### ISSUE TITLE
Add RTD link in each github repository

### ISSUE THREAD

**Issue by tritemio** [jupyter/jupyter#10]
To facilitate discovering the docs, all the github repositories under the jupyter organization should have a link to the readthedocs documentation (when existent).

Preferably the link should be put in the "heading" next to the repository description, but also a simple link in the README would be enough.

For one, the "jupyter" repo should have a link to jupyter.readthedocs.org.

**Comment by takluyver** [comment]
OK, I've gone round adding these links to all the repos I could think of. Leave a comment if you find any that you think still need a link.

**Comment by tritemio** [comment]
Great, thanks!
