### ISSUE TITLE
Feature request: VCS, metadata friendly file format

### ISSUE THREAD

**Issue by hcarvalhoalves** [jupyter/jupyter#102]
Current notebook format mixes metadata with code, and local cell changes end up touching the entire underlying file. It may also contain encoded binary blobs. Those aspects make the file format unsuitable for diff'ing in a version control system.

Quiver's data format is a well thought format that could be adopted fully, or used as a baseline:

https://github.com/HappenApps/Quiver/wiki/Quiver-Data-Format

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Specifically for diffing, you cuold take a look at https://github.com/jupyter/nbdime and for a text-only (binary blob free) format there's https://github.com/mwouts/jupytext. There's also a group of people who are collaborating on another text-based format: https://github.com/jupyter/enhancement-proposals/pull/103

Thanks and happy hacking! :bowtie:
