### ISSUE TITLE
moving cells up / down: add autoscroll

### ISSUE THREAD

**Issue by DSLituiev** [jupyter/jupyter#105]
When moving a cell up or down, I need to scroll manually to follow where the cell goes. Is there a way to add an autoscroll on moving up/down?

**Comment by minrk** [comment]
I think this is a likely focus-related bug, possibly introduced by the recent multi-select.

cc @ellisonbg @jdfreder for focus/select fun.

**Comment by jdfreder** [comment]
![fake excitement](https://ak-hdl.buzzfed.com/static/enhanced/webdr05/2013/5/6/13/anigif_enhanced-buzz-8841-1367859684-8.gif)
