### ISSUE TITLE
Jupyter won't connect to a kernel

### ISSUE THREAD

**Issue by hekevintran** [jupyter/jupyter#106]
I'm using django-extensions and I ran `shell_plus --kernel` and it output:

```
To connect another client to this kernel, use:
    --existing kernel-6690.json
```

Then I tried connecting with Jupyter:

```
$  jupyter notebook --existing=kernel-6690.json
[W 10:44:59.290 NotebookApp] Unrecognized alias: '--existing=kernel-6690.json', it will probably have no effect.
...
```

Why doesn't Jupyter connect to the kernel?

**Comment by willingc** [comment]
@hekevintran Would you mind trying this command:
```
jupyter notebook --existing kernel-6690.json
```

It looks like there is an extra "=" between 'existing' and 'kernel'.

**Comment by hekevintran** [comment]
@willingc The "=" is a standard way to pass arguments in bash.  Running that command returns a slightly different response:

```
[C 11:43:47.383 NotebookApp] Bad config encountered during initialization:
[C 11:43:47.383 NotebookApp] Unrecognized flag: '--existing'
```

Reviewing https://github.com/ipython/ipython/issues/4066, it appears that the notebook is not able to connect to kernels.  In other words for all the talk about how Jupyter notebook is separated into a kernel and frontend it's actually not and this information is not written in any documentation I could find.
