### ISSUE TITLE
OSX El Capitan 

### ISSUE THREAD

**Issue by jlamb85** [jupyter/jupyter#107]
Not sure about other version but to run the jupyter notebook on OS X El Capitan you run 
jupiter-notebook not jupyter notebook

**Comment by takluyver** [comment]
What do you get if you run `jupyter notebook`?

**Comment by jlamb85** [comment]
I typed jupyter and hit tab.   These are my options
MacBook-Pro:~ user1$ jupyter-
jupyter-console      jupyter-kernelspec   jupyter-nbconvert    jupyter-nbextension  jupyter-notebook     jupyter-qtconsole    jupyter-trust

**Comment by Carreau** [comment]
What / how  did you install ?

`jupyter` is just a command that will in the backend use all these `jupyter-*`.

**Comment by jlamb85** [comment]
I used pip to install

**Comment by jlamb85** [comment]
I am trying to switch to anaconda.  I will try it.

**Comment by jlamb85** [comment]
Got it to work.  Thanks

**Comment by willingc** [comment]
@jlamb85 Glad you have it working with anaconda. :+1:

**Comment by Carreau** [comment]
> I used pip to install


For later reference: 

There are several way to pip install, and which package you did install might also have an effect.
`pip install notebook`, or `pip install jupyter` will have a different effect. One can also use `python -m pip`
