### ISSUE TITLE
"kernel dead" in Jupyter notebook using python 3

### ISSUE THREAD

**Issue by dharurgobi** [jupyter/jupyter#115]
i am using jupyter on windows. Whenever i start python3 in jupyter notebook, i get the message kernel dead. 

Dead kernel
The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. 
If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

i get the above message in notebook dashboard

[I 23:07:08.365 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 9938cea3-6528-4a27-b4c3-ee906d748bfb restarted
Traceback (most recent call last):
  File "c:\users\dharini\appdata\local\programs\python\python35-32\lib\runpy.py"
, line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dharini\appdata\local\programs\python\python35-32\lib\runpy.py"
, line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\dharini\appdata\local\programs\python\python35-32\lib\site-pack
ages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "c:\users\dharini\appdata\local\programs\python\python35-32\lib\site-pack
ages\traitlets\config\application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "c:\users\dharini\appdata\local\programs\python\python35-32\lib\site-pack
ages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\dharini\appdata\local\programs\python\python35-32\lib\site-pack
ages\ipykernel\kernelapp.py", line 417, in initialize
    self.init_io()
  File "c:\users\dharini\appdata\local\programs\python\python35-32\lib\site-pack
ages\ipykernel\kernelapp.py", line 316, in init_io
    self.patch_io()
  File "c:\users\dharini\appdata\local\programs\python\python35-32\lib\site-pack
ages\ipykernel\kernelapp.py", line 326, in patch_io
    faulthandler_register = faulthandler.register
AttributeError: module 'faulthandler' has no attribute 'register'
[W 23:07:11.369 NotebookApp] KernelRestarter: restart failed
[W 23:07:11.369 NotebookApp] Kernel 9938cea3-6528-4a27-b4c3-ee906d748bfb died, r
emoving from map.
ERROR:root:kernel 9938cea3-6528-4a27-b4c3-ee906d748bfb restarted failed!
[W 23:07:11.390 NotebookApp] Kernel deleted before session
[W 23:07:11.392 NotebookApp] 410 DELETE /api/sessions/1cca4919-305f-4b4f-acdd-b2
a614fd2638 (::1) 3.00ms referer=http://localhost:8888/notebooks/Untitled.ipynb?k
ernel_name=python3

i get the above message in command prompt.. 
i installed jupyter using pip.. i am new to programming in python and also jupyter. i installed in this order, python3.5, pip, ipython notebook and then jupyter notebook. is there any blunder mistake i have done. I have attached the kernelapp file here. Is there a way to rectify the error 'no attriblute register in fault handler module'. please help. 

[kernelapp.txt](https://github.com/jupyter/jupyter/files/149483/kernelapp.txt)

**Comment by takluyver** [comment]
Sorry, we released a version that had a problem on Windows. We released a fix the other day - run `pip install --upgrade ipykernel` to get it.

**Comment by dharurgobi** [comment]
thanks.. issue resolved..

**Comment by yyf** [comment]
I had a dead kernel when launching jupyter notebook. Currently using python 2.7. Tried the same pip install --upgrade ipykernel, but had the following error, any suggestion? Thanks. 

Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, filterfalse, map
  File "/Library/Python/2.7/site-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ImportError: No module named extern

**Comment by takluyver** [comment]
That sounds like your setuptools install is broken :-S. If you're not sure how to uninstall that, try removing and reinstalling Python itself.
