### ISSUE TITLE
Using different favicon's would make navigation easier

### ISSUE THREAD

**Issue by dubourg** [jupyter/jupyter#118]
Since we are tending toward a full OS in the browser... ;-) I think it would help to be able to differentiate the jupyter-js-filebrowser, jupyter-js-editor, jupyter-js-terminal and jupyter-js-notebook navigation tabs from the favicon.

**Comment by willingc** [comment]
@dubourg Thanks for passing along the tip. I have migrated this issue to the jupyter/jupyter-js-notebook issue tracker https://github.com/jupyter/jupyter-js-notebook/issues/53 since that repo will get more developer views and discussion there.

I'm going to close it here.
