### ISSUE TITLE
ReadTheDocs - Sustainability and Ads

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter#119]
On Monday, ReadTheDocs changed their service to opt in projects for display of a small ad in the bottom left of the docs (they do not allow tracking of users by third party scripts). See [blog post](https://blog.readthedocs.com/ads-on-read-the-docs/) for details.

For all the project documentation that I have permissions on, I have disabled the advertising feature for the following reasons:

- this is a decision that should be made by the larger project community or steering council to opt in, if desired
- I personally support ReadTheDocs financially with the ReadTheDocs Gold contribution monthly.
- I also contribute my time as I know other devs on Jupyter do as well.

It is my belief that the advertising feature was added to address commercial projects who are "free riders" in an economic sense. I believe that RTD is committed to the open source community and the needs of the community.

For now, I will keep the ads turned off unless the consensus is different. Thanks!

cc/ @fperez @ellisonbg @minrk @carreau @takluyver @jhamrick @jdfreder who are active with the docs. Others, please feel free to voice your thoughts as well.

**Comment by Carreau** [comment]
I saw one of their adds, I didn't found it intrusive.
So I do not have any object on reenabling it if the consensus is to do so.

**Comment by jdfreder** [comment]
I'm okay with supporting them through adverts.  I'm grateful they've given us the ability to toggle the adverts.  As a semi high visibility open source project, displaying non-intrusive adverts on our docs may really help them.  I personally don't pay for RTD Gold though, so I may feel more obligated to contribute just because I'm not currently.

**Comment by jdfreder** [comment]
@willingc how does this affect, if at all, the template work we've been doing?

**Comment by minrk** [comment]
The ads seem reasonable, and it seems like a decent way to support them providing us a valuable service. No objection from me on letting the ads be displayed on our docs, at least with how they are currently.

**Comment by willingc** [comment]
@jdfreder Not at all. The message I left on ipywidgets for you is a sphinx bug with markdown.

**Comment by fperez** [comment]
For the record, I've looked at the ads and read their post, and I'm also OK with it.  I think, however, this is an issue we can revisit if they ever change their policies (add tracking, flashing/animated/obtrusive ads, etc).

**Comment by fperez** [comment]
ps - unless we get strong dissent from anyone in say a week,  I suggest closing this as our current record of the decision, so it doesn't dangle open.

**Comment by minrk** [comment]
:+1: thanks, @fperez

**Comment by takluyver** [comment]
I'm OK with enabling the adverts in their current form (not moving or overly distracting, not tracking users). As @fperez said, we can come back to the decision if they get worse.

For reference, here's what an advert looks like in the sidebar of Pynsist (as a random project where I haven't disable adverts):

![screenshot from 2016-03-16 13 39 30](https://cloud.githubusercontent.com/assets/327925/13814020/8dd38308-eb7c-11e5-85da-51fc26ab1dfa.png)

**Comment by willingc** [comment]
Closing since the consensus seems to be that we support RTD. I've enabled the ads.
