### ISSUE TITLE
Install instructions for upgrading from IPython < 4

### ISSUE THREAD

**Issue by takluyver** [jupyter/jupyter#12]
The install page should have some mention of how to upgrade from earlier versions of the notebook. I think this should be just a matter of installing the Jupyter package, but people will probably want some reassurance.

@asmeurer, have you thought about what the packaging will look like on conda? On PyPI, we'll have a `jupyter` metapackage that just depends on all of our other packages. It would be convenient if this pattern was the same in conda. Is there a mechanism to deprecate or rename the `ipython-notebook` package? In Debian packaging, I know it would become a 'transitional' package, expressing a dependency on its new name, for instance.

**Comment by asmeurer** [comment]
Conda doesn't support anything like this directly. I think the best we can do is to print a message to the terminal when a new version is installed that the package has been renamed. This is what we have done with binstar, which was renamed to `conda-server` (try `conda install binstar`). 

To clarify, what exactly should the conda packages be called? Right now we have `ipython`, `ipython-notebook`, and `ipython-qtconsole`, where the last two are metapackages.

**Comment by takluyver** [comment]
I'd suggest you follow our packaging as far as possible, i.e.

```
ipython
ipykernel (depends on ipython>=4)
ipyparallel
ipywidgets
jupyter_core
jupyter_client
nbformat
nbconvert
notebook (you might want to call this jupyter-notebook instead)
qtconsole
jupyter_console
jupyter (the metapackage depending on the other bits)
```

**Comment by takluyver** [comment]
I've added upgrade instructions to the install page, assuming for now that `jupyter` will be the name of the metapackage for conda as well as for pip.

**Comment by asmeurer** [comment]
our plan is to match the conda package names to the pypi package names.

**Comment by takluyver** [comment]
Great, thanks. We're nearly there on the release. `ipywidgets` is out now, so there's just the `jupyter` metapackage and `ipython` itself to go.

**Comment by takluyver** [comment]
Closing as those instructions are there now.
