### ISSUE TITLE
Python log in the jupyter notebook appears only in the terminal, not in the output cell

### ISSUE THREAD

**Issue by ziky90** [jupyter/jupyter#120]
I am using `jupyter` notebook and since short time ago logs stopped to appear in output cells and started to appear only in the terminal.

I have described the problem here:
http://stackoverflow.com/questions/35936086/jupyter-notebook-does-not-print-logs-to-the-output-cell/35940918#35940918

To summarise this, I have found that since there is not specified exact version of `ipykernel` package in setup in `jupyter`. There was changed `ipykernel`'s version that is being installed.

Logging to output cell works correctly for `ipykernel==4.2.2` and earlier, but since `4.3.0` https://github.com/ipython/ipykernel/releases/tag/4.3.0 logs goes to terminal instead of the output cell.

I am not sure, but my guess is that the problem is caused by this commit: https://github.com/ipython/ipykernel/commit/65b6144d191b867c67d9724cd5e7b94e9f688d83

**Comment by captainsafia** [comment]
Thanks for opening the issue, @ziky90 and gathering all the relevant information.

Do you mind closing this issue and opening it in ipython/ipykernel where it is more relevant and you are more likely to get a response from one of the developers on the kernel?

**Comment by ziky90** [comment]
Ok thanks @captainsafia 
I have opened it here since I was not sure what is relation between `jupyter` and `ipykernel` projects. 
It seemed to me just as an external dependency and maybe new stuff might have not been bug, but feature for `ipykernel`, but causing obvious bug as a dependency in `jupyter`.
I have opened the issue in `ipykernel` project here https://github.com/ipython/ipykernel/issues/111
