### ISSUE TITLE
Rename option --python to export code from other kernels

### ISSUE THREAD

**Issue by juliohm** [jupyter/jupyter#121]
Currently we can export Julia code with:

```bash
$ jupyter nbconvert --python mynotebook.ipynb
```

It would be great to rename the option to `--code` or something.

**Comment by takluyver** [comment]
I think `--to script` is what you're looking for - it should already work.

**Comment by juliohm** [comment]
Perfect @takluyver, I missed that option.

**Comment by willingc** [comment]
@takluyver I want to add a more prominent examples in the nbconvert docs (--to script is already documented) for this. Would this be the correct syntax for examples for converting julia and R notebooks? Thanks.

```bash
jupyter nbconvert --to script my_julia_notebook.ipynb --output my_julia_script.jl
jupyter nbconvert --to script my_r_notebook.ipynb --output my_r_script.r
```

**Comment by juliohm** [comment]
@willingc I didn't try the `--output` option, but I tried the rest of the command and it is working fine.

**Comment by willingc** [comment]
@juliohm Thanks. Adding to the nbconvert docs in https://github.com/jupyter/nbconvert/pull/270 :sunny:
