### ISSUE TITLE
In-console editor: how do I insert tabs?

### ISSUE THREAD

**Issue by ctb** [jupyter/jupyter#122]
Hi all,

I'm trying to create & edit a Makefile, but can't figure out how to get the editor to save tabs (which are needed).  I can introduce tabs in vim mode with C-q TAB, but I can't save the tabs into the resulting text file. Any suggestions?

**Comment by ctb** [comment]
@minrk sez:

```
There isn’t a GUI toggle, but if you run this code in the javascript console for an editor page:

      Jupyter.editor.update_codemirror_options({indentWithTabs: true});

It will enable indentation with tabs in the editor (same thing with false will change it back).
```
I note that this requires that the ~/.jupyter/notebook directory already exist; and, since it creates ~/.jupyter/notebook/edit.json, that file can just be created in the shell too. (I'm doing this in mybinder.)

**Comment by minrk** [comment]
[This extension](And [this extension](https://github.com/minrk/ipython_extensions/blob/master/nbextensions/editor-tabs.js) should give you a toggle in the edit menu: 

<img width="213" alt="screen shot 2016-03-16 at 15 19 26" src="https://cloud.githubusercontent.com/assets/151929/13815381/a2caf8aa-eb8a-11e5-91e7-4ff68083bc68.png">

Complete shell installation for the extension:

```bash
wget https://raw.githubusercontent.com/minrk/ipython_extensions/master/nbextensions/editor-tabs.js
jupyter nbextension install editor-tabs.js
jupyter nbextension enable --section edit editor-tabs
```

**Comment by igg** [comment]
The above does not work for Jupyter 4.1.1/iPython 5.1.0.
Based on [http://stackoverflow.com/a/35623770](http://stackoverflow.com/a/35623770), create `~/.jupyter/nbconfig/edit.json`:

    {
        "Editor": {
            "codemirror_options": {
                "indentWithTabs": true
            }
        }
    }
If this file already exists and has JSON in it, add the lines between the two outer brackets above to the existing file before it's last bracket, after inserting a comma. Then create `~/.jupyter/nbconfig/notebook.json` with:

    {
        "CodeCell": {
            "cm_config": {
                "indentWithTabs": 2
            }
        }
    }
Same as above if notebook.json already exists and has JSON already in it: Add the lines between the outer brackets to the existing file's outer brackets after a comma.

**Comment by krinsman** [comment]
Just to elaborate on or clarify the answer above, in the paths given above, make sure to replace 

`~/.jupyter/nbconfig`

with whatever the output of the terminal command `jupyter --config-dir` is on your machine.

If you only want to change the tab feature in the text editor, then only change `edit.json`; if you only want to change the tab feature in notebook cells, only change `notebook.json`. (Obviously, if you want to change the feature in both the text editor and the notebook cells, change both of the above files.)

**Comment by Harrypotterrrr** [comment]
> Just to elaborate on or clarify the answer above, in the paths given above, make sure to replace
> 
> `~/.jupyter/nbconfig`
> 
> with whatever the output of the terminal command `jupyter --config-dir` is on your machine.
> 
> If you only want to change the tab feature in the text editor, then only change `edit.json`; if you only want to change the tab feature in notebook cells, only change `notebook.json`. (Obviously, if you want to change the feature in both the text editor and the notebook cells, change both of the above files.)

Thanks! It really works for the latest version!

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
