### ISSUE TITLE
pip3 install jupyter needs more info

### ISSUE THREAD

**Issue by richardgmcmahon** [jupyter/jupyter#123]
hello, I have installed using

pip install --user jupyter

works fine:

jupyter notebook

gives the error:

jupyter: Command not found.

I assume that some additional configuration is needed

**Comment by takluyver** [comment]
Probably the directory pip installs scripts to is not on your `PATH`. Where that directory is depends on your platform - on Linux, it is `~/.local/bin` by default.

**Comment by Qjs** [comment]
Just for clarity's sake, you can fix this by adding `export PATH="/home/user/.local/bin:$PATH"` to your ~/.bashrc if you're on linux. Be sure to `source ~/.bash` afterwards.

**Comment by willingc** [comment]
Closing this issue as resolved. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
