### ISSUE TITLE
File called tokenize.py causes Jupyter notebook to stop working.

### ISSUE THREAD

**Issue by andykitchen** [jupyter/jupyter#125]
Hi Everyone!

I've just noticed that if you happen to have a file called `tokenize.py` in your current directory. Just trying to launch a kernel fails.

Here's the version I'm running:

```shell
$ conda list | grep jupyter
jupyter                   1.0.0                    py27_1    defaults
jupyter_client            4.1.1                    py27_0    defaults
jupyter_console           4.1.0                    py27_0    defaults
jupyter_core              4.0.6                    py27_0    defaults
```

Steps to reproduce:
```shell
$ mkdir test
$ cd test
$ touch tokenize.py
$ jupyter notebook
# Create a new notebook, starting the kernel fails!
```

Thanks for all the good work,

Kind Regards

AK

**Comment by takluyver** [comment]
Yes, if you use the same name as a module that IPython tries to import and use, you will break it. It's generally bad practice to use the name of a standard library module like [tokenize](https://docs.python.org/3/library/tokenize.html) anyway. See my explanation on ipython/ipykernel#112 for more details.
