### ISSUE TITLE
Create a developer guide - action item from dev mtg

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter#128]
We will rework the existing Contributor Documentation to create a developer guide similar to the CPython Dev Guide.
Items to add: 
- Style guidelines (autopep8, white space in PRs)
- PR courtesy

FYI @jhamrick, @takluyver, @damianavila, @yuvipanda

**Comment by jhamrick** [comment]
We can probably start with what's already in the contributor readme: 

* https://github.com/ipython/ipython/blob/master/CONTRIBUTING.md
* https://github.com/ipython/ipython/wiki/Dev:-GitHub-workflow
* https://github.com/ipython/ipython/wiki/Dev%3A-Closing-pull-requests

In general there are a lot of things already in the [IPython wiki](https://github.com/ipython/ipython/wiki), they are just scattered and hard to find and should be consolidated in the new contributor documentation.

**Comment by willingc** [comment]
Sounds like a good place to start. Brian and I were discussing this recently. Thanks for the links @jhamrick.

**Comment by willingc** [comment]
A WIP PR #132 has been opened.

**Comment by jhamrick** [comment]
Also @willingc did you see #129 ?

**Comment by willingc** [comment]
I did see #129. Just merged it. I may reorder the contents and overall doc index. Will ping you when I do. Thanks!

**Comment by willingc** [comment]
Partially addressed by #136

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
