### ISSUE TITLE
Clean up gitter rooms

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#130]
- Pick which rooms to delete
- archive them
- Announce to the ML.
- all links to jupyter/help.

Remove badges. 

I suggest removing all rooms with less than 50 users.

ping @williingc

**Comment by Carreau** [comment]
Ok, cannot archive.

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
