### ISSUE TITLE
How to downgrade Julia notebooks?

### ISSUE THREAD

**Issue by juliohm** [jupyter/jupyter#131]
I have written tens of Julia notebooks using Julia v0.5 (dev) and now I am on Julia v0.4 (stable). Is there any way to downgrade the notebook so that they can be run by the older kernel?

**Comment by takluyver** [comment]
If I'm understanding you correctly, you should be able to switch to the older Julia kernel from the Kernel, Change kernel menu.

**Comment by juliohm** [comment]
@takluyver thank you, missed that simple option, sorry for the noise.
