### ISSUE TITLE
OCaml syntax highlighting

### ISSUE THREAD

**Issue by dpinsard** [jupyter/jupyter#133]
When I load a OCaml Notebook, code cells are correctly highlighted,
but new cells  are not, until I save and reload the notebook.

Metadata notebook :

```
{
  "language_info": {
    "version": "4.1.0",
    "name": "ocaml"
  },
  "kernelspec": {
    "name": "ocaml",
    "display_name": "OCaml",
    "language": "ocaml"
  }
}
```

The version of the notebook server is _4.1.0_ and is running on:
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4]

**Comment by takluyver** [comment]
I'm guessing that this is an issue with IOCaml's [custom javascript](https://github.com/andrewray/iocaml/blob/master/profile/static/custom/custom.js). Pinging @andrewray.

**Comment by willingc** [comment]
Passing along the installation info from the IOCaml wiki and a Docker playground mentioned in the wiki:

- [Information from iocaml wiki](https://github.com/andrewray/iocaml/wiki/jupyter)
- [Docker playground for OCaml](https://github.com/signalpillar/ocaml-playground)

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
