### ISSUE TITLE
Blog: link to jupyter.org

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#139]
With the recent release of [4.2 on hackernews](https://news.ycombinator.com/item?id=11507454) and [reddit](https://www.reddit.com/r/programming/comments/4f08gz/jupyter_notebook_42_released/) lots of people complain that you can't go from the blog to the main homepage. 

So the "Home" button or the Jupyter logo link in Ghost **should** link to the main webpage. 

Ping @ellisonbg @willingc

**Comment by Carreau** [comment]
As there does not seem to be a config options for that, 
I propose to insert the following in  footer: 
```javascript
<script>
document.onreadystatechange = function(){ 
    (document.getElementsByClassName('blog-logo')[0]||{}).href = 'https://jupyter.org';
}
</script>
```

**Comment by willingc** [comment]
@Carreau Great idea. Unfortunate that the Ghost default theme doesn't support.

Your suggestion seems good (though I'm far from a JS expert that's your superpower). I noticed this in the Ghost docs: http://academy.ghost.org/basic-casper-theme-customizations/ Passing along in case you see something useful in it.

Overall, a big +1 to being able to get to Jupyter webpage from Ghost blog. :+1:

**Comment by Carreau** [comment]
> Your suggestion seems good (though I'm far from a JS expert that's your superpower). I noticed this in the Ghost docs: http://academy.ghost.org/basic-casper-theme-customizations/ Passing along in case you see something useful in it.

Theme customisation change the appearance, we actually need to change the content, so IIUC custom theme will not help.

**Comment by Carreau** [comment]
Script no injected on the blog. It works.

**Comment by Carreau** [comment]
no -> now

**Comment by willingc** [comment]
@Carreau Indeed it does :cake: Nice!

Closing this issue. Thanks @Carreau.
