### ISSUE TITLE
Fill out the IPython projects section

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyter#144]
As noted to me @szeitlin, the IPython Projects section is rather blank on ReadTheDocs.

**Comment by willingc** [comment]
@rgbkrk Yes, it is, but only temporarily. Nailing down the master documentation outline next week and moving #138 forward. Please let them know that we :heart: IPython projects. Thanks 🐶

**Comment by ivanov** [comment]
a reminder years later that you all rock! closing this <3
