### ISSUE TITLE
Python3 Kernel error after anaconda install

### ISSUE THREAD

**Issue by soedr** [jupyter/jupyter#147]
I am unable to run jupyter notebook successfully, and am getting the error `FileNotFoundError: [Errno 2] No such file or directory: '//anaconda/envs/py35/bin/python'`. I have uninstalled anaconda and jupyter and reinstalled, but am still getting the same result. 

How do I solve it?

```
Traceback (most recent call last):
  File "/Users/martin/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 458, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/Users/martin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/martin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/martin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/martin/anaconda/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 58, in post
    sm.create_session(path=path, kernel_name=kernel_name))
  File "/Users/martin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/martin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/martin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/martin/anaconda/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 73, in create_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/Users/martin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/martin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/martin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/Users/martin/anaconda/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/martin/anaconda/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/martin/anaconda/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/Users/martin/anaconda/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/martin/anaconda/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/martin/anaconda/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/Users/martin/anaconda/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '//anaconda/envs/py35/bin/python'
```

**Comment by takluyver** [comment]
What do you get from `jupyter kernelspec list`?

**Comment by soedr** [comment]
I get 
`Available kernels:
  python2    /Users/martin/Library/Jupyter/kernels/python2
  python3    /Users/martin/Library/Jupyter/kernels/python3`

However, I reinstalled ipykernel using `python2 -m pip install ipykernel` and `python2 -m ipykernel install --user` and that seems to have solved the problem!

**Comment by takluyver** [comment]
Great. Yes, the error was likely because you had a kernelspec referring to an env you had later deleted.

**Comment by soedr** [comment]
Sorry to revisit this, but the previous fix seems to work only in some cases. I am getting a similar error `FileNotFoundError: [Errno 2] No such file or directory: '//anaconda/envs/py35/bin/python'` when trying to work on a notebook shared with me by another user. 

Is there a handy documentation or suggested solution that you can please refer to that prevents this issue? Am new to jupyter so apologies for the basic issue.

Thank you.

**Comment by takluyver** [comment]
I'm guessing that you reinstalled your `python2` kernelspec, but not the `python3` one, and the notebook you're getting from another user has `python3` in the metadata. You'll probably need to create or switch to a Python 3 environment, install ipykernel and run `python -m ipykernel install --user` again.

**Comment by soedr** [comment]
I removed the kernels listed under `jupyter kernelspec list` and the created a new python2 kernel using
`conda create -n py27 python=2 ipykernel
source activate py27
python -m ipykernel install --user`
as found [here](https://ipython.readthedocs.io/en/latest/install/kernel_install.html) with sematic edits `py27` instead of `ipykernel_py2` to reflect the error that jupyter showed earlier and that solved it!

Thanks!

**Comment by takluyver** [comment]
You're welcome :-)

**Comment by sudharsanj** [comment]
While im running this code im getting an error that i mentioned below , i dont know how to solve , can anyone please help me to solve this issue.


CODE :
# In[10]:

with detection_graph.as_default():
  with tf.Session(graph=detection_graph) as sess:
    while True:
      ret, image_np = cap.read()
      # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
      image_np_expanded = np.expand_dims(image_np, axis=1)
      image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
      # Each box represents a part of the image where a particular object was detected.
      boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
      # Each score represent how level of confidence for each of the objects.
      # Score is shown on the result image, together with the class label.
      scores = detection_graph.get_tensor_by_name('detection_scores:0')
      classes = detection_graph.get_tensor_by_name('detection_classes:0')
      num_detections = detection_graph.get_tensor_by_name('num_detections:0')
      # Actual detection.
      (boxes, scores, classes, num_detections) = sess.run(
          [boxes, scores, classes, num_detections],
          feed_dict={image_tensor: image_np_expanded})
      # Visualization of the results of a detection.
      vis_util.visualize_boxes_and_labels_on_image_array(
          image_np,
          np.squeeze(boxes),
          np.squeeze(classes).astype(np.int32),
          np.squeeze(scores),
          category_index,
          use_normalized_coordinates=True,
          line_thickness=8)

      cv2.imshow('object detection', cv2.resize(image_np, (800,600)))
      if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break


ERROR :

C:\Users\Dass6\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  if sys.path[0] == '':
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-106-bb831561a18b> in <module>()
     22       (boxes, scores, classes, num_detections) = sess.run(
     23           [boxes, scores, classes, num_detections],
---> 24           feed_dict={image_tensor: image_np_expanded})
     25       # Visualization of the results of a detection.
     26       vis_util.visualize_boxes_and_labels_on_image_array(

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    885     try:
    886       result = self._run(None, fetches, feed_dict, options_ptr,
--> 887                          run_metadata_ptr)
    888       if run_metadata:
    889         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1077             feed_handles[subfeed_t] = subfeed_val
   1078           else:
-> 1079             np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
   1080 
   1081           if (not is_tensor_handle_feed and

~\Anaconda3\lib\site-packages\numpy\core\numeric.py in asarray(a, dtype, order)
    490 
    491     """
--> 492     return array(a, dtype, copy=False, order=order)
    493 
    494 

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by mchang429** [comment]
Hi, when I run jupyter kernelspec list I get jupyter not installed. Is my installation of anaconda incomplete?

**Comment by mchang429** [comment]
Hi, where should I be typing jupyter kernelspec list?

**Comment by spring-haru** [comment]
For Mac, I guess `Terminal`. 

Just for record on @takluyver  answer which saved me. If there is a problem in an env:
```
python -m ipykernel install --user --name <my_env>
```
