### ISSUE TITLE
Copy works but not paste on Terminal window

### ISSUE THREAD

**Issue by shwina** [jupyter/jupyter#148]
Tested on Firefox and Safari (Mac OS X). After opening a terminal via Jupyter, I can copy text out of the terminal, but not paste into it (tried right click as well as menu bar->Edit).

**Comment by takluyver** [comment]
Issues like this are likely to be with [term.js](https://github.com/chjj/term.js), the terminal component we use. It's not very actively maintained, but there's some talk of moving it to an organisation so more people can collaborate on it.

**Comment by shwina** [comment]
Thanks, @takluyver!
