### ISSUE TITLE
Jupyter should make a .exe on Windows

### ISSUE THREAD

**Issue by orf** [jupyter/jupyter#15]
After installing Jupyter on Windows it seems the "jupyter" command isn't turned into an executable, and thus can't be run through the windows command line. It creates a `jupyter` file containing:

```python
#!C:\Python34\python.exe
"""Launch the root jupyter command"""

from jupyter_core.command import main

if __name__ == '__main__':
    main()
```

But obviously this cant be run on Windows without doing `C:\python\python.exe C:\python\scripts\jupyter --help`, which is not as nice as just `jupyter`

**Comment by takluyver** [comment]
Thanks, I'll investigate what we can do about this.

**Comment by minrk** [comment]
How did you do the installation?

**Comment by orf** [comment]
Just did pip install Jupiter

**Comment by takluyver** [comment]
jupyter/jupyter_core#41 is part of the fix (it will create jupyter.exe, at least)

**Comment by minrk** [comment]
An alternate implementation would be to use execfile on Windows, which would force the commands to be Python on Windows, which I'm okay with.

**Comment by willingc** [comment]
Since significant merges were done last year related to the this issue, I'm closing this issue. If there is still outstanding work to be done, it may be better to reopen as a new issue in a project repo.
