### ISSUE TITLE
[docs/theme] Fix sidebar affix.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#153]
Sidebar affix "jump" down when it hits the top of screen, 

setting the following seem to do the trick:

```
.bs-sidenav {
    top: 49px;
}
```

Now need to understand why `49px`, and set it in the right place.

**Comment by willingc** [comment]
@jdfreder Any thoughts or memories?

**Comment by willingc** [comment]
@Carreau I wonder if we should put these issues in jupyter/jupyter-sphinx-theme at some point and fix for all.

**Comment by Carreau** [comment]
> jupyter/jupyter-sphinx-theme

Not sure where they belong, if it needs fix in sphinx-theme, I'll move that upstream, but I want them filled for tracking.

**Comment by willingc** [comment]
This is likely where the majority would be fixed: https://github.com/jupyter/jupyter-sphinx-theme

It doesn't really matter where the :cat: and :dog: are filed :smile:. Let's just get them all documented. Thanks.

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
