### ISSUE TITLE
[docs/theme] Smaller font too small

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#154]
12pt for a font is too small, especially since we use modifier like font-size 90%, making some text less than 11pt on screen. I don't want  to need my magnifying glass to read on my 30" screen.

**Comment by wotanii** [comment]
Increasing the smallest font size would also mean to increase all other font-sizes, too. 

On both my 28'' UHD screen and on my 13'' HD screen I'm used to zoom in on every single website. And when I zoom the juniper-docs as much as I usually zoom github, it looks fine to me.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. I think we've migrated away from whatever theme was being used when this issue was made.

Thanks everyone and happy hacking! :bowtie:
