### ISSUE TITLE
[docs/theme] Previous next on top and bottom of all pages. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#155]
Nice readable documentation should (hopefully) be readable linearly, 
nice examples are: [Julia docs](http://docs.julialang.org/en/release-0.4/) and [rust docs/the rust book (now the same thing)](https://doc.rust-lang.org/book/), where you can literally land on the first page:
- start reading, 
- hit next
- repeat

And spend 4h learning about stuff. 
Giving user the choice is a bad thing because: 1) You don't know where you want to go 2) you won't remember were you went.

**Comment by willingc** [comment]
@Carreau The [full contents](http://jupyter.readthedocs.io/en/latest/contents.html) where one can read linearly is found on the [landing page](http://jupyter.readthedocs.io/en/latest/).

I'm not opposed to reworking the landing page; however, @fperez suggested the two column landing page. This would seem to be a good issue to do usability testing on. cc/ @ellisonbg

**Comment by Carreau** [comment]
Landing page has no "next button":

![screen shot 2016-05-10 at 16 52 07](https://cloud.githubusercontent.com/assets/335567/15166025/921018d6-16cf-11e6-8921-f1ce1a923931.png)

vs a random page:

![screen shot 2016-05-10 at 16 52 13](https://cloud.githubusercontent.com/assets/335567/15166029/9e3ac28c-16cf-11e6-9d44-16bbd1947a5f.png)

I think it's confusing if you click on a section , click `previous`, `previous`, ...`previous`. And don't land on "index.html", so content should likely get a "previous" link to `index` and `index` a `next` to content.

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
