### ISSUE TITLE
[docs/theme] `Previous` link missplaced. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#158]
the `ul.pager` container is in the wrong div leading to `prev` being to far left, outside of the "content" of the docs:

![screen shot 2016-05-10 at 16 57 15](https://cloud.githubusercontent.com/assets/335567/15166096/6c8c52a4-16d0-11e6-819c-ca5a7fc4e7b9.png)

While the following would be more appropriate. 

![screen shot 2016-05-10 at 16 57 42](https://cloud.githubusercontent.com/assets/335567/15166105/83103ae0-16d0-11e6-9e93-aec7aeeb7d64.png)

The size of the font of the target should likely be bigger.

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
