### ISSUE TITLE
Markdown syntax imcompatibility (headings) with IPython 3.x created notebooks

### ISSUE THREAD

**Issue by Puggie** [jupyter/jupyter#16]
Notebooks that were created in IPython 3.x have there Markdown cells not properly shown in Jupyter 4.0. At least this goes for headings. After a small investigation it appears that the Markdown syntax has slightly changed.
In IPython 3.x, the following showed up properly as a heading level 1 in a Markdown cell in a notebook:
`#Heading level 1`
In Jupyter 4.0, a space needs to be added after the hashtag to make it work:
`# Heading level 1`

**Comment by Carreau** [comment]
Hum interesting, that might be a change in behavior in our dependencies. 
Thanks for the report ! We'll try to fix it if possible. 

(usually notebook issues are on https://github.com/jupyter/notebook)

**Comment by Carreau** [comment]
Quick note, it seem like `hash-space-title` is the direction that most markdown parsers are starting to enforce, and fighting against that will be really hard. Even for us.

I would suggest trying to fix your headers when possible for now, we might make a tool to fix notebook en-masse.

**Comment by minrk** [comment]
migrated to jupyter/notebook#276
