### ISSUE TITLE
Version strings in jupyter.py and setup.py

### ISSUE THREAD

**Issue by hastebrot** [jupyter/jupyter#160]
The version strings in `jupyter.py` and `setup.py` were not updated since 1.0.0. When I run `pip show jupyter` it lists me `Version: 1.0.0`.

`jupyter.py` (excerpt):
~~~
__version__ = '1.0.0'
~~~

`setup.py` (excerpt):
~~~
setup_args = dict(
    name                = 'jupyter',
    version             = '1.0.0',
    description         = "Jupyter metapackage. Install all the Jupyter components in one go.",
~~~

**Comment by hastebrot** [comment]
Nevermind, I did not understand your versioning is package-independent. :smile:

~~~
$ jupyter --version
4.1.0
$ jupyter notebook --version
4.2.0
$  jupyter console --versio
4.1.1
~~~

Will close this issue.

**Comment by takluyver** [comment]
Yep, `jupyter` is a metapackage that depends on all the pieces that contain code.
