### ISSUE TITLE
ignoring allow_origin="*"

### ISSUE THREAD

**Issue by ptulpen** [jupyter/jupyter#161]
Hello,
I try to use jupyterhub behind a nginx proxy, but currently I get 
Blocking Cross Origin WebSocket Attempt.  Origin: https://server1:5555, Host: server1

To avoid this, I added to the config the line
 c.NotebookApp.allow_origin = '*'
But it gets ignored.

This is my ngingx config:
`
    server {
        listen      5555 default ssl;
        server_name  https://server1.domain.net:5555;
        ssl_certificate     server.crt;
        ssl_certificate_key server.key;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        auth_gss on;
        auth_gss_realm domain.net;
        auth_gss_keytab /etc/krb5_server1.keytab;
        #auth_gss_service_name HTTP;

```
    #charset koi8-r;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
    root   /srv/www/htdocs/;
    index  index.html index.htm;
   # proxy_pass https://server1/sso/;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header REMOTE_USER $remote_user;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;

          # WebSocket support

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 86400;

    proxy_pass http://server1:8000/;
    }


    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /srv/www/htdocs/;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           /srv/www/htdocs/;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
```

`

and this is my  jupyterhub config:

c = get_config()

import os

keyfile = '/ssl/ssl.key'
certfile = '/ssl/ssl.crt'
if os.path.exists(keyfile) and os.path.exists(certfile):
    c.JupyterHub.ssl_key = keyfile
    c.JupyterHub.ssl_cert = certfile
    c.JupyterHub.port = 443

c.Spawner.env_keep.extend([name for name in os.environ.get('ENVPASSWHITELIST','').split(',')])

c.JupyterHub.authenticator_class = 'remote_user.remote_user_auth.RemoteUserAuthenticator'
c.Authenticator.admin_users = {'mwigger', 'jnie'}
c.NotebookApp.allow_origin = '*'
c.NotebookApp.trust_xheaders = True
c.JupyterHub.proxy_auth_token = '[...]'

any ideas how to solve?

**Comment by ptulpen** [comment]
are there any information missing or is my problem to strange?

**Comment by takluyver** [comment]
It doesn't sound too strange, but I don't know the answer. @rgbkrk and @minrk are more likely to be able to help.

**Comment by rgbkrk** [comment]
The notebook server itself has to have the configuration as well. However the global config for your user servers get set, you'll need that as well.

**Comment by firlevapz** [comment]
I had the same issue and solved it by setting _c.NotebookApp.allow_origin = '*'_  in the default jupyter_notebook_config.py instead of jupyterhub_config.py (i guess that's also what @rgbkrk meant)
Usually this file should be in ~/.jupyter, see http://jupyter-notebook.readthedocs.io/en/latest/public_server.html
You can also change any other config file for the notebook-server in your spawner.

**Comment by ivanov** [comment]
Issue was solved, closing 7 years later :trophy:
