### ISSUE TITLE
Why we don't have the document for --ip parameter of cmd jupyter

### ISSUE THREAD

**Issue by ybdesire** [jupyter/jupyter#162]
This is a very useful command below to force jupyter listen on all IP.

```
jupyter notebook --ip="*"
```

But the `--ip` parameter still not been described at the document of `jupyter` command below. 
* http://jupyter.readthedocs.io/en/latest/projects/jupyter-command.html

Since I think the `--ip` parameter for `jupyter` command is helpful, why we didn't add description to the documentation?

**Comment by takluyver** [comment]
That document is just for the top level `jupyter` command - `--ip` is an option for the `jupyter notebook` subcommand. In principle, all the options are documented here:
http://jupyter-notebook.readthedocs.io/en/latest/config.html

But that doesn't yet describe the short command line arguments.

**Comment by ybdesire** [comment]
Thanks @takluyver for the explanation.
