### ISSUE TITLE
Map needed on How Do I Decide Which Packages I Need

### ISSUE THREAD

**Issue by GadgetSteve** [jupyter/jupyter#164]
On: http://jupyter.readthedocs.io/en/latest/projects/content-projects.html [http://jupyter.readthedocs.io/en/latest/projects/content-projects.htm](url)

There is a lovely diagram for new users decide where they need to go next with what look like links in it - unfortunately when the user clicks on any of the "links" they simply open the diagram as an png image - this is counter intuitive and may put some off.

To resolve this the simplest solution is to add a "map" to the html giving appropriate links for the "links" and possible for the whole box for each outcome.

**Comment by GadgetSteve** [comment]
It looks like the best solution for this would be to replace the png image with an svn with clickable links and insert it on the page as an svn object. See https://github.com/sphinx-doc/sphinx/pull/2176/commits/691141d23fe22881d259dc31507c75250daa53c4 for possibly related.

**Comment by GadgetSteve** [comment]
Possibly the spinx.ext.grapviz extension might be the best way to go.

**Comment by GadgetSteve** [comment]
I have a set of changes which uses the graphviz: command to produce a less neat, _(I am not a graphviz expert by any means),_ version of the diagram produced by @willingc but as an SVG with the links working - not 100% sure that this is the best way to go so attaching the image to see if it gets any comments.

[graphviz-88cfa414d22dd3242c19a9cb35b8312723e8386c.zip](https://github.com/jupyter/jupyter/files/289069/graphviz-88cfa414d22dd3242c19a9cb35b8312723e8386c.zip)

**Comment by GadgetSteve** [comment]
graphviz version ready to commit but might need current links replacing with intersphinx references will - sorry not sure if intersphinx references will work in graphviz sections.

**Comment by willingc** [comment]
@GadgetSteve Thanks for raising this issue. It's something that's on our radar to improve. I'll take a look at the PR and share my thoughts with you afterward. Thanks for taking the extra time to submit a PR.

**Comment by willingc** [comment]
Thanks for the contribution @GadgetSteve!
