### ISSUE TITLE
[docs/theme] template is for template, not content,

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#168]
The _template shipped here have 2 huge drawbacks:
- [ ] They overwrite strictly identical template of the theme and change 1 word, which is configurable in `conf.py`. Fix It. Upstream if necessary, and potentially using [file wide metadata](http://www.sphinx-doc.org/en/stable/markup/misc.html#file-wide-metadata) to special case a file
- [ ] Them carry some actual content, as HTML, will be extremely hard to maintain, and cannot be crosslinked. Migrate that to RST.

**Comment by willingc** [comment]
@carreau I'm happy to pair with you on this since this is beyond my JS/frontend abilities. I'm not a front end developer so working on the theme was a collaboration between @jdfreder and I. To address this issue as well as the other theme issues, a front end dev is needed.

**Comment by Carreau** [comment]
Thanks @willingc , I"m mostly just opening these things to offload things from my mind.
@ellisonbg students might be able to help at some points.

**Comment by willingc** [comment]
@Carreau Thanks! I'm all for capturing and may be a good thing for the interns to sprint on too.

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
