### ISSUE TITLE
Feature request: Table of contents based on markdown headings

### ISSUE THREAD

**Issue by lvphj** [jupyter/jupyter#170]
Jupyter notebooks are a very useful way to organise data analyses. However, they are so easy to use that they can quickly become cumbersome to navigate. It would be very useful to have an automatically-generated table-of-contents at the start of the document that would show the structure of the notebook based on the levels of markdown headings. The headings should be hyper-linked so that clicking on them would take the user directly to the relevant cell. Alternatively, an outline view (similar to that found in Word, for example) would similarly enable the structure of the document to be seen at a glance.

**Comment by Carreau** [comment]
These are typically available as extensions:
like here: https://github.com/captainsafia/notebook-toc
or here: https://github.com/minrk/ipython_extensions/blob/master/nbextensions/toc.js
or here: https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/toc2

I'm sure there are others.
