### ISSUE TITLE
Feature request: Collapsing cells to a single line

### ISSUE THREAD

**Issue by lvphj** [jupyter/jupyter#171]
The recently introduced feature to be able to collapse output fields is very useful. However, it would also be very useful to be able to collapse cells, perhaps down to the first one or two lines. Perhaps this could be implemented in a similar way to navigating directories in an operating system (e.g. with a triangle to the left of the cell name that toggles displaying the cell contents).

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. I believe this has been available in JupyterLab now for some time.
Happy hacking! :bowtie:
