### ISSUE TITLE
Gitter Welcome message

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#175]
I just saw the following:

> You can now create a Welcome Message that will be displayed to anyone who stumbles upon your community room. Use it to inform about anything they should know before joining your room. For example, you could let them know about your community guidelines, the code of conduct, and describe the general purpose of the room. 
> 
> Check out the example Welcome Message from our gitterHQ/gitter room.

![unnamed](https://cloud.githubusercontent.com/assets/335567/16236956/1819f5ac-378f-11e6-83a0-5c334c27b6c4.png)

> You can edit the Welcome Message in the Room Settings.

(Received by mail, so no links) might it be useful to setup on a few rooms as we said we would get rid of gitter? and redirect people to jupyter/help ?

**Comment by Carreau** [comment]
ping @fperez

**Comment by fperez** [comment]
Let's wait to see what we decide...  For reference, the core python dev team seems to also be reaching communication overload and Guido [suggested following the 'repo issues as comm channel' approach](https://mail.python.org/pipermail/python-dev/2016-June/145324.html). We can obviously make our own decisions, but it's useful to see how they frame the problem.

Guido immediately said no to real-time options, but they plan on looking at the various alternatives.  We'll probably want to decide before they finish their process, but still, useful to see what a related community thinks of these questions.

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
