### ISSUE TITLE
Rollback or Push forward the Jupyter Theme.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#176]
The current there has several drawback [will edit to list later]
- The current theme is bad:
  - Cross linking is wrong. 
  - to use it each project need  overwrite 1/2 the templates, see #168 
  - navigation have a lot of issues on various screens size. 
  - miss the "edit on github" and many RTD features.
- Readthedoc have their own theme which works great but
  - cannot render widgets.

We should decide to either rollback, or push the theme forward. 

cc @fperez , @SylvainCorlay , @willingc

**Comment by willingc** [comment]
cc @ellisonbg 

I'm fine with rolling back the theme and letting front end devs take the lead on a new theme that supports interactivity for widgets and extensions.

**Comment by JamiesHQ** [comment]
From @SylvainCorlay : needs to work easily on Android

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
