### ISSUE TITLE
Add markdown style guide to contributor docs

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter#182]
As suggested by @blink1073 in https://github.com/jupyter/jupyterlab/pull/180#issuecomment-231060839:

Style guide for markdown could include:
- line length and text wrap
- reflow of paragraphs (when to do so)
- Headings
- alternating gender if people are used in examples

**Comment by rstein66** [comment]
Commit https://github.com/jupyterlab/jupyterlab/pull/180/commits/e5d6ebc6bc5bcf9a19212196b0e533dc06193ea0 closes #182

**Comment by takluyver** [comment]
@willingc do you want to close this? Or was the aim of opening it here to have something in the main Jupyter overview docs?

**Comment by willingc** [comment]
@takluyver I can't remember ;-) Closing.
