### ISSUE TITLE
302 redirect when attempting to access jupyter notebook

### ISSUE THREAD

**Issue by ryantuck** [jupyter/jupyter#185]
fresh EC2 instance spun up from the `kaggle-machine` AMI in AWS.

my `~/.jupyter/jupyter_notebook_config.py`:

```
c = get_config()
c.NotebookApp.ip = '*'
c.NotebookApp.port = 9999
c.NotebookApp.allow_origin = '*'
c.NotebookApp.open_browser = 'false'
```

fire it up with `jupyter notebook`

when i `curl localhost:9999` on that box, I get no response back. 

looking at the logs, after `curl`ing I see there was a `302` redirect:

```
[I 15:22:28.578 NotebookApp] 302 GET / (127.0.0.1) 0.62ms
```
- I think I've adjusted just about every one of those params in the config file to no avail
- When I attempt to access the ip:port in the browser, I see the same `302` redirect on the server
- I've attempted editing the `base_url` variable in the config file to no avail
- I can confirm that `jupyter notebook` does default to using `~/.jupyter/jupyter_notebook_config.py` as its config

Anyone else seen this issue? Know a fix? I can run `jupyter` locally no problem but I'm trying to set up a server to access it remotely.

**Comment by ryantuck** [comment]
just attempted a fresh startup of this AMI without affecting any configs and am experiencing the same issue. Not sure if it's the AMI or if it's some setting in `jupyter` that i need to change.

**Comment by minrk** [comment]
Sorry, I don't see what there is to fix. 302 on `/` is expected. There is no page to serve at `/`, so it redirects to `default_url`, which is `/tree/` by default.

**Comment by INT-ZC** [comment]
> Sorry, I don't see what there is to fix. 302 on / is expected. There is no page to serve at /, so it redirects to default_url, which is /tree/ by default.

[I [time] NotebookApp] 302 GET /tree? (::1) 1.00ms

**Comment by pankaj-kvhld** [comment]
Same problem with :(

**Comment by IdoPort1** [comment]
Having a similar trouble on my local windows machine.
Removed fire wall and used a fresh  config file and still having the issue.

**Comment by IdoPort1** [comment]
Found on a different thread that reverting to notebook 5.7.4 solves it, fixed for me

**Comment by sarwar187** [comment]
conda update --jupyter worked for me

**Comment by ojitha** [comment]
same problem with me

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. This is an old issue without much actionable information as it stands right now. Please re-open on https://github.com/jupyter/notebook if you run into this again.

Thanks everyone and happy hacking! :bowtie:
