### ISSUE TITLE
Migration/backporting Bot.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#186]
This is something we often talk about and which is becoming more and more pressing, would be more and more useful. 

We have a few script [edit to put link to scripts] that can be manually invoked to kinda-migrate issues, and/or backport pull-requests.

Would it be interesting to spare some cycle on having an actual Bot to whom the core team can send specific request for things to be done ? 

Like `@bot migrate to jupyter/nbconvert` , or `@bot backport to 4.2`
Or even something that would, when a PR is submitted assign the last core-dev  that touched the same file, and the  core-dev that has the most line in this file for review ? 

https://github.com/barosl/homu can be a base, we need to figure out how to host it though.

**Comment by minrk** [comment]
Script links:

- backporting: https://github.com/minrk/ghpro
- migrating issues: https://github.com/minrk/migrate-issues

The API requests aren't too complicated (backport more so than migrate), so hooking them up to a web service that produces PRs / Issues shouldn't be too tough, and I'm sure people other than me would be more likely to use them.

**Comment by go-bears** [comment]
I think github's hubot can be launched on heroku and there's an npm package for him talks to Travis CI? and it can be integrated with gitter and/or slack.

**Comment by takluyver** [comment]
@Carreau now has such a bot, `meeseeksdev`. We're using it on some (?) of our repos.
