### ISSUE TITLE
jupyter --version outputs to stderr

### ISSUE THREAD

**Issue by gibiansky** [jupyter/jupyter#19]
Why does `--version` write to stderr, rather than stdout? This is non-intuitive and not what `ipython` used to do! (This broke the IHaskell install :( )

**Comment by minrk** [comment]
This is not intentional, it's just argparse's default on Python 2 for some reason. It's on stdout on 3.4, which is why I didn't notice it. Should be fixed by jupyter/jupyter_core#45
