### ISSUE TITLE
Organisation to gather teaching material ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#191]
From the dev meeting, we should create an organisation. Which name ?

Propose a single name in a comment, use up/downvotes to vote.

**Comment by Carreau** [comment]
jupyter-teaching-materials

**Comment by Carreau** [comment]
jupyter-teachy-mcteachface

**Comment by minrk** [comment]
Is it only for tutorials and teaching, not talks/demos?

**Comment by Carreau** [comment]
> Is it only for tutorials and teaching, not talks/demos?

I'm fine with talks as well.

**Comment by Carreau** [comment]
jupyter-talks

**Comment by Carreau** [comment]
jupyter-talks-and-tutorials

**Comment by Lull3rSkat3r** [comment]
jupyter-learn

**Comment by fperez** [comment]
I like jupyter-learn... Curious if @willingc has any thoughts on this name, re. its impact on disseminating information and community building...

**Comment by jasongrout** [comment]
along the lines of jupyter-learn: jupyter-edu, jupyter-education

**Comment by willingc** [comment]
If we're gathering resources (including talks, tutorials, webinars, etc.) , I would be inclined to gather them in one place such as a Resource Library (https://puppet.com/resources).

While many of these resources may provide educational value, I would try to keep the name somewhat generic so that the resources contained within could be used in different user communities - education, corporate data, etc.

Whether the Resource Library is an organization or a repo or a markdown document that links to these resources (or all of the above) would depend on what we would like to maintain. Perhaps jupyter-library.

**Comment by parente** [comment]
Perfect timing: @lbustelo, @jtyberg and I would like to move the https://github.com/ibm-et/pydata2016 dashboard / widget tutorial materials under a `jupyter.*` org before the pydata carolinas conference.

**Comment by Carreau** [comment]
> While many of these resources may provide educational value, I would try to keep the name somewhat generic so that the resources contained within could be used in different user communities - education, corporate data, etc.

I tend to side with @willingc on this one, I would be +1 for a resources. I'll change my vote.

**Comment by Carreau** [comment]
jupyter-resources

**Comment by fperez** [comment]
I like `jupyter-resources` too.  I think it should be an org, to make it easy to make repos like this for various content (some will be narrow, even one talk, others can be big and evolving, like large tutorials).

And I do like the idea of coupling that to a nice, visible page on the site like @willingc suggests, that can serve as the "front end" for the public to find these most visible.  But we can go ahead with the "back end" content store that's just org+repos (hopefully each with at least a useful README), while the more polished public website summary gets built.

Let's see if anyone else objects to this plan in the next day or two, and if not we can proceed.

**Comment by willingc** [comment]
Folks, If you haven't yet seen the new [pyvideo.org](https://pyvideo.org] site, give it a look. Nice to see that it includes PyData and SciPy content. This is a resource that we should share with the community too.

**Comment by takluyver** [comment]
I'm glad to hear that pyvideo.org has been resurrected. :-)

**Comment by fperez** [comment]
[Done!](https://github.com/jupyter-resources). I've invited a few people, we can add more as needed to make sure there's content there...

**Comment by jasongrout** [comment]
Can you change the name of the org to "Jupyter Resources" instead of "Project Jupyter"? It's confusing right now.

**Comment by fperez** [comment]
Oops! Fixed, thx.

**Comment by parente** [comment]
@fperez I transferred the pydata carolinas dashboards / widgets talk material into the org, but now I don't seem to have any access to it. Can you grant me admin on it? (The repo name is too generic and needs to be fixed.)

https://github.com/jupyter-resources/pydata2016

**Comment by fperez** [comment]
Done!

**Comment by fperez** [comment]
How do you think we should set up team structure to make it easiest for everyone?  I just added you by hand to this one...

**Comment by parente** [comment]
@fperez Accepted, but still no admin access on the repo. For example, the settings tab doesn't appear. 😕

**Comment by fperez** [comment]
Weird! I see you with admin access:

![image](https://cloud.githubusercontent.com/assets/57394/17723906/9947c232-63f2-11e6-8a4f-cafff6dd4b9e.png)

**Comment by fperez** [comment]
Maybe reload?

**Comment by parente** [comment]
Was some kind of lazy change. Had to refresh a bunch of times and then voila.

**Comment by fperez** [comment]
ok, all good then. Will look a bit more for optimal team setup moving fwd. Anything else you need?

**Comment by parente** [comment]
No. Thank you for jumping on it!

**Comment by fperez** [comment]
No prob, glad to help!

**Comment by fperez** [comment]
Instead of making a bunch of admin teams, I just made the default member permissions to have full admin rights. For this org I don't think that's a problem, and it will simplify our admin load.  If anyone disagrees, let me know.

**Comment by parente** [comment]
Any preference on naming? I went with dashboards-pydata-carolinas-2016 for topical + venue but it's quite the mouthful.

**Comment by fperez** [comment]
I think that's fine... Long, yes, but it will make it easier to find them...

I tend to name all my talks directories like `YYMM-{location/venue}-{topical descriptor}`, which makes it easy to do lexicographic sorting and makes it consistent.  I don't know if it's worth enforcing something that rigid here...

**Comment by fperez** [comment]
While working, I keep single-word short symlinks for my active/recent ones to facilitate navigation, but I periodically prune the symlinks, leaving only the long-form names for all my stuff. A bit OCD, but works for me with over 15 years worth of talks :)

**Comment by willingc** [comment]
Would it be easier to make the repos:

- talks (typically 1 hour or less)
- tutorials (workshops and tutorials)
- papers (written by jupyter team or about jupyter)

Inside each repo could live a folder that is named as suggested by @fperez. The README.md in each repo could be a running markdown file of title and one line descriptions.

**Comment by parente** [comment]
@willingc the dashboards one I just transferred in is pretty darn complex with it's own setup scripts that know how to clone their own repo onto a VM in the cloud, clone other repos, etc. I think mixing all that in with other stuff would be asking for trouble.

**Comment by willingc** [comment]
Iterating on @parente's comment.

Perhaps have 3 main repos to start: 
- talks
- tutorials
- papers

Structured similar to the go talks repo https://github.com/golang/talks

Workshops, such as those mentioned by @parente, could have their own repo since that makes good sense, but we keep an index of all of these workshops/tutorials in the main tutorial repo.

So the org would have repos:

- talks
- tutorials
- papers
- peter's dashboard pydata workshop
- workshop 2
- workshop 3
- adding workshop and other repos as needed over time

**Comment by willingc** [comment]
I'm a bit concerned if we have a repo for each talk and workshop that the org will become unwieldy over time. I'm inclined to have a handful of collection repos and then let folks use their own good judgement on when a new repo is needed.

**Comment by lbustelo** [comment]
i think standalone projects for each talk/tutorial allows the most flexibility. Maybe a naming convention is what is necessary to help organize. 
Date-Venue-Topic-(talk | tutorial | paper | ...).

**Comment by fperez** [comment]
I can see it working well for talks to put them all in one repo, with one subdirectory per talk.  Talks are typically fairly self-contained, sometimes just one item or a main pdf/ppt/key  + a few supporting materials (say demo code, images, videos, etc).  And they are fairly regular and not meant to change much over time, so putting each new talk in as a single PR could work quite well.

But for tutorials and papers, I think that the flexibility of having a repo for each is worth the (real, I don't deny it) complexity cost.  Tutorials are often complex, multi-directory affairs, and now that we have tools like binder, it becomes realistic to offer a binder/docker/env to go along with the tutorial.  To do that, it's probably not going to work well to have multiple tutorials living together in one repo.

As for papers, they will likely evolve with their own authorship, commentary and even post-publication review process.  I think it's quite clean, conceptually, to have each matched by a repo, which is the "natural", atomic unit of organization on github.

So I'd propose to start with:

- One repo for all talks.  Each talk would be a subdir, named as I suggested above (`YYMM-{locator}-{descriptor}`), and as suggested by @willingc, the top-level README can be a simple index that can also link to videos if available.

- One repo each for new tutorials & papers.  Those I would call `tutorial-{descriptor}` or `paper-{descriptor}` to make it easier to find by name in the listing.  No dates as the same tutorial can potentially be reused many times, and the publication date of a paper won't be known at repo creation time.

How does this sound? @willingc, I know it's a bit different from your suggestion, so I'm happy to discuss further til we find a good solution...

**Comment by willingc** [comment]
Sounds good to me. This seems to capture everyone's input. We can always iterate over time. 

If a talk needs a repo of its own for whatever reason, folks should feel free to do so and simply link to the repo from the README in the talks repo.

**Comment by willingc** [comment]
## Summary of Issue Resolution

**New organization for Jupyter Learning Resources**
jupyter-resources [https://github.com/jupyter-resources]()
 
### Talks
- One repo for all talks: **talks** [https://github.com/jupyter-resources/talks]
- Each talk would be a subdirectory in **talks** repo, named as  `YYMM-{locator}-{descriptor}`
- Top-level README can be a simple index that can also link to videos if available.
- If necessary for a particular talk, feel free to create a repo of the format `talk-YYMM-{locator}-{descriptor}` and create a link to it in the `talks/README.md` file of the **talks** repo.

### Tutorials and papers
- One repo each for new tutorials & papers. 
- ` tutorial-{descriptor}` or` paper-{descriptor}` to make it easier to find by name in the listing. 
- No dates as the same tutorial can potentially be reused many times, and the publication date of a paper won't be known at repo creation time.

**Comment by fperez** [comment]
thanks @willingc for that summary, fully agreed!

One question we didn't sort out: should we suggest that all the repos in this org by default use the [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license? It seems to me like the closest to BSD/MIT in spirit but more focused on content.  Repos that have substantial amounts of actual code can also include the standard BSD license for that material, if it's really needed, but I don't imagine we'll be shipping whole libraries/applications here, so I think even for some amounts of code CC-BY would do.

Do we agree on that?

**Comment by jasongrout** [comment]
Sure, CC-BY sounds great. But we need to clarify what attribution means. Is it a link to the repo? Are we going to track multiple authors through document edits?

**Comment by fperez** [comment]
Creative Commons actually specifies in detail [what attribution means](https://wiki.creativecommons.org/wiki/License_Versions#Detailed_attribution_comparison_chart). That looks pretty detailed to me.  We'll provide a copyright/license notice, so that's all they would need to honor...

That seems sufficient to me, and we'd just be following exact CC practices without any customization.

**Comment by jasongrout** [comment]
> That seems sufficient to me, and we'd just be following exact CC practices without any customization.

Sounds good! That page you linked was interesting reading--thanks!

**Comment by JamiesHQ** [comment]
@willingc : thanks for looping me in!
