### ISSUE TITLE
Terminal display settings: line spacing too small

### ISSUE THREAD

**Issue by xtYao** [jupyter/jupyter#196]
Dear Jupyter team,

While I enjoy the convenience of directly talking to my shell by running a terminal within Jupyter, I found the default display is truncating each printed line from its bottom. For example, as shown below, parts of the letters 'j', 'p', 'y', and the underscores are not visible.

![image](https://cloud.githubusercontent.com/assets/7048349/18012470/95acb4d8-6b87-11e6-9964-44b3064638a5.png)

Do you have any options I can change the display settings? like expanding the line spacing?

Thanks,
Xiaotong

**Comment by hzclarksm** [comment]
For me the truncation happens at the top of the text

![Screenshot from 2022-09-21 14-02-44](https://user-images.githubusercontent.com/23175136/191577877-676ce1fc-3840-4f3b-8b31-6a18f8626c12.png)

**Comment by ivanov** [comment]
This was eventually dealt with in JupyterLab - see https://github.com/jupyterlab/jupyterlab/issues/5264
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
