### ISSUE TITLE
[idea] jupyter <subcommand> --docs

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#20]
Would open the web browser for the docs of the target subcommand, potentially the right version as it has access to the version number.

Thoughts ?

**Comment by minrk** [comment]
That's a pretty good idea. Want to add it to the base JupyterApp?

**Comment by Carreau** [comment]
Yeah probably. 
I think that `--bugs` could also work, as you can prefill github issues, so we could collect user info, and pre-fill with that. Getting late here, so might not do ti tonight. Should we mark that as newcomer friendly ?

**Comment by minrk** [comment]
Sure.

**Comment by damianavila** [comment]
> I think that --bugs could also work, as you can prefill github issues, so we could collect user info, and pre-fill with that. Getting late here, so might not do ti tonight. Should we mark that as newcomer friendly ?

I implemented something like that in Bokeh last year and people did not use it at all, so we removed it... just passing a previous experience :wink:

**Comment by willingc** [comment]
I've labeled this as an enhancement. I'm also going to close this based on @damianavila's feedback. Feel free to reopen when/if desired.
