### ISSUE TITLE
[Windows] "jupyter notebook" unlike "ipython notebook" launches in C:\Windows if working directory is a UNC path (e.g. on network share)

### ISSUE THREAD

**Issue by niklas88** [jupyter/jupyter#203]
Foreword:
-----------
I'm much more comfortable on Linux than on Windows so excuse if I'm not seeing something obvious here.  Other than that, I'm using the current stable version of jupyter with Python 3.5. I installed via pip instead of Anaconda, not sure if this makes a difference.

Summary:
----------
It looks like the "jupyter notebook" command unlike "ipython notebook" doesn't work with UNC paths. which means the newer command can't be used to open notebooks residing on a network share.

How to reproduces:
----------------------
First I think one has to do this in PowerShell since cmd.exe seems to not like UNC paths at all.  So after cd'ing to a network share one can launch a notebook that sees that directory as its root via "ipython notebook" and it works however it will rightfully complain that this command is deprecated. However, using "jupyter notebook" in the same directory results in it complaining that CMD.exe was launched with a UNC path.

My guess would be that the "jupyter" command uses a cmd.exe to launch the actual process while "ipython notebook" doesn't.

**Comment by takluyver** [comment]
That does sound plausible - with Jupyter, we changed how subcommands work so that `jupyter foo` [does execute](https://github.com/jupyter/jupyter_core/blob/c600d7e2d5240a02c3308d7cb4f2cfb0fa6c45c5/jupyter_core/command.py#L96) a separate `jupyter-foo` command. So as a workaround, you should be able to run `jupyter-notebook`, with a dash instead of a space.

**Comment by niklas88** [comment]
@takluyver thank you, I can confirm that this workaround does indeed work.

**Comment by minrk** [comment]
@niklas88 can you tell if jupyter/jupyter_core#88 fixes this for you?

**Comment by niklas88** [comment]
@minrk adding the changes in the diff manually solves the problem yes, also wow is it difficult to edit files as administrator on Windows

**Comment by takluyver** [comment]
Thanks for testing. I've merged Min's PR now.
