### ISSUE TITLE
problem  formatting in jupyter with julia 0.5

### ISSUE THREAD

**Issue by jmarcellopereira** [jupyter/jupyter#210]
I do not know why, but the formatting in jupyter with julia 0.5 is bad. when I use:
using SymPy
@vars x
x \* x

It appears `x ^ 2` instead of `x²`

**Comment by takluyver** [comment]
In Python, you have to call `sympy.init_printing()` inside the notebook to get the nice output. You probably need something similar in Julia.

**Comment by jmarcellopereira** [comment]
i did try, but  does not work :(

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
