### ISSUE TITLE
i met really strange problem “ Disallowing redirect outside JupyterHub: ''

### ISSUE THREAD

**Issue by yonghuming** [jupyter/jupyter#213]
```
I 2016-10-21 23:09:35.274 JupyterHub log:100] 302 GET /hub (@::ffff:101.226.125.118) 1.82ms
[W 2016-10-21 23:09:35.462 JupyterHub pages:32] Disallowing redirect outside JupyterHub: ''
[I 2016-10-21 23:09:35.467 JupyterHub log:100] 302 GET /hub/ (@::ffff:101.226.125.118) 2.11ms
[I 2016-10-21 23:09:35.658 JupyterHub log:100] 302 GET /login (@::ffff:101.226.125.118) 1.66ms
[I 2016-10-21 23:09:35.862 JupyterHub log:100] 200 GET /hub/login (@::ffff:117.185.27.146) 14.04ms
[W 2016-10-21 23:09:46.635 langxm kernelspec:142] Native kernel (python3) is not available
[I 2016-10-21 23:09:57.345 JupyterHub log:100] 200 GET /hub/home (langxm@::ffff:106.187.102.44) 9.48ms
[I 2016-10-21 23:10:22.212 JupyterHub log:100] 302 GET / (@::ffff:117.185.27.146) 1.04ms
[I 2016-10-21 23:10:22.385 JupyterHub log:100] 302 GET /hub (@::ffff:101.226.125.118) 1.96ms
**# [W 2016-10-21 23:10:22.566 JupyterHub pages:32] Disallowing redirect outside JupyterHub: ''**
[I 2016-10-21 23:10:22.571 JupyterHub log:100] 302 GET /hub/ (@::ffff:117.185.27.146) 1.42ms
[I 2016-10-21 23:10:22.747 JupyterHub log:100] 302 GET /login (@::ffff:117.185.27.146) 1.06ms
```

it's so strange this problem
i use china mobile wire network,but if i visit my server directly i got this error. and i can not login my server.even ther username and passwd were corect!
if i visit my server via vpn or ss proxy,i can login successfully

**Comment by yonghuming** [comment]
i just want to know what does this error mean.when i use china union work at office, i have not met this problem so strange

**Comment by minrk** [comment]
What version of JupyterHub? The disallowed redirect message looks to be displayed in error, because the target is empty, which means there is no redirect target. The only consequence of this is that you will be redirected to the default `/hub/home` URL instead of another location. It won't affect the ability to login. When you connect are you sure that you are connecting to the public proxied IP, and not bypassing the proxy and connecting directly to the Hub?

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Please report other issues with https://github.com/jupyterhub/jupyterhub there.

Thanks everyone and happy hacking! :bowtie:

**Comment by yonghuming** [comment]
您好，邮件已经收到
