### ISSUE TITLE
Incorrect indentation in Julia v0.5

### ISSUE THREAD

**Issue by juliohm** [jupyter/jupyter#214]
In Julia v0.5 we can write:

```julia
a = indmax(rand() for i=1:3)
```

that is, we can avoid allocating memory in an array as it used to be the case in Julia v0.4:

```julia
a = indmax([rand() for i=1:3])
```
On Jupyter, the new syntax causes incorrect indentation when the ENTER key is pressed:

```julia
a = indmax(rand() for i=1:3)
    # incorrect indentation
```

**Comment by takluyver** [comment]
I can reproduce this in the CodeMirror [Julia demo](http://codemirror.net/mode/julia/index.html). Please file an issue [on CodeMirror](https://github.com/codemirror/CodeMirror/issues), the editor component we use in the notebook.

**Comment by juliohm** [comment]
Thank you @takluyver , done: https://github.com/codemirror/CodeMirror/issues/4356
