### ISSUE TITLE
Segmentation fault (core dumped) while running jupyter notebook

### ISSUE THREAD

**Issue by nikhilweee** [jupyter/jupyter#215]
I'm on Ubuntu 16.04 with jupyter installed via anaconda2.
Everything was working fine until I force-closed a running notebook (hitting CTRL-C twice).
Since then, jupyter gives segfault for every command.
I've tried reinstalling jupyter as well as ipython but none of them seem to work.

Here is the syslog output:

```
Oct 29 14:51:40 spyder kernel: [ 5635.790435] jupyter-noteboo[9624]: segfault at 2260 ip 0000000000002260 sp 00007fffa2fecb18 error 14 in python2.7[400000+1000]
```

Any leads would be appreciated.

**Comment by minrk** [comment]
I don't understand any mechanism that could cause this, but perhaps reinstalling Python itself would do it?

**Comment by nikhilweee** [comment]
For now, I reinstalled anaconda, and that solved the problem. I still have the old environment, in case you may want do dig deeper into the issue.
