### ISSUE TITLE
Plan for improved accessibility for jupyterlab and project-wide docs

### ISSUE THREAD

**Issue by gnestor** [jupyter/jupyter#218]
Follow up from https://github.com/jupyter/notebook/issues/1801

We will most certainly discuss this at the Fall Meeting next week, but I want to create an issue to track our progress.

**Comment by willingc** [comment]
A list of resources from the WriteTheDocs newsletter https://docs.google.com/document/d/19crjGz7lryYlvaIEzK8KTX_oMLAxzxx1AwGsjlsymgs/edit#heading=h.c5b1b4c0b5i6

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. The document Carol linked from WriteTheDocs was deleted, and now there's a whole [Accessibility Working Group](https://github.com/jupyter/accessibility)

Thanks everyone and happy hacking! :bowtie:
