### ISSUE TITLE
Repo-map improvements

### ISSUE THREAD

**Issue by ian-r-rose** [jupyter/jupyter#219]
https://jupyter.readthedocs.io/en/latest/architecture/visual_overview.html
The map of repos is a useful overview of the project structure, but, as a relatively new jupyter team member, I still find it confusing in some ways. I think the following would be useful:
* Clickable links to either the docs or the github pages for the specific repos.
* Perhaps there could be a 1-2 sentence description of the subproject goals/responsibilities upon mouseover
* A description of the meaning of the arrows between subprojects (i.e., which direction does the dependency go?, what is the nature of the connection between `ipykernel` and `jupyter_client`?)
* A description of the color coding of the repos:  what do green and purple and yellow mean?

I am happy to take a crack at this, but if anybody has any other ideas...

**Comment by takluyver** [comment]
I went to add some more information, and... there already is more information there, but browsers don't display it. I was hoping that in 2017 we could display an SVG in the browser and it would handle *italic text*, but apparently not :angry: . I'll convert it to PNG for display.

**Comment by takluyver** [comment]
See #238
