### ISSUE TITLE
issue with `custom.js`, loading but not triggering as expected 

### ISSUE THREAD

**Issue by parmentelat** [jupyter/jupyter#221]
Hi; I run jupyter version 4.1.0 (on top of python-3.5) on a mac

I used to have a working `custom.js` a while back (mostly I use it to define my own keyboard shortcuts); it is now located in `~/.jupyter/custom/custom.js` and I can see it loading, but then something does not trigger as expected.

Based on [this post on SO](http://stackoverflow.com/questions/32170197/how-do-can-i-use-a-custom-js-file-under-jupyter-notebook) I came to the basics and right now my `custom.js` contains exactly this

```
console.log("loading custom.js")

define(['base/js/namespace', 'base/js/events'], function(IPython, events) {
    console.log("define'd deps loaded");
    events.on('notebook_loaded.Notebook', function() {
        console.log('define & notebook_loaded.Notebook');
    });
    events.on('app_initialized.NotebookApp', function() {
        console.log('define & app_initialized.NotebookApp');
    });
});
```

When loading a notebook, the JS console gives me this 

![loading-custom](https://cloud.githubusercontent.com/assets/4519227/20239386/29dc411e-a8ff-11e6-9432-64046e72e047.png)

So `custom.js` clearly was found and loaded, but none of the 2 expected messages starting in `define & ...` shows up. 

I could use some hints on how to tackle this issue further, I'm really missing the ability to use my shortcuts :)

**Comment by takluyver** [comment]
It might be loading after the events you're listening for have already fired. I'm not quite sure what to do about that, though.

**Comment by parmentelat** [comment]
Thanks for the feedback
Having run out of ideas, I just did a port upgrade and ended up with jupyter-4.2.0, and bingo, with that in place I can now enjoy my shortcuts again
So I take it it's best to just close this issue, as I would be unable to reproduce any of this anyways

And thanks much all for the great tool :)

**Comment by takluyver** [comment]
Thanks for following up, @parmentelat
