### ISSUE TITLE
No Conection to Kernel

### ISSUE THREAD

**Issue by Yeris** [jupyter/jupyter#222]
Hi!
Im trying to run Jupyter usying Anaconda (on Windows), but i can not connect to kernel, so no code running for me . It's the notorious "WebSocket ping timeout". I'm doing everything locally, tried 3 different borwsers (fire fox, chrome, explorer), and killed the antyvirus.  Nothing helps.
Here how it looks when i run notebook in debug: http://imgur.com/a/9zTvg
I tried using qtconsole, there my code works fine (so its not a problem with Python.. i think)

Thanks in advance guys.

**Comment by takluyver** [comment]
Which antivirus do you have, and are you certain you totally disabled it? We have had various problems with antivirus systems blocking websockets.

You might also try switching between `localhost` and `127.0.0.1` in the URL; it sometimes makes a difference.

**Comment by Yeris** [comment]
Yeah, i killed that little bastard from the task manager. I use ad-Aware.
Hmm, what is strange, i can not connect using 127.0.0.1, I can only connect through localhost:8888.

**Comment by takluyver** [comment]
I don't know how the websocket blocking (if there is any) works - it may change some setting on your computer which persists even if you kill it. Is there a shutdown/disable option inside ad-Aware?

I don't think we've had problems reported with ad-Aware before, but various AV systems have been a problem, and it's possible that we don't have many users with ad-aware.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
