### ISSUE TITLE
Collapse code block to just show output [feature request]

### ISSUE THREAD

**Issue by ieee8023** [jupyter/jupyter#223]
Can it be that I can collapse a block of code just like I can collapse the output boxes? 

I'd like to be able to keep all my code for a project in a single notebook so when I share it all the needed code is there. If I do this the file can become very long and hard to understand.

Thanks!

**Comment by mikkokotila** [comment]
Are you aware that you can do it with Javascript very simply:

http://stackoverflow.com/questions/27934885/how-to-hide-code-from-cells-in-ipython-notebook-visualized-with-nbviewer

**Comment by ieee8023** [comment]
Yes I saw that. I don't want to send people a notebook with javascript in it because I would be suspicious of receiving a notebook with javascript in it. If it is nonstandard I would rather not use it.

**Comment by takluyver** [comment]
There's an [extension for it](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/codefolding/readme.html), and discussion about including the functionality by default (jupyter/notebook#2235).

**Comment by stuaxo** [comment]
Is code folding the same thing ?   I can't see how you can hide the entire code of a cell with it ?

**Comment by nherbaut** [comment]
definitely not the same thing. Also looking for the feature

**Comment by colinator** [comment]
I concur. This feature would be great for collaboration - you could view notebooks in 'presentation' mode, and write for such.

**Comment by efiring** [comment]
I have just now encountered this feature in an R notebook rendered as html, and it works beautifully.  There is a button to the upper right of each cell that toggles between "hide" and "code".  There is a similar button at the top of the entire notebook that has menu options for hiding or revealing code throughout the notebook.  Well done--to be competitive, jupyter notebook badly needs this.

**Comment by karanalang** [comment]
is there a way to hide code in Scala Jupyter notebook ?

**Comment by brianmapes** [comment]
Another searcher is surprised this feature hasn't come yet. It seems right at the core of usability (distribution within the integrity of a single file, yet with readability for recipient as well as creator so the extension is not quite satisfying) -- the essence of the literate programming paradigm. Are security concerns holding it back or something?

**Comment by RBenRocks** [comment]
For anyone coming here looking for an answer, there are extensions to [hide all code input](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/hide_input_all/readme.html) or [hide code in a selected cell](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/hide_input/readme.html).

**Comment by gutow** [comment]
I believe this should be closed based on RBenRocks comment.

**Comment by choldgraf** [comment]
Also just a note that this is possible out-of-the-box with jupyterlab:

![2019-03-26_08-24-01](https://user-images.githubusercontent.com/1839645/55009955-9f733500-4fa0-11e9-9d8f-2b5bb2382986.gif)

**Comment by datdinhquoc** [comment]
This feature should be made. Sometimes I use Python to draw, instead of uploading an image and insert into a text block with markdown. For example:
![image](https://user-images.githubusercontent.com/40449395/66297145-4efa6e00-e919-11e9-8480-5102b1e27f8d.png)

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. 

Thanks everyone and happy hacking! :bowtie:
