### ISSUE TITLE
Issue: Infinite Loop in IPython Kernel

### ISSUE THREAD

**Issue by jolespin** [jupyter/jupyter#224]
When I accidentally run and infinite loop and it starts printing, it is impossible to shut down the kernel w/in the notebook.  Sometimes my entire browser freezes for all the Jupyter tabs.  Is there a way around this?  Often I can restart the kernel from the main Jupyter home but sometimes I can't.

**Comment by takluyver** [comment]
This is a known problem with sending a lot of output to the browser to show. We're looking into rate-limiting output to avoid it, but it's a tricky balance to strike.

**Comment by jolespin** [comment]
I can imagine it must be really tricky to deal with that!  Thanks for the response . Has anyone mentioned any hacks around it short of closing down the kernel from the terminal?

**Comment by takluyver** [comment]
There's an extension you can try here: http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/limit_output/readme.html . I don't know of anything better to do once it's already started causing a problem, though.

**Comment by takluyver** [comment]
There's an [extension for it](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/codefolding/readme.html), and discussion about including the functionality by default (jupyter/notebook#2235).

**Comment by takluyver** [comment]
Sorry, wrong issue.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
