### ISSUE TITLE
Problem in widget background_color

### ISSUE THREAD

**Issue by ema8490** [jupyter/jupyter#225]
Hello,
I noticed that there are some issues related to the widget background_color property. In particular, I have been working with Jupyter 4.2.1 and I am able to set the background color without any problem. On the other hand, after downloading the last version of Jupyter, running the same code has no impact on the background color, therefore I am not able to change it.

Here a Python3 code example:
from ipywidgets import widgets
from IPython import display

led = widgets.Button(margin = "5px 22px", width = "40px", disabled = True)
led.background_color = "#00FF00"
l = [led]
widgets.HBox(l)

On Jupyter 4.2.1 this code makes a green button appear, whereas, on the current version of Jupyter, the vert same code makes a blank button appear.

Thanks for your help!
Emanuele

**Comment by takluyver** [comment]
Pinging @SylvainCorlay, as I'm not sure if you follow this repo.

**Comment by SylvainCorlay** [comment]
> Pinging @SylvainCorlay, as I'm not sure if you follow this repo.

Thanks for the ping, I was not!

@ema8490 as of ipywidgets 5.0, the way to modify widget **layout** attributes is to modify the properties of the *layout* trait of a widget.

```python
led = Button()
led.layout.width = '40px'
led.layout.margin = '5px 22px'
```

a big advantage is that you can reuse the same layout for multiple widgets:

```python
l = Layout(width='40px', margin='5px 22px')
button1.layout = l
button2.layout = l
```

All the css attributes that relate to layout are exposed through the layout attribute.

In terms of colors, we have disabled the ability to modify top-level styling attributes. You can still choose among multiple pre-defined styles with the `button_style` attribute.

**Comment by ema8490** [comment]
@SylvainCorlay ok, thank you for your help! I wasn't aware of this change in top-level styling attributes.

Thanks again
Emanuele
