### ISSUE TITLE
Cannot see Cluster tab on Jupyter

### ISSUE THREAD

**Issue by arita37** [jupyter/jupyter#229]
After doing, in command Line :

```
ipcluster nbextension enable
ipcluster start -n  3
jupyter notebook
```

I see this on CLuster tab:
'''
Clusters tab is now provided by IPython parallel. See IPython parallel for installation details.
'''

it means not activated.
Config is 

```
     conda  {4.2.13 -> 4.2.13 (conda-forge)}
     conda-env  {2.6.0 -> 2.6.0 (conda-forge)}
     notebook  {4.2.1 -> 4.2.3 (conda-forge)}
    +ipyparallel-5.2.0 (conda-forge)
```

**Comment by minrk** [comment]
What do you see in `jupyter nbextension list`?

**Comment by arita37** [comment]
Hello,
I have this :

jupyter nbextension list
Known nbextensions:
  config dir: D:\_devs\Python01\Anaconda27\etc\jupyter\nbconfig
    notebook section
      nb_anacondacloud/main enabled
      - Validating: ok
      nb_conda/main enabled
      - Validating: ok
      nbpresent/js/nbpresent.min enabled
      - Validating: ok
    tree section
      nb_conda/tree enabled
      - Validating: ok
      ipyparallel/main disabled
  config dir: C:\ProgramData\jupyter\nbconfig
    tree section
      ipyparallel/main enabled
      - Validating: ok

C:\Users\asus1>^A

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Please open a new issue on https://github.com/ipython/ipyparallel if you have a  similar issue in the future.

Thanks everyone and happy hacking! :bowtie:
