### ISSUE TITLE
jupyter kernelspec install-self make no sens,

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#23]
It's an IPython thing !

**Comment by jorisvandenbossche** [comment]
I just encountered this, and it already says it is deprecated.

```
install-self
    [DEPRECATED] Install the IPython kernel spec directory for this Python.
```

But what is the easy alternative? (when using python, and without having to write the kernelspec yourself) 
It would be nice if this could be updated on SO then: http://jupyter.cs.brynmawr.edu/hub/dblank/public/Jupyter%20Help.ipynb#1.4.2-Enable-Python-3-kernel

**Comment by Carreau** [comment]
I did not get the deprecation, I might not have been up-to date.

The alternative is to use ipython kernel spec install-self.

Install self for **jupyter** make no sens. It does for IPython.

**Comment by jorisvandenbossche** [comment]
Ah, yes, `ipython` has this as well. However, it seems it is deprecated there as well (I suppose it is just an alias for jupyter):

```
C:\Users\vdbosscj>ipython kernelspec -h
Manage Jupyter kernel specifications.

Subcommands
-----------

Subcommands are launched as `jupyter kernelspec cmd [args]`. For information on
using subcommand 'cmd', do: `jupyter kernelspec cmd -h`.

install-self
    [DEPRECATED] Install the IPython kernel spec directory for this Python.
list
    List installed kernel specifications.
install
    Install a kernel specification directory.

To see all available configurables, use `--help-all`


C:\Users\vdbosscj>ipython --version
4.0.0
```

**Comment by jorisvandenbossche** [comment]
What I now did was:

```
from ipykernel import kernelspec
kernelspec.install(kernel_name='env_name')
```

**Comment by minrk** [comment]
We should probably add the entrypoint to `ipython kernel install-self`. It's only accessible now as `python -m ipykernel.kernelspec`

**Comment by rgbkrk** [comment]
Done in https://github.com/ipython/ipykernel/pull/43
