### ISSUE TITLE
Jupyter does not work when Python is not on PATH

### ISSUE THREAD

**Issue by stuxcrystal** [jupyter/jupyter#231]
On a clean python installation, installing Jupyter via

```
    py -3 -m pip install jupyter
    py -3 -m jupyter notebook
```

Will return an error that jupyter-notebook could not be found. Other commands will raise similar exceptions.

**Comment by takluyver** [comment]
I think that's what I'd expect. All of our applications can be launched from their module as well, i.e.

```
py -3 -m notebook
```
