### ISSUE TITLE
Cross origin scripting error when running Dockerspawner behind an nginx proxy

### ISSUE THREAD

**Issue by jdavidheiser** [jupyter/jupyter#232]
I am running Jupyerhub with DockerSpwaner behind an nginx proxy, and am able to load the hub, but when I try to run a notebook or create a file, I get cross origin scripting errors being thrown on the Docker container.  I've already seen the suggested fixes in #161 and #79, and added `c.NotebookApp.allow_origin = '*'` to my jupyterhub_config.py.  However, my understanding is that I ALSO need to add this to the local jupyterhub config for each of the servers that is spawned.  Since DockerSpawner kicks off [jupyterhub-singleuser](https://raw.githubusercontent.com/jupyterhub/jupyterhub/0.6.1/scripts/jupyterhub-singleuser), and it has the `disable-user-config` flag set to true, I am not sure how to set that option.  Could I do it using a command line switch to tini, something along the lines of what's shown in the [embedding a notebook docs](https://github.com/jupyter/notebook/blob/master/docs/source/public_server.rst#embedding-the-notebook-in-another-website)?  Where's the best place to put this - singleuser.sh?

**Comment by minrk** [comment]
@jdavidheiser you'll want to add that in `/etc/jupyter/jupyter_notebook_config.py` in the container, and make sure that the user that the notebook runs as does not have write permissions to this file or directory.

**Comment by jdavidheiser** [comment]
I used traitlets to add this option to the command line options in singleuser.sh, ie:

`exec jupyterhub-singleuser \
  --port=8888 \
  --ip=0.0.0.0 \
  --user=$JPY_USER \
  --cookie-name=$JPY_COOKIE_NAME \
  --base-url=$JPY_BASE_URL \
  --hub-prefix=$JPY_HUB_PREFIX \
  --hub-api-url=$JPY_HUB_API_URL \
  ${notebook_arg} \
  $@`

but will keep in mind creating a complete config file on the container (since the default image doesn't seem to have one) if we need to add more options in the future.
