### ISSUE TITLE
Latex doesn't work properly for mutiply

### ISSUE THREAD

**Issue by junjiecai** [jupyter/jupyter#234]
Hi 

When I use 

```
display(Latex('$M \times N$'))
```

in jupyter.

```\times``` is not rendered as multiply operator but the given result.

![selection_002](https://cloud.githubusercontent.com/assets/8223728/22461871/0b549ca2-e7e6-11e6-88cf-e9256ee69ba9.png)

The latex works in markdown cell in Jupyter.

It that an expected behavior or bug for Jupyter?

**Comment by dsblank** [comment]
You probably need to escape the backslash:

`display(Latex('$M \\times N$'))`

or use a "raw string".

**Comment by takluyver** [comment]
I think @dsblank is right. In a Python string, `\t` means the tab character.

**Comment by junjiecai** [comment]
Thank you @dsblank , it works
