### ISSUE TITLE
Formatted docs for magic functions

### ISSUE THREAD

**Issue by lmmx** [jupyter/jupyter#24]
I was looking for documentation for the 'magic' functions online, but the [top hit](https://ipython.org/ipython-doc/dev/interactive/tutorial.html) on Google is a tutorial which briefly mentions some of them, and the next hit (which admittedly I only found now embarrassingly) looks right but is missing some - `%autoindent`, `%cat` and `%clear` for example aren't there, so it's hard to tell how old a version they are from (which probably explains why I didn't find them).

I did the `%magic` command to get the plaintext docs, and searched this to try and find any formatted copy online but there wasn't, so I went ahead and turned them into markdown.

e.g. [searching the documentation for the `%cat` command](https://www.google.co.uk/search?q="Callable+object+storing+the+details+of+one+alias."+"Instances+are+registered+as+magic+functions+to+allow+use+of+aliases.") shows the developer docs, but finds nothing in a readable format, nor anything 'all in one place'.

I get the feeling I may have wasted my time turning the 'man pages' produced by the `%magic` command [into a markdown version](https://github.com/lmmx/devnotes/wiki/IPython-'magic'-function-documentation), as it looks like even though [that IPython list](https://ipython.org/ipython-doc/dev/interactive/magics.html) is outdated, it's processed the indenting in some way to properly format code blocks and regular `<pre>` elements within a `<dl>` definitions list — so I don't know if mine will actually be any use to you... :sweat_smile: was handy for me to read anyway

( Also this may relate to #20 for a subcommand to open formatted docs in a browser )

**Comment by lmmx** [comment]
D'oh! Sorry all, this is one for IPython/IPython

**Comment by Carreau** [comment]
No problem, we also work on issues a bit cross repository. 

Cross linking to the issues you opened on IPython/IPython:

https://github.com/ipython/ipython/issues/8762

Thanks
