### ISSUE TITLE
Broken jupyter notebook kernel integration with conda environments

### ISSUE THREAD

**Issue by dhimmel** [jupyter/jupyter#245]
Greetings. I'm currently in a Jupyter kernel hell. I can't figure how to fix it. And I'm not sure whether it's a Jupyter or conda issue, so thanks for the patience!

Here's my setup. I use conda to manage my python environments. I work on many different projects that use Jupyter notebooks, each project having its own environment (specified in `environment.yml` files).

I recently reinstalled conda to update my root environment to Python 3.6 and conda 4.3.13. As part of this reinstallation, I tried to remove files that I thought would get freshly regenerated including jupyter configuration files (IIRC).

This reinstallation of conda triggered the issue:

+ when I run `jupyter notebook` with the conda environment activated, the specific conda environment is not available in the spawned notebook browser.
+ If I run `python -m ipykernel.kernelspec` (I think) then I the activated conda environment becomes the default `Python 3` kernel for all my notebook servers.
+ Creating new conda environments with `jupyter` installed does not add them to the list of kernels in jupyter.

Before I reinstalled conda (and deleted jupyter config directories since I wanted to freshly reinstall everything related to python):

+ if I launched a notebook from an activated conda environment, the default `Python 3` kernel would correspond to that notebook
+ if I created a new conda environment, the kernel would show up as a choice in all jupyter sessions regardless of which environment `jupyter notebook` was running from
+ I never had to mess around with configuration files.

So I think I've broken something and I want the old (or any environment aware) behavior back. Tagging @minrk @jakevdp @kalefranz @asmeurer in case you or someone you mention can help. Will really appreciate any guidance!

**Comment by pilotneko** [comment]
For what it's worth, I am experiencing the similar issues. I am on Windows 10, and I completely removed Anaconda using the recommended steps (anaconda-clean, then uninstall from add/remove programs). I installed the Python 3.6 version of Anaconda, and now my Jupyter Notebook is completely borked. I can launch the server, but I can't access any of my conda environments (old or new). Only one kernel is listed: "Python 3." If I install Jupyter from within the environment and launch the notebook server while the environment is activated, sys.path still refers to the base installation path. Is something broken with respect to 3.6?

**Comment by takluyver** [comment]
I think Continuum stopped shipping their environments-as-kernels plugin by default - you can probably still install it, or you can [set up kernels for environments manually](http://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments). We're thinking about better ways to expose environments to Jupyter.

**Comment by pilotneko** [comment]
Thanks for the quick reply, this restored my workflow entirely. I think you are right about Continuum. I guess it serves me right for relying on pre-built distros, heh.

**Comment by dhimmel** [comment]
> I think Continuum stopped shipping their environments-as-kernels plugin by default - you can probably still install it

@takluyver, thanks for that info! It was enough for me to track down `nb_conda_kernels` ([anaconda cloud](https://anaconda.org/anaconda/nb_conda_kernels), [repo](https://github.com/Anaconda-Platform/nb_conda_kernels)). Once I'm back at the affected machine, I'll let you know if this fixes my issues.

[`nb_conda`](https://github.com/Anaconda-Platform/nb_conda) also looks interesting (allows you to manage conda environments in a Jupyter browser tab).

In worst case, I should be able to use the single kernel installation commands you [link to](http://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments):

```sh
source activate myenv
python -m ipykernel install --user --name myenv --display-name "Python (myenv)"
source activate other-env
python -m ipykernel install --user --name other-env --display-name "Python (other-env)"
```

But I'm not a huge fan of this solution as it's a manual step. Furthermore, when we have several people collaborating on a repo, we want them to all have the same kernel names for conda environments.

**Comment by dhimmel** [comment]
`conda install nb_conda_kernels` failed with:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda_kernels -> _nb_ext_conf -> nb_anacondacloud -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
```

So I installed `nb_conda_kernels` from conda-forge using:

```sh
conda install --channel=conda-forge nb_conda_kernels
```

Now I can choose from my conda environments in the Jupyter kernel menu. Phew!

Note that the `nb_conda_kernels` [README](https://github.com/Anaconda-Platform/nb_conda_kernels/blob/fe861722902df9c97f47bbf6e16c8c634d17144f/README.md) states:

> To use a conda environment as a kernel, don't forget to install `ipykernel` in this environment or it won't show up in the kernel list.

**Comment by dhimmel** [comment]
@takluyver or other repo members: close this issue at will. I may still report some additional findings here...

**Comment by takluyver** [comment]
Thanks

**Comment by xiaotangfeidao** [comment]
I had similar issue, this was really helpful. Thanks

**Comment by tsu-nera** [comment]
Thank you. I had same problem.

**Comment by bede** [comment]
Such a useful thread. IMO it is more than a little counterintuitive that notebooks do not use the active conda env by default.

**Comment by JyiHUO** [comment]
Thank you, this is very helpful for me. I am sucking in this problem about two day

**Comment by NumesSanguis** [comment]
I did the following:

    python -m ipykernel install --user --name StoAU2 --display-name "Python (StoAU2)"
    /home/user/anaconda3/envs/StoAU2/bin/python: No module named ipykernel
    [Errno 13] Permission denied: '/usr/local/share/jupyter'`

So then I tried:

    source deactivate
    python -m ipykernel install --user --name StoAU2 --display-name "Python (StoAU2)"
    Installed kernelspec StoAU2 in /home/user/.local/share/jupyter/kernels/stoau2
    python -m ipykernel install --user --name StoAU --display-name "Python 3 (StoAU)"
    Changed Kernel -> Python (StoAU2).

Then in a Jupyter notebook:

    import sys
    print(sys.executable)
    from jupyter_core.paths import jupyter_data_dir
    print(jupyter_data_dir())`
    
    /home/user/anaconda3/bin/python
    /home/user/.local/share/jupyter

Still not referring to the right kernel... This is quite an annoying change that terminal kernel and Notebook terminal are not the same.

This is what I tried (based on: https://github.com/Anaconda-Platform/nb_conda_kernels/blob/fe861722902df9c97f47bbf6e16c8c634d17144f/README.md):

    conda install -c conda-forge nb_conda_kernels
    conda create -n test
    package plan Proceed ([y]/n)? y
    conda install -n nb_conda_kernels --file requirements.txt -c r
   
But I got an error that I don't have the `requirement.txt` (sorry lost actual error). So I reinstalled everything and did the following (which finally worked):

    conda create --name StoAU
    source activate StoAU
    conda install ipykernel
    python -m ipykernel install --user --name StoAU --display-name "Python 3 (StoAU)"

I might be a beginner, but I don't understand what the purpose is of creating an environment and installing all packages there, if in the end the notebook doesn't use this kernel with what you've just installed.

**Comment by barnabytprowe** [comment]
Hi all, I followed the steps above on Windows 10 but still no joy... Anyone have luck in Windows?

**Comment by Kirktj** [comment]
Hi @barnabytprowe, I'm in the same position as you.  I'll let you know if I find anything that works.

**Comment by barnabytprowe** [comment]
Thanks @Kirktj - my colleague was in the same boat as me also but finally got everything working by installing the Python 3 version of Anaconda and making a v3.5 environment as per https://docs.continuum.io/anaconda/faq#how-do-i-get-anaconda-with-python-3-5.  Previously we had made the tensorflow python 3.5 environment from our Python 2.7 root install of conda.

Seems that this doesn't work nicely with Jupyter.  Were you in the same situation, trying to make tensorflow + Jupyter work from a Python 2.7 root install of Anaconda?

**Comment by anshbansal** [comment]
>> dhimmel commented on Mar 16

That worked for me on Windows 10 machine

**Comment by anshbansal** [comment]
I changed my .condarc from

```
channels:
  - defaults
ssl_verify: true
```

to

```
channels:
  - defaults
  - conda-forge
create_default_packages:
  - pip
  - ipykernel
  - nb_conda_kernels
ssl_verify: true
```

and now whenever I am creating a new virtualenv it gets automatically added to the list of environments.  I don't even have to run the commands anymore.

**Comment by thvasilo** [comment]
For future Googlers the simplest solution seems to be to install the `nb_conda` package: https://stackoverflow.com/a/38880722/209882

**Comment by jbrant** [comment]
No luck in Windows 7 - nb_conda or otherwise.

**Comment by KODeKarnage** [comment]
Installing nb_conda_kernels in the activated environment works for me with jupyter lab on Windows10. 

It comes with a tonne of dependencies though, so may not be worth it.

**Comment by rakeshch** [comment]
very helpful post

**Comment by VFiloso** [comment]
The problem repeates itself in 2019 with a fresh installation of **Anaconda 3** on a Mac with Mojave. The kernel does not get exist and the **jupyter notebook** cannot get access to Python.

```
[W 16:56:44.626 NotebookApp] KernelRestarter: restart failed
[W 16:56:44.627 NotebookApp] Kernel b656dc1a-b221-4d35-b473-dfbcf1d593a3 died, removing from map.
[W 16:57:29.624 NotebookApp] Timeout waiting for kernel_info reply from b656dc1a-b221-4d35-b473-dfbcf1d593a3
[E 16:57:29.627 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: b656dc1a-b221-4d35-b473-dfbcf1d593a3)
```

**Comment by dev-mtshikomba** [comment]
Refer to this package: [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels)

It worked for me.

**Comment by DJD-Code-Studio** [comment]
I couldn't run **jupyter kernelspec list**
It failed with the error --

> Traceback (most recent call last):
  File "C:\DEB_pythons\anaconda3\Scripts\jupyter-kernelspec-script.py", line 5, in <module>
    fromTraceback (most recent call last):
  File "C:\DEB_pythons\anaconda3\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\DEB_pythons\anaconda3\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\DEB_pythons\anaconda3\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\DEB_pythons\anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\DEB_pythons\anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\DEB_pythons\anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\DEB_pythons\anaconda3\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\DEB_pythons\anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\DEB_pythons\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\DEB_pythons\anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\DEB_pythons\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\DEB_pythons\anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\DEB_pythons\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: The specified module could not be found.

Which led me this ---

> (at a python prompt)
import KernelSpecApp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'KernelSpecApp'

Then similar result followed in case of -- 

> (at a python prompt)
import ipykernel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ipykernel'

I checked my Anaconda3 installation which was done via **silent mode** - the module ipykernel was definitely there.
But in spite of that python was failing to locate them which indicates in all probability a 'path not found' kind of issue.

That reminded me that I had opted for not setting the path during the installation by 
> using the parameter AddToPath=0 during the silent installation.

Hence the solution was to add the 3 vital Anaconda3 paths to the system level **"path"** variable.
First I made a new environment variable called -
> ANACONDA_PATHS and added the 3 following paths there-
C:\DEB_pythons\anaconda3\
C:\DEB_pythons\anaconda3\Scripts\
C:\DEB_pythons\anaconda3\Library\bin\

Btw, the first is the Anaconda3 root location in my set up.
**And voila...**
I was able to run --
> python -m ipykernel 

with no errors.
This also solved my initial problem ...

>jupyter kernelspec list
Available kernels:
  python3         C:\DEB_pythons\anaconda3\share\jupyter\kernels\python3
  anaconda3       C:\ProgramData\jupyter\kernels\anaconda3
  py390_ds_env    C:\ProgramData\jupyter\kernels\py390_ds_env
C:

**Comment by SouravPal1995** [comment]
I was facing an issue with this method. If i freshly create a conda environment and then create a kernel with it, I am being able to access those kernels from the base environment, however, if I update the conda environment, then jupyter from the base environment is not being able to connect with this kernel.
