### ISSUE TITLE
import numpy failed

### ISSUE THREAD

**Issue by leafjungle** [jupyter/jupyter#247]
Env:   Linux (Red Hat 4.4)
Desc: In my host machine, "import numpy", it works OK.
(the python environment is the same as the first line in "jupyter" script)

But in the jupyter webpage, import numpy error, the error info is as following:
---> 29 from numpy.linalg import lapack_lite, _umath_linalg
     30 from numpy.matrixlib.defmatrix import matrix_power
     31 from numpy.compat import asbytes

ImportError: /lib64/libgcc_s.so.1: version `GCC_4.0.0' not found (required by /home/myname/env/lib/liblapack.so)

I am puzzled about the python environment of the jupyter webpage.
(notebook/js/main.min.js  execute_cells function)

**Comment by takluyver** [comment]
That sort of error usually means there's some difference in the environment variables it sees.

Isn't Red Hat 4.4 super old? Wikipedia says that the entire RH 4 series is out of support at the end of this month, and the series got up to 4.9.

**Comment by leafjungle** [comment]
@takluyver .    I think the use who execute the python programs in jupyter is the same as the login user.
Thus they should source the same profile files: .bash_profile and .bashrc。 so that they should share the same environment variables.

**Comment by takluyver** [comment]
Right, but those aren't the only things that can set environment variables.

**Comment by leafjungle** [comment]
@takluyver , Omm, you are right.  I print the PATH variable in jupyter webpage (calll PATH.1), and compare it with PATH in login user(call PATH.2). I find that jupyter did add some paths before and after PATH.2. namely PATH.1 = XXX + PATH.2 + YYY

**Comment by leafjungle** [comment]
And in jupyter, I run "python test.py" through subprocess.popen,  and in test.py, there is "import numpy".   Amazingly the jupyter works.

**Comment by takluyver** [comment]
It may be using a different version of Python to the one you expect? Check `sys.executable`. Sorry, I don't have much insight on how to debug this.

**Comment by jiangqideng** [comment]
@leafjungle same problem with you. Do you find some solutions?

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
