### ISSUE TITLE
java gateway process exited before sending the driver its port number

### ISSUE THREAD

**Issue by leafjungle** [jupyter/jupyter#248]
import pyspark ---> works fine.
sc = pyspark.SparkContext() --> Error, info: "java gateway process exited before sending the driver its port number"

"""
the python context
![image](https://cloud.githubusercontent.com/assets/6143261/24248023/b78e4f8c-1008-11e7-8843-4f119cfb9278.png)

"""

After googling, I set the environment:
export PYSPARK_SUBMIT_ARGS="--master local[2] pyspark-shell"
or even:
sc = pyspark.SparkContext("local")

but the problem remains.

**Comment by leafjungle** [comment]
After a lot of Googling, finally I found the solution:
JAVA_HOME is not set !!

**Comment by VeLKerr** [comment]
As for me, setting `JAVA_HOME` didn't help.

**Comment by avocado2016** [comment]
Same for me

~/spark-2.1.1-bin-hadoop2.7/python/pyspark/java_gateway.py in launch_gateway(conf)
     93                 callback_socket.close()
     94         if gateway_port is None:
---> 95             raise Exception("Java gateway process exited before sending the driver its port number")
     96 
     97         # In Windows, ensure the Java child processes do not linger after Python has exited.

Exception: Java gateway process exited before sending the driver its port number

**Comment by hero0926** [comment]
Same error happens. delete PYSPARK_SUBMIT_ARGS dosen't get me through this problem. also I set my JAVA_HOME and SPARK_HOME.

**Comment by wplatter** [comment]
following @leafjungle's advice, setting JAVA_HOME worked for me.

I'm on Mac with a `brew` installed OpenJDK setup,
```
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
```

Credit => https://stackoverflow.com/a/6588410/665578

**Comment by SujanMukherjee** [comment]
I figured out the problem in Windows system. The installation directory for Java must not have blanks in the path such as in "C:\Program Files". I re-installed Java in "C\Java". I set JAVA_HOME to C:\Java and the problem went away.

**Comment by hykavitha** [comment]
setting JAVA_HOME dint help 
os.environ['JAVA_HOME'] = ' /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home'
also I set by exporting path 
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
----> 4 sc = SparkContext(appName="PythonSparkStreamingKafka_RM_01")
Exception: Java gateway process exited before sending the driver its port number
error is
  /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java: No such file or directory

but actually when I run 
 $ /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java
I get proper java option 
$ /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:

**Comment by rajesh-srivastava** [comment]
I got this error after upgrading to JDK 10. Changing JAVA_HOME to point to JDK 8 solved the issue. Spark version - 2.3.1

**Comment by danielemarmiroli** [comment]
in my case the error originated from the missing line

`127.0.0.1    localhost.localdomain`

in /etc/hosts . I traced it back trying to execute spark-shell from SPARK_HOME and finding this error:

`UnknownHostException: name or service not known`

which in turn directed me to this post:

https://stackoverflow.com/questions/33028842/unknownhostexception-name-or-service-not-known

**Comment by gulshan-gaurav** [comment]
I tried all the above options. nothing helped.
OS: Mac OS
spark:2.3.1
java version 1.8.0_181

@hykavitha  how did you fix the issue?

**Comment by hykavitha** [comment]
Hi Gushan,

You need to print your java home.

**Comment by gulshan-gaurav** [comment]
I tried setting JAVA_HOME but it did not solve the issue.
Finally I had to do a clean Install of everything, now its working fine.
I am still clueless as to what exactly was the issue.

**Comment by ecampana** [comment]
I did not have to unset my `PYSPARK_SUBMIT_ARGS` shell variable. Setting my `JAVA_HOME` shell variable did resolve the issue for me though. Strange, everything seemed to be working the previous day but then today the problem appeared. Running my jupyter notebooks from a server at work. I used the following shell command to find path needed for `JAVA_HOME`.

```
which java
```

**Comment by ylashin** [comment]
On Windows, I had the problem due to having JRE not JDK. Once I removed JRE and insalled JDK in `C:\java\jdk1.8.0_201` just in case spaces in program files make things crash, I was able to run pyspark in Jupyter notebooks. JDK installation includes both JDK and JRE but JAVA_HOME should point to JDK folder, in my case it was `C:\java\jdk1.8.0_201`

**Comment by shihs** [comment]
I use Mac OS. I fixed the problem!

I have **jdk-11.jdk** in **/Library/Java/JavaVirtualMachines**, by @rajesh-srivastava said, JDK8 worked fine. So I [downloaded JDK8](https://stackoverflow.com/questions/24342886/how-to-install-java-8-on-mac) (I followed the link).
Which is:
```
brew tap caskroom/versions
brew cask install java8
```

After this, as @leafjungle said, I added
```
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
```
and (I found this somewhere, can't remember now...) 
```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home
```
to **~/.bash_profile** file.  (you sholud check your jdk1.8 file name)

It works now!
Hope this help :)

**Comment by aashana94** [comment]
@shihs 
How did you add to ~/.bash_profile?

**Comment by ecampana** [comment]
@shihs they explicitly added the export JAVA_HOME line above to their ~/.bash_profile text file.

**Comment by shihs** [comment]
@aashana94 
find the file .bash_profile in ~/ .
It's a hidden file, use "Shift + Command +  . " the hidden files will show.

**Comment by shihs** [comment]
> @shihs they explicitly added the export JAVA_HOME line above to their ~/.bash_profile text file.

It didn't have, I added it manually.

**Comment by shihs** [comment]
you can use `echo $JAVA_PATH` in terminal to check if the path is added or not

**Comment by maximillianus** [comment]
> following @leafjungle's advice, setting JAVA_HOME worked for me.
> 
> I'm on Mac with a `brew` installed OpenJDK setup,
> 
> ```
> export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
> ```
> 
> Credit => https://stackoverflow.com/a/6588410/665578

I just want to add that I set `JAVA_HOME=/usr/bin/java` and it doesn't work. Setting `JAVA_HOME `to this actually works. Thanks!

I did not setup anything else including `SPARK_HOME` or `PYSPARK_SUBMIT_ARGS`.

My setup:
```
- macOS Sierra 10.12
- apache-spark 2.4.3 (installed through homebrew)
- python3
- java8 installed through homebrew
```

**Comment by guido611** [comment]
I was running in the same error. The spaces in the `JAVA_HOME` and the `SPARK_HOME` broke my neck.
Following the advice on this [page](https://changhsinlee.com/install-pyspark-windows-jupyter/), I have solved it.

Just replace `Program Files` with `Progra~1` in the environment variables. If JDK is installed under `\Program Files (x86)`, then replace the `Progra~1` part by `Progra~2` instead.

**Comment by Mona-Arami** [comment]
After spending hours and hours trying many different solutions, I can confirm that Java 13 SDK causes this error. On Mac, please navigate to /Library/Java/JavaVirtualMachines then run this command to uninstall Java JDK 13 completely:

sudo rm -rf jdk-13.jdk/

After that, please download JDK 8 then the problem will be solved.follow this link.
https://www.cs.dartmouth.edu/~scot/cs10/mac_install/mac_install.html

**Comment by burgerbaba** [comment]
Step by step installation for windows:
1) Download Java jdk and install. 
2) Copy the folder folder path where your Java is installed.
3) In your python environment, (Spyder in my case) add this (and replace the copied Java folder path within the quotations in the first line only)
```
os.environ["JAVA_HOME"] = "C:/Program Files/Java/jdk1.8.0_251"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]
```
4) Then you should be able to run spark = sparknlp.start()   

Hope this helps.

**Comment by MehvashKhanGitHub** [comment]
I have Java 8 and openJDK  spark version 3.0.0 mongodb version 4.2 
`import findspark
import os
os.environ["SPARK_HOME"]="C:\Spark\spark-3.0.0-bin-hadoop2.7"
os.environ["JAVA_HOME"] = "C:\Program Files\Java\java-1.8.0-openjdk"
findspark.init()
from pyspark.sql import SparkSession
from pyspark import SparkConf, SparkContext

conf = SparkConf().setAppName("mongo-connect")\
                  .setMaster("spark://192.168.1.102:7077")

spark = SparkSession \
        .builder \
        .config(conf=conf) \
        .config("spark.mongodb.input.uri", "mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false") \
        .config("spark.mongodb.input.database", "test") \
        .config("spark.mongodb.output.uri", "mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false") \
        .config("spark.mongodb.output.database", "test") \
        .config("spark.jars.packages", "org.mongodb.spark:mongo-spark-connector_2.12:3.0.0") \
        .getOrCreate()
`
![image](https://user-images.githubusercontent.com/45491293/91628946-6be0d980-e9e2-11ea-9981-5103ac306b97.png)

**Comment by rishi-wqd190004** [comment]
On fedora33 i faced the same issue when i did a normal update. Hence the java folder name got changed, so added the same folder name (_presently located in /usr/lib/jvm/java_folder_name_) in the .bashrc file and it resulted in everything working fine. 
Hope this helps.

**Comment by digital-spearman** [comment]
I'm facing similar error message, I'm using Jupyter notebook to learn pyspark in a windows machine.
Glad if i can get some pointers to resolve the issue. TIA

**Comment by noncreature0714** [comment]
(I'm on macOS.) Even though my JAVA_HOME was set and work for _**most**_ things, I still had this issue. 

The fix was to set it in my `.zshrc` (or wherever it's set) with 

`export JAVA_HOME=$(/usr/libexec/java_home)`

and not simply a raw path.

**Comment by hosein97** [comment]
I had the same error. However, Pyspark shell was running with no problem but, switching on jupyter notebook was giving the error. I found that the python version of my notebook(3.7) was different from my local one (3.8). I fixed this and the error was gone.

**Comment by BitwiseMayur** [comment]
On windows, the **JAVA_HOME** variable was already set, but it was set in the **system variables** and was not available in the **user variables**. I set it in the user variables and it started working for me.
