### ISSUE TITLE
[Idea] Add a glossary of Jupyter projects to docs

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter#25]
I was editing the docs to think about how to add a section on migrating from 3.x to 4.x. As I was reading the docs' landing page, there are a lot of projects now where there were far fewer before. 

I think it would be helpful to new users to have an alphabetical glossary of all Jupyter projects (or related projects).

**Comment by rgbkrk** [comment]
:+1: that's a fundamentally good thing as we expand (and maybe contract). What a Universe.

**Comment by willingc** [comment]
Closing issue since #26 merged.
