### ISSUE TITLE
Text files (*.log) are displayed as ASCII when they are UTF-8

### ISSUE THREAD

**Issue by bertjwregeer** [jupyter/jupyter#251]
I have some log files that are being generated and named `name.log`, when users click on them in their notebook it displays them with invalid characters because it gets opened as an ASCII file rather than a UTF-8 file.

Is there a setting that I can change to force it to open all files with UTF-8 encoding? The log output is from another service and it is using fancy UTF-8 quotes.

**Comment by takluyver** [comment]
Closing this to focus discussion on jupyter/notebook#2397
