### ISSUE TITLE
After making my notebook importable it still gives import error, why?

### ISSUE THREAD

**Issue by RizwanAli1** [jupyter/jupyter#254]
To make my notebook importable I tried this tutorial [http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Importing%20Notebooks.html](url). As soon as I try to import the module which I named iPyLoader in another notebook I get import error, specifically:

ImportError                               Traceback (most recent call last)
<ipython-input-20-d8b28a2bcacd> in <module>()
----> 1 import iPyLoader

ImportError: No module named iPyLoader
When I try to import iPyLoader from the same directory I get the above error but when I try to import from another directory I get the following ImportError:
ImportError: cannot import name iPyLoader

If I run ls Notebooks I get 
__init__.py  iPyLoader.ipynb

Which clearly shows that the module is present there.
Note: I have tried doing import Notebooks.iPyLoader but I still get the same error. 
When I do import iPyLoader in the iPyLoader notebook after registering it it does get imported but when I try to import iPyLoader in another module I get the Import Error. What am I doing wrong?
ipython --version 
5.3.0 
jupyter --version 
4.3.0 
jupyter notebook --version 
5.0.0

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks and happy hacking! :bowtie:
