### ISSUE TITLE
how to create new kernel

### ISSUE THREAD

**Issue by vhp1360** [jupyter/jupyter#255]
Hello experts,
I'm wondering if anyone explains or provide me to how to create a new kernel?
let me explain my issue:
I have spark on my server in _/usr/local/spark_, I could use the built-in SparkR package in spark package in R language as making link of that to R library like:
`ln -s /usr/local/spark/R/SparkR/ /usr/local/R/library`

as you know, to create pyhton2 kernel for jupyterhub we only need below code in `/usr/local/share/jupyter/kernels/python2/kernel.json` file:
```
{
 "display_name": "Python 2",
 "language": "python",
 "argv": [
  "/usr/bin/python2",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ]
}
```
now, I need to know how can I create scala and spark kernel for jupyter like above.

many thanks.

**Comment by takluyver** [comment]
The `.../kernel.json` file tells Jupyter how to launch the kernel; the main thing you need is the kernel implementation. [Here's a list of kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels). IIRC there are several for Scala & Spark. @rgbkrk is interested in that space and may be able to recommend one.

**Comment by vhp1360** [comment]
thanks @takluyver for the reply.
I knew [Jupyter Kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) but I'm going to know 
> how can I tell Jupyter to launch the kernel
as I mentioned, I can launch SparkR in R by linking, I'm interested to know  is it possible to do that for jupyter kernel?

Thanks

**Comment by takluyver** [comment]
Most kernels should provide some instructions on how to install their kernelspec. I don't know what those would be for any of the Scala kernels.

**Comment by rgbkrk** [comment]
The two kernels I recommend for Scala are:

* @alexarchambault's [jupyter-scala](https://github.com/alexarchambault/jupyter-scala)
* [Toree](https://toree.incubator.apache.org/docs/current/user/installation/)

As for R, we deploy R with Sparklyr using the IRKernel.

It's a standard R setup, the only difference is that we make sure all the environment variables for spark are all set up (`SPARK_OPTS`, `PYSPARK_SUBMIT_ARGS`, etc.)

**Comment by vhp1360** [comment]
hi @rgbkrk,
 thanks for the reply, I knew those, some of them need `sbt` command and I'm going to use existing packages.
as I understood I could not link existing Scala and Spark package and make a kernel for Jupiter, like as I did for R, am I right?
one thing more, it seems _Apache Toree_ isn't compatible with Spark 2.1.0.

thanks.

**Comment by vhp1360** [comment]
thanks @takluyver for the reply.
I knew [Jupyter Kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) but I'm going to know 
> how can I tell Jupyter to launch the kernel
as I mentioned, I can launch SparkR in R by linking, I'm interested to know  is it possible to do that for jupyter kernel?

Thanks

**Comment by rgbkrk** [comment]
I'm not well versed with the Scala setup, so I couldn't really tell you. I'd reach out to the toree devs or @alexarchambault if I were you.

**Comment by vhp1360** [comment]
OK!
if there is not any way we can close this.

thanks

**Comment by alexarchambault** [comment]
@vhp1360 Launching the [`jupyter-scala` script](https://github.com/alexarchambault/jupyter-scala/blob/master/jupyter-scala) like
```
$ ./jupyter-scala --jupyter-path /usr/local/share/jupyter
```
should install jupyter-scala under `/usr/local/share/jupyter/kernels/scala`. It doesn't need a spark distribution - it downloads the spark jars itself, depending on the version users ask in the session (illustrated [here](https://github.com/alexarchambault/jupyter-scala#spark)).

**Comment by vhp1360** [comment]
hi @alexarchambault, and thanks for your reply.
your solution is good, but I tried to know is there any way to link scala from scala package also spark and pyspark from Apache Spark package to python and then to Jupyter.
it seems, I'm looking for a hard issue and should forget it. :-)
