### ISSUE TITLE
Enhancement: Installing extensions from a jupyter-requirements.txt file

### ISSUE THREAD

**Issue by samzhang111** [jupyter/jupyter#256]
I recently moved a large project to a server, and found that my notebook failed to run because I was using an extension (jupyter_cms, for importing code from another notebook). I was also surprised about the lack of an easy way to install all of the extensions that I use locally.

I propose fixing this by adding a command to the jupyter command line to freeze extensions into a jupyter-requirements.txt file, and a command to install extensions from such a file.

**Comment by nemasobhani** [comment]
Seconded.

**Comment by r-nagaraj** [comment]
I have a requirement to open Jupyter Notebook in Read-only mode i.e it can be executed, but input cannot be changed.  
Please suggest any workaround to achieve the requirement and the same need to be invoke from command line (file notebook-conf.py).  Thanks

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. There's a straightforward mechanism to add jupyter subcommands, so anyone is welcome to experiment with adding such a feature, but it appears there is no appetite for working on this within the default jupyter installation.

Thanks everyone and happy hacking! :bowtie:
