### ISSUE TITLE
How to read nbserver info programmatically?

### ISSUE THREAD

**Issue by wang-shun** [jupyter/jupyter#257]
I have a server which runs multiple jupyter notebook instances. From the notebook cell I can run `notebook.notebookapp.list_running_servers()` to read all nbserver instances. 

> {u'secure': False, u'url': u'http://localhost:57439/research/user/wangshun/', u'hostname': u'localhost', u'pid': 10260, u'base_url': u'/research/user/wangshun/', u'token': u'e6ed7c9d6c9a69b9b4c19e976b0382a1dbe70310981cc5b7', u'notebook_dir': u'e:\\playground\\jupyter-repository\\wangshun', u'password': False, u'port': 57439}
{u'secure': False, u'url': u'http://localhost:57440/research/user/wangshun/', u'hostname': u'localhost', u'pid': 11528, u'base_url': u'/research/user/wangshun/', u'token': u'2e8d19c6110959a5bc6794610f3b2019bda753a65b1279b2', u'notebook_dir': u'e:\\playground\\jupyter-repository\\wangshun', u'password': False, u'port': 57440}

But it seems there is no programmatically way to find which instances I am currently using. 

Can anyone shed some light on this issue?

**Comment by takluyver** [comment]
You can see what *kernels* are currently running on a notebook server by making an http request to it. [Here's some code that does that](https://github.com/takluyver/nbmanager/blob/master/nbmanager/api.py).

The info you get back on each kernel should include a `last_activity` field with a timestamp of when the kernel was last used. This field is new in notebook 5.0.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
