### ISSUE TITLE
Dead Kernels with Python 2 envs, Import Name Constant Errors

### ISSUE THREAD

**Issue by thleo** [jupyter/jupyter#258]
My current setup:
Windows 8 enterprise
Notebook 5.0.0
Python 3.x
I attempted to install a python2 env with the [guide from IPython](http://ipython.readthedocs.io/en/stable/install/kernel_install.html):

```
conda create -n ipykernel_py2 python=2 ipykernel
source activate ipykernel_py2    # On Windows, remove the word 'source'
python -m ipykernel install --user
```
And I get errors trying to run the last line.

`python -m ipykernel install --user`

(Following the successful activation and creation of env) gives me a name constant error.
```
((C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3) C:\Users\danielle.le
ong>activate ipykernel_py2

(ipykernel_py2) C:\Users\danielle.leong>python -m ipykernel install --user
Traceback (most recent call last):
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\envs\ipykernel
_py2\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\envs\ipykernel
_py2\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\Lib\site-packa
ges\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\Lib\site-packa
ges\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\Lib\site-packa
ges\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\Lib\site-packa
ges\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\Lib\site-packa
ges\zmq\__init__.py", line 34, in <module>
    from zmq import backend
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\Lib\site-packa
ges\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\Lib\site-packa
ges\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\Lib\site-packa
ges\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\danielle.leong\AppData\Local\Continuum\Anaconda3\Lib\site-packa
ges\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name constants
```

I tried the code:
```
conda create -n py2 python=2 anaconda
# register py2 kernel
source activate py2
ipython kernel install
```

From @minrk 's comment in [Jupyter Issues 71](https://github.com/jupyter/jupyter/issues/71) thread with no success.

When launching jupyter server in chrome, I can go to the conda tab but I get import package error instantly, though my python 2 envs are there.

Also, when creating a notebook with my new env, the kernel always dies.

I tried deleting the notebook config file--which removed all kernels/python from jupyter--and it didn't work, so I restored it.

I've removed and installed new env of python2 via cmd multiple times and still getting dead kernels. My 3.x kernel is fine.

I've also tried installing a python3 env as per IPython's instructions but that threw the same error (import error with name constants).

Anyone know what might be the issue?

Suggestions?

**Comment by takluyver** [comment]
Is it possible that you might have upgraded pyzmq using pip at some point? Errors like that can arise when both pip and conda think they're managing the same package, and they can be really tricky to get rid of. The only reliable way is to remove Anaconda entirely and install it again.

**Comment by ebleo** [comment]
I don't recall updating pyzmq with pip--though I did perform a mass update to all packages that were outdated as of a month ago or so.

Is there a specific method for entirely removing anaconda?

**Comment by takluyver** [comment]
Re-reading what you wrote more carefully, is that your only Python 2 environment? If so, it might be worth trying removing it, then running `conda clean -tipsy` to clear caches, and creating it again.

I'm also less sure that the cause is what I thought it was. @minrk might have better ideas.

**Comment by minrk** [comment]
It's probably pyzmq and/or zeromq packages being messed up. Reinstalling one or both of these (I think the conda pyzmq package bundles zeromq) often solves problems like this. It's unclear what the cause usually is.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. RIP Python 2.

Thanks everyone and happy hacking! :bowtie:
