### ISSUE TITLE
When i install the anaconda scientific computation package in my virtual environment，it display a ConnectionError ，how can i solve it ？

### ISSUE THREAD

**Issue by gehongyi** [jupyter/jupyter#259]
When i install the anaconda scientific computation package in my virtual environment，it display a ConnectionError ，how can i solve it ？Thanks, and the following is all the display：

C:\Users\Administrator>activate python36

(python36) C:\Users\Administrator>conda install -n python36 anaconda
Fetching package metadata .....

CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-
64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ConnectionError(ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io',
port=443): Read timed out.",),)

**Comment by blink1073** [comment]
Hi @gehongyi, it could be that the site was temporarily down.  I tried running that command just now and it went through.  Can you please try again?

**Comment by gehongyi** [comment]
@blink1073 i have tried again ,and i solved the issues,thank you very much!

**Comment by blink1073** [comment]
Cheers!
