### ISSUE TITLE
XSRF cookie does not match POST argument

### ISSUE THREAD

**Issue by SaintNazaire** [jupyter/jupyter#260]
I am trying to transfert files using a python program running on a local Anaconda to a local Jupyter within a docker container using the Jupyter rest API.

I managed already to execute a requests.get() succesfully after muddling-through a bit on how to input the token.

Now I would like to execute a requests.post() command to transfert the files.

Configuration:
1. local docker container running on docker toolbox for windows
- docker version 17.04.0-ce, build 4845c56
- tensorflow/tensorflow incl. Jupyter latest version install
- jupyter_kernel_gateway==0.3.1
2. local Anaconda v. 4.3.14 running on a windows 10 machine

Code:
```
token = token_code_provided_by_jupyter_at_startup
api_url = "http://192.168.99.100:8888/api/contents"
# getting the file's data from disk and converting into a json file
cwd` = os.getcwd()
file_location` = cwd+r'\Resources\Test\test_post.py'
payload` = open(file_location, 'r').read()
b64payload` = base64.encodestring(payload)
body = json.dumps({
            'content':b64payload,
            'name': 'test_post.py',
            'path': '/api/contents/',
            'format': 'base64',
            'type':'file'
        })
# getting the xsrf cookie
client` = requests.session()
client.get('http://192.168.99.100:8888/')
csrftoken` = client.cookies['_xsrf']
cookies = dict(client.cookies)
headers ={'Content-type': 'application/json', 'X-CSRFToken':csrftoken, Referer':'http://192.168.99.100:8888/api/contents', 'token':token}
response = requests.post(api_url, data=body, headers=headers, verify=True)
```
Error returned

> [W 12:22:36.710 NotebookApp] 403 POST /api/contents (192.168.99.1): XSRF cookie does not match POST argument
> [W 12:22:36.713 NotebookApp] 403 POST /api/contents (192.168.99.1) 4.17ms referer=http://192.168.99.100:8888/api/contents

**Comment by takluyver** [comment]
Discussion on https://github.com/jupyter/help/issues/172 ;  closing here for now.
