### ISSUE TITLE
Notebook Server API documentation of required params and expected output

### ISSUE THREAD

**Issue by atomless** [jupyter/jupyter#261]
I find I'm sadly lacking the esp required to discover the schema of required params for the various endpoints of this API. Anyone know of any other source of documentation on this?

https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API

**Comment by blink1073** [comment]
Hi @atomless, the schema is [here](https://github.com/jupyter/notebook/blob/master/notebook/services/api/api.yaml), rendered nicely [here](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml).

**Comment by willingc** [comment]
I've added @blink1073 suggested text and links to the wiki page cited by @atomless.

Hope that helps.
