### ISSUE TITLE
Jupyter notebook connect with c#

### ISSUE THREAD

**Issue by lesiano** [jupyter/jupyter#262]
Hello all,

I'm trying to connect to a jupyter notebook to use the c# api but I don't know how to do it. I already tried a lot of things.. but is always returning the html of a web page. Do anyone knows how to connect to it? 
I'm using this code:
```
  Client = new RestClient("https://0.0.0.1/user/api");
  Client.AddHandler("application/json", new DynamicJsonDeserializer());
  var cookieUser= new Cookie("user", _userName, "/", "0.0.0.1");
  var cookiePassword= new Cookie("password", _password, "/", "0.0.0.1");
  Client.CookieContainer= new CookieContainer();
  Client.CookieContainer.Add(cookieUser);
  Client.CookieContainer.Add(cookiePassword);
```

Can someone help me? :)

Thanks a lot.
Regards.

**Comment by Carreau** [comment]
Hi, I'm relatively confused about this issue:
>  to use the c# api
We don't have a  c# api, we have a REST api, and you are trying to access it via C# ?

> "https://0.0.0.1/user/api" 

This IP and url scheme is weird are you hosing it yourself ? How are you running the notebook server ?

Are you y any chance confusing Jupyter (the open source project) for one of the many companies that are actually using Jupyter ?

**Comment by lesiano** [comment]
Hi Carreau,

Thanks for your answer. 

I'm talking about this api: [http://jupyter-api.surge.sh/#/](url)

The IP is not correct. Just put some fake IP :) the URL Scheme is the one I don't know.. Don't know how to use the api and how to connect to the web page using c#.
Just put the code where I try to connect to the notebook.

Thanks a lot.

**Comment by takluyver** [comment]
If that's a JupyterHub server, then I think that URL is looking for a user called `api`. The URL you'd need would be something like `https://<server_ip>/user/lesiano/api`. There's also a separate API for the hub itself.

**Comment by lesiano** [comment]
Hi takluyver,

I already tried to put that URL and what I receive is an HTML with: "   
    <h1>404 : Not Found</h1>
    <p>You are requesting a page that does not exist!</p>"

Thanks.

**Comment by takluyver** [comment]
Is it definitely a user that exists? I can do it with demohub: https://demohub.jupyter.org/user/takluyver/api .

**Comment by lesiano** [comment]
Hi takluyver,

Yes, the user exists. I don't need  the password for accessing it?

Thanks

**Comment by takluyver** [comment]
Seemingly not - I can access the URL I gave above in a private browsing session, where I'm not logged in.

**Comment by lesiano** [comment]
Sorry for the delay..
Seems I have a SSL problem. its working with your URL..

Thanks for everything
I will close the isse.
