### ISSUE TITLE
Broken Link to a notebook - 404

### ISSUE THREAD

**Issue by krishna247** [jupyter/jupyter#263]
An Introduction to Applied Bioinformatics: Interactive lessons in bioinformatics, by Greg Caporaso.
The link is found in the Matchematics, Physics, Chemistry and Biology section [here](https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks#mathematics-physics-chemistry-biology)

This link is broken.

**Comment by krishna247** [comment]
This is in "A gallery of interesting Jupyter Notebooks"

**Comment by takluyver** [comment]
Thanks, I've updated it to http://readiab.org/ . That's a wiki page, so you should be able to edit it yourself if you spot other problems.
