### ISSUE TITLE
Run ipynb file with RESTful way?

### ISSUE THREAD

**Issue by liushaofeng89** [jupyter/jupyter#268]
Is there a way running *.ipynb or *.py file with RESTful? in my system i need a solution like this, Can you give me some advise?

**Comment by takluyver** [comment]
https://github.com/jupyter/kernel_gateway/ might be what you're looking for.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
