### ISSUE TITLE
Add additional installation paths

### ISSUE THREAD

**Issue by parente** [jupyter/jupyter#27]
The existing install docs are great for getting a basic Jupyter Notebook environment locally. As we look to make it ever easier for users to walk-up and get a notebook environment with supporting tools for work in their favorite languages on their desktop or in the cloud, we should expand with further options. Some suggestions:

1. Instructions or pointer to running docker-stacks in a VM locally (why: batteries included vs pip/conda install everything natively)
2. Instructions on deploying single notebook instances to cloud providers (e.g., Rackspace, Softlayer, AWS, ...) (why: bigger machines, on compute clusters)

I'm glad to contribute over time here. Just writing the idea down for consideration.

**Comment by Carreau** [comment]
I think we should get external docs/wiki for that, and link to it. The external provider docs will most likely have quicker update than our releases. I'm fine if it's a wiki, or one of our repos (like this one), I just think it should not be tied to a specific package docs.

**Comment by parente** [comment]
> I'm fine if it's a wiki, or one of our repos (like this one), I just think it should not be tied to a specific package docs.

Discoverability is my concern. The new Jupyter home page brought this to mind. There's two buttons: try it (try.jupyter.org) and install it (direct link to the readthedocs install page). My concern about the latter is that, it gets you jupyter notebook et al but doesn't direct you to how to go beyond that. For example, if I'm an R+Spark user, and the Jupyter home page is telling me I can use R, Spark, and all these wonderful things together, how do I do it? Where do I go for that info?

**Comment by Carreau** [comment]
Good point.

**Comment by minrk** [comment]
This is one of the things that I think is tricky - in some ways, I think a wiki is the best format for more specialized cookbook-style docs (I think some amount of more special-case installation would belong there), but having yet another place for docs isn't attractive. Given the balance of things, adding more detailed, "example installation" docs for things like docker setups probably makes sense to be adjacent to the existing installation docs in the same repo.

**Comment by parente** [comment]
> adding more detailed, "example installation" docs for things like docker setups probably makes sense to be adjacent to the existing installation docs in the same repo.

Yes. A few opinionated "If you're an R and Python data scientist, you can easily get setup locally with ..." type recipes would go a long way in the doc. After those, it seems reasonable to have a final section to "community contributed recipes" which could live ... somewhere. Maybe on the wiki attached to this repo where the main docs live?

**Comment by ellisonbg** [comment]
I like having the bigger picture installation docs on the RTD of this repo. 

I would suggest have a new top level item in addition to the existing "Installation" section that is something like "Alternate Installation Scenarios" and try to focus on official supported/best practices approaches.

We could also have a single Installation section with the existing stuff going under a "Basic" subsection. But I am worried about flooding new users with all of the installation information at once.

**Comment by minrk** [comment]
Oops, forgot to mention that I brought this up [on the mailing list](https://groups.google.com/forum/#!msg/jupyter/QnqcMVb4jDo/Jl2MlmPlEAAJ) for wider discussion. Doesn't appear to have grabbed anyone's attention yet, though.

**Comment by willingc** [comment]
Closing this based on the old date and the progress that we are making (and will continue to make :smile:) on docs.
