### ISSUE TITLE
Add "go to definition" feature

### ISSUE THREAD

**Issue by misteraverin** [jupyter/jupyter#271]
When you use Pycharm, you can click `Ctrl+B` and go to line of code where variable was defined. I suppose it would be nice to have this feature in `jupyter`. What do you think? @takluyver @ellisonbg

**Comment by takluyver** [comment]
Would be nice, but pretty tricky to implement.

**Comment by Murtaza0xFF** [comment]
Any updates on this?

**Comment by krassowski** [comment]
Please see my workaround (although tested only in jupyter-lab) here: https://github.com/jupyterlab/jupyterlab/issues/4562#issuecomment-435608004

**Comment by krassowski** [comment]
And here is a follow-up: a [jupyter-lab go-to-definition extension](https://github.com/krassowski/jupyterlab-go-to-definition).

**Comment by Tontonconvolution2000** [comment]
Hi everyone, 

Thank your for your work. Those features are very helpful but i was not able to implemente this extension altough i followed all instructions provided to install it.  And i have no clues on what is going wrong.

None of features described in the readme seems working. And, again, no informations to understand why..

Thanks for your wor have a nice day

**Comment by krassowski** [comment]
That extension is no longer maintained. Instead this functionality is now available in the LSP extension. It is explained in the README, at the very top:

> ## Status: inactive
>
> This extension is no longer maintained. Please use [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp) which provides more features, including  advanced autocompletion, code navigation, hover suggestions, linters, etc.
