### ISSUE TITLE
Error launching jupyter notebook on Windows using Anaconda

### ISSUE THREAD

**Issue by pmerwah** [jupyter/jupyter#273]
when I try to launch notebook : jupyter notebook. I get the following error:

Assertion failed!

Program: C:\Users\name\Anaconda3\envs\tensorflow-gpu\python.exe
File: markupsafe/_speedups.c, Line 33

Expression: PyUnicode_Check((PyUnicodeObject*)PyUnicode_DecodeASCII("&#34;", strlen("&#34;"), ((void *)0)))

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

my conda info for reference:
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\name\Anaconda3  (writable)
    default environment : C:\Users\name\Anaconda3\envs\tensorflow-gpu
       envs directories : C:\Users\name\Anaconda3\envs
                          C:\Users\name\AppData\Local\conda\conda\envs
                          C:\Users\name\.conda\envs
          package cache : C:\Users\name\Anaconda3\pkgs
                          C:\Users\name\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\name\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.14393
          administrator : False

**Comment by takluyver** [comment]
That looks like a problem in the `markupsafe` package. You could try uninstalling and reinstalling that.

**Comment by pmerwah** [comment]
Thank you Takluyver. I downgraded markupsafe to ver 0.9 from ver 1.0 and it works. For anyone looking for the fix:
pip install --upgrade markupsafe==0.9

**Comment by tRosenflanz** [comment]
If you are getting an error trying to install version 0.9
pip install --upgrade markupsafe==0.9.3
