### ISSUE TITLE
ETL with python notebook

### ISSUE THREAD

**Issue by dimgold** [jupyter/jupyter#274]
I suggest to add to the wiki an ETL with python notebook (using ``petl`` package) from here:
https://github.com/dimgold/ETL-with-Python/blob/master/ETL_with_Python.ipynb

**Comment by Carreau** [comment]
Hi @dimgold. 
I'm unsure what you are asking.

First if it's python specific it should be on  https://github.com/ipython/ipython (but that's a detail). 
Second IPython does not ship or maintain any actual code to handle data, we are "just" the glue between the frontend and the library code.

 If it's only to the wiki feel free to edit yourself, it is a wiki so is open to any contribution without the need having to ask for prior authorization, and we will be really happy to have a better wiki with your contribution. You can edit the wiki from the GitHub Interface, or you can also use git to clone it and edit locally. 

Does that answer your question / suggestion ?

**Comment by dimgold** [comment]
yep, I'll update myself
