### ISSUE TITLE
Execute Notebook by Server Api 

### ISSUE THREAD

**Issue by pepgal** [jupyter/jupyter#275]
Hi! There is a way to run a Notebook by Notebook Server Api? I found example that run py script but no a Ipynb file. In other discussion an user describes mixed used of Api methods for realize that, but not posted code/example! Thanks a lot.

**Comment by takluyver** [comment]
Not super easily, unfortunately. Do you need to do it through a notebook server? If you just need to run a notebook programatically, nbconvert has code that can do that directly:

https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py
