### ISSUE TITLE
how are nbextensions updated?

### ISSUE THREAD

**Issue by davidedelvento** [jupyter/jupyter#277]
In other words, does a `jupyter nbextension install blah` perform an update on `blah` if `blah` is already installed?

Sorry if this is just a documentation issue, but I can't find the answer anywhere (not in `jupyter nbextension --help-all`, not in official documentation, not anywhere on the internet that Google knows).

I need to separate the install from the update and it's not clear if update is done or not with the regular install. If it is, is there a flag to **prevent** it? If it isn't, how is an update done?

**Comment by takluyver** [comment]
Looking at [the code](https://github.com/jupyter/notebook/blob/823e44729381c52cce3c2c1b26529447de544e64/notebook/nbextensions.py#L77), it looks like it mostly will upgrade the files, but the situation is extremely messy - sorry.

There's a `--overwrite` flag which is meant to force overwriting already installed extension files. But:

- If the extension is already installed in a different place (see the *data* section of `jupyter --paths`), it completely ignores that and does a fresh install no matter what.
- If you're installing from an archive (zip or tarball), it looks like it will overwrite all files regardless of the flag.
- If you don't pass `--overwrite`, it will still overwrite files where the modified time of the source file is newer than that of the destination.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
