### ISSUE TITLE
Using Python 2.x kernel from Jupyterhub

### ISSUE THREAD

**Issue by sudipto84goswami** [jupyter/jupyter#278]
Hi Team,

We have an installation of Jupyterhub through Anaconda and the base python version is 3.5.  We have a requirement to use python version 2.x on the same notebook but having a separate kernel for the same.

I did install Python 2.7.13 separately for this and also create a kernel spec file similar to that of Python 3.5 version.

  python2     /usr/local/share/jupyter/kernels/python2
  python3     /usr/local/share/jupyter/kernels/python3

The content of the Kernel Json file is:

/app/sasdata/jupyter/Python2/Python-2.7.13 $ cat /usr/local/share/jupyter/kernels/python2/kernel.json
{
 "display_name": "Python 2",
 "language": "python",
 "argv": [
  "/app/sasdata/jupyter/anaconda3/envs/default-notebook/bin/python2",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ]
}

After this, i did restarted my jupyterhub notebook server and whenever i am trying to use Python 2 it gives me error as Kernel Died always.

I also tried python -m pip install --upgrade ipykernel [specifically for Python2], but it always states:
Requirement already up-to-date: ipykernel in /app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages

Can you please help on this.

**Comment by Carreau** [comment]
Wether the kernel dies is not related to JupyterHub, what you can try to do is to login via another method (or even use the web terminal in web application) and try to start the kernel manually. 

```
$ /app/sasdata/jupyter/anaconda3/envs/default-notebook/bin/python2 -m ipykernel
```

You should (if all goes ok) see:

```
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-28657.json
```

You will likely see an error message, this will tell you why the kernel is dying. This message will help us help diagnose what is happening.

**Comment by sudipto84goswami** [comment]
This gives the error message as : 

/app/sasdata/jupyter/anaconda3/envs/default-notebook/bin $ ./python2 -m ipykernel
Traceback (most recent call last):
  File "/app/sasdata/jupyter/Python2/Python-2.7.13/Lib/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/app/sasdata/jupyter/Python2/Python-2.7.13/Lib/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named backports.shutil_get_terminal_size


Not sure why this is being still routed to Python3.5

**Comment by Carreau** [comment]
What's your $PATH ? have you customized it ?

**Comment by Carreau** [comment]
You might also want to start a pure python2 repl and look at `import site; site.PREFIXES`.

**Comment by sudipto84goswami** [comment]
$PATH is not customized. Below is the value.

/app/sasdata/jupyter/anaconda3/envs/default-notebook/bin $ echo $PATH
/app/sasdata/jupyter/anaconda3/bin:/app/sasdata/jupyter/anaconda3/lib64:/app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages:/app/sasdata/jupyter/anaconda3/bin:/usr:/usr/local:/usr/local/bin:/usr/local/lib:/usr/bin:/app/sasdata/jupyter/latex:/usr/lib:/usr/local/share/swig/3.0.8:/usr/local/share/swig/3.0.8/python:/usr/share/swig/3.0.8/python:/usr/share/swig/3.0.8:/app/sasdata/jupyter/anaconda3/pkgs:/usr/lib64/qt-3.3/bin:/sbin:/bin:/usr/sbin:/usr/bin:/app/sasdata/jupyter/anaconda3/bin:/app/yum_installs/usr/bin

Below is the details after starting Python2
/app/sasdata/jupyter/Python2/Python-2.7.13 $ ./python
Python 2.7.13 (default, Aug 10 2017, 14:40:07)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import site;
>>> site.PREFIXES
['/usr/local', '/usr/local']
>>>

**Comment by Carreau** [comment]
There is definitively something fishy going on as you have `/app/sasdata/jupyter/anaconda3/bin` several time and `:/app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages` is in your path. 
If it is in your $PATH that explain why Python picks it up from there. 

Check your `.profile`, `.bashrc` , `.bash_profile` for $PATH modification.
AFAICT by default anaconda should _only_ add `export PATH="~/anaconda/bin:$PATH"` and even when activating environments, `site-packages` should not be on PATH:

```
~ $ source activate 27
(27)  ~ $ $PATH
EnvPath(
['$HOME/anaconda/envs/27/bin',
 '$HOME/bin',
 '$HOME/anaconda/bin',
 '/usr/local/bin',
 '/usr/bin',
 '/bin',
 '/usr/sbin',
 '/sbin',
 '/opt/X11/bin',
 '/usr/texbin']
```

**Comment by sudipto84goswami** [comment]
As mentioned earlier, Python 3.5 was installed by default while installing Anaconda so this got resided under /app/sasdata/jupyter/anaconda3/. And now as per the requirement, i need to add on Python 2.x in the current setup, so that while opening notebook i can select both version 3.x and 2.x .

So for achieving this, i installed Python 2.7 separately and created the kernel,json similar to that of Python 3.5 , and just replacing the Python executable.

So it will be helpful, if you can help me out where to start debugging on this.

**Comment by Carreau** [comment]
> i installed Python 2.7 separately

How ?

> created the kernel,json similar to that of Python 3.5 , and just replacing the Python executable.

How ? Did you edit the kernel.json file by hand ?

Because as I mentioned earlier your Python/Anaconda install seem to be wrong. This is not how an anaconda install should look like. You have things on your $PATH that are not supposed to be on $PATH and are likely the cause to your troubles. 

As I ask before:

> Check your .profile, .bashrc , .bash_profile for $PATH modification.

Once we figured out why your $PATH is not right we can find a fix.

Also try the following:

```
$ python2
>>> import site; site.getsitepackages()
```

**Comment by sudipto84goswami** [comment]
Installation of Python 2.7.13 --> This was done through traditional downloading the tar file and doing an install.

Kernel.json --> Yes i copied it from hand and replaced the executable.

Do i need to specify anything specific to Python 2 on .profile file. As the Python 3 was installed as a part of Anaconda, so this is having the entry like this.

It would be really helpful if you can tell me just : How to configure Python 2.x kernel on a Jupyterhub Notebook which was installed through Anaconda and was having Python 3.5 by default, so that the users can select any of the versions (2.7 or 3.5) as required by selecting the appropriate kernel.

**Comment by minrk** [comment]
> Do i need to specify anything specific to Python 2 on .profile file. As the Python 3 was installed as a part of Anaconda, so this is having the entry like this.

This shouldn't be necessary.

>  It would be really helpful if you can tell me just...

From [the docs](http://ipython.readthedocs.io/en/latest/install/kernel_install.html#kernels-for-python-2-and-3), the following will install Python 2 its kernelspec system-wide:

```bash
# install the ipykernel package for python 2
pip2 install ipykernel
# install the python 2kernelspec system-wide. Add --user to install it just for you
python2 -m ipykernel install
```

If you already had Python 3 set up, that's all you need. But it's possible for extra PATH and PYTHONPATH environment variables to cause problems with an otherwise correct installation, and I suspect that's what is going on based on what you have provided. As @Carreau said, `site-packages` shouldn't be on PATH, so you should find what's adding that and remove it. Do you perhaps have `$PYTHONPATH` env set? If so, please unset it and find wherever it is being set (perhaps .profile/bashrc) and remove it. It is very rare that PYTHONPATH should be set to anything, and it should never include a site-packages directory, or a directory containing compiled Python packages.

**Comment by sudipto84goswami** [comment]
One thing which is coming to my mind:
[root@ndwjupyter-ch2-a1p Python-2.7.13]# pip -V
pip 9.0.1 from /app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages (python 3.5)

The pip which is installed is corresponding to Python 3.5 version. Do i need to install a pip again for Python 2.x again as whenever i do pip install ipykernel it tells me - 

[root@ndwjupyter-ch2-a1p Python-2.7.13]# python -m pip install ipykernel
Requirement already satisfied: ipykernel in /app/sasdata/jupyter/anaconda3/lib/python3.5/site-packages
[root@ndwjupyter-ch2-a1p Python-2.7.13]#

**Comment by Carreau** [comment]
> The pip which is installed is corresponding to Python 3.5 version. Do i need to install a pip again for Python 2.x again as whenever i do pip install ipykernel it tells me -

No, you can "just" do `python2 -m pip` whenever you need `pip2`

> Kernel.json --> Yes i copied it from hand and replaced the executable.

> As @Carreau said, site-packages shouldn't be on PATH, so you should find what's adding that and remove it.

These 2 also mean you do not have IPython and ipykernel installed fro Python 2, which aamy also help to explain why it tried to fall back further on Path. 

> Installation of Python 2.7.13 --> This was done through traditional downloading the tar file and doing an install.

Now that's also extremely weird. You do have anaconda, anaconda is ment to have multiple Python and right now you are struggling with having an anaconda Python 3 and a system Python 2 built from tgz. Why ? Why not just use conda environments ?

**Comment by sudipto84goswami** [comment]
This gives error as:

[root@ndwjupyter-ch2-a1p sasdata]# python2 -m pip install ipykernel
/usr/bin/python2: pip is a package and cannot be directly executed
[root@ndwjupyter-ch2-a1p sasdata]#

However I am getting python 2 prompt
[root@ndwjupyter-ch2-a1p sasdata]# python2
Python 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Carreau** [comment]
> Installation of Python 2.7.13 --> This was done

> However I am getting python 2 prompt
> [root@ndwjupyter-ch2-a1p sasdata]# python2
> Python 2.6.6 (r266:84292, Aug 9 2016, 06:11:56)

So your Python install is screwed up. You can't have installed Python2.7 correctly if `Python2` executable give you a 2.6.6 prompt from something built more than a year ago.

So definitively you first need to fix your Pythons installs. Once you fixed your Pythons install and Multiple Pythons works correctly we can get your IPython kernels install correctly for Jupyter.
I would suggest : Deciding on which Python distribution you'd like to use: Anaconda, your System one, or custom builds – mixing will bring you trouble. Then join the mailing lists of your OS, anaconda/ whatever is relevant for your Python distribution and get help with that. And once this is done, you get your Python setup correctly we can help you with figuring things out.

Right now the issue you have are not related to Jupyter, and until you get your system in a strait state there is little hope and getting Jupyter to work right. 

We've also asked you a couple of other questions and given a number of hints in previous messages that you do not seem to have investigated. I would also suggest looking at those and fixing them before moving  forward.

**Comment by sudipto84goswami** [comment]
Let me clear this up and will get back again.

**Comment by RajeshB61** [comment]
I have a similar issue. I have anaconda installed with Python3.6. I use JupyterHub and want python2.7 kernel to be installed python 2.7 using conda and installed ipyhton kernel. I can see the kernel in jupyter notebook but the kernel is always dead. Any idea where i'm wrong?

Available kernels:
  python3    /usr/local/anaconda3/share/jupyter/kernels/python3
  python2    /usr/local/share/jupyter/kernels/python2

/usr/local/anaconda3/envs/python27/bin/python -m ipykernel
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-22370.json
quit
^\Quit (core dumped)
(python27) [root@srvmuldvlsk93 ~]# /usr/local/anaconda3/envs/python27/bin/python
Python 2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 23:32:55)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import site; site.getsitepackages()
['/usr/local/anaconda3/envs/python27/lib/python2.7/site-packages', '/usr/local/anaconda3/envs/python27/lib/site-python']
>>> quit()

**Comment by RajeshB61** [comment]
# $PATH
-bash: /usr/local/anaconda3/envs/python27/bin:/usr/local/anaconda3/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

# conda info --envs
# conda environments:
#
base                     /usr/local/anaconda3
python2.7                /usr/local/anaconda3/envs/python2.7
python27              *  /usr/local/anaconda3/envs/python27


I have anaconda2 as well installed but have commented the path.

**Comment by constant5** [comment]
Did you install the Python 2 IPython kernel?

https://ipython.readthedocs.io/en/stable/install/kernel_install.html

**Comment by zainul1114** [comment]
Hi,
I am new to jupyterhub and i am trying to Add multiple python kernel(2.7.x,3.6.x,3.7.x) to jupyterhub 
my default python version is 3.6.8 which is installed from python sourcefile, 

i am able to run jupyterhub with python3.
Python path: /share/apps/platform/ai/py36/3_6_8/bin/python3

But now i am trying to add Python 2.7.16 kernel
 
my python2 installation path: /share/apps/platform/ai/py27/2_7_16/bin/python

# jupyter-kernelspec list
Available kernels:
ir /root/.local/share/jupyter/kernels/ir
python3 /share/apps/platform/ai/py36/3_6_9/share/jupyter/kernels/python3

i tried to add python2:
[root@master ~]# python --version 
Python 2.7.16 
[root@master ~]# python3 --version 
Python 3.6.9 

#python2 -m ipykernel install 
Installed kernelspec python2 in /root/.local/share/jupyter/kernels/python2

[root@master ~]# jupyter-kernelspec list 
Available kernels: 
 ir /root/.local/share/jupyter/kernels/ir 
 python3 /share/apps/platform/ai/py36/3_6_9/share/jupyter/kernels/python3 
 python2 /usr/local/share/jupyter/kernels/python2

and when i try to check logsof jupyterhub, i am getting below error

Jul 6 22:00:03 master jupyterhub: [I 2020-07-06 22:00:03.662 SingleUserNotebookApp restarter:110] KernelRestarter: restarting kernel (4/5), new random ports 
Jul 6 22:00:03 master jupyterhub: /share/apps/platform/ai/py27/2_7_16/bin/python2: No module named ipykernel_launcher 
Jul 6 22:00:06 master jupyterhub: [W 2020-07-06 22:00:06.690 SingleUserNotebookApp restarter:100] KernelRestarter: restart failed 
Jul 6 22:00:06 master jupyterhub: [W 2020-07-06 22:00:06.691 SingleUserNotebookApp kernelmanager:135] Kernel 2997ce87-ab15-475a-b4a0-d534bf910d8f died, removing from map. 


Please guide me how to resolve this.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Python 2 reached its end of life support a while ago. Please report issues related to https://github.com/jupyterhub/jupyterhub there

Thanks everyone and happy hacking! :bowtie:
