### ISSUE TITLE
How to use python3 modules in jupyter without change the kernel?

### ISSUE THREAD

**Issue by lpulido96** [jupyter/jupyter#285]
Hi.
I'm writing a python2 code in jupyter, but I need some python3 functions. So, how can I use python3, without change the python2 kernel, in order to avoid the sinax differences between python2 and python3.
Thank you.

**Comment by Carreau** [comment]
Hi there, 

Thanks for your question, this seem to be a pure is a pure Python question, it is unrelated to Jupyter and can be applied in any python context. 

Python 3 have features that Python 2 does not have, for most of these, you cannot get them on Python 2 it is technically impossible. You have to switch to Python 3. 

The only couple of things you can get back on Python 2 are documented [here](https://docs.python.org/2/library/__future__.html#module-__future__), for the rest there might be workaround but that will be on a case by case basis.

**Comment by rgbkrk** [comment]
I wonder what it would be like to make a "compat" kernel that only allows you to do things that work in both Python2 and Python3. 🤔

**Comment by Carreau** [comment]
Syntax wise ? Or librarywise ? Because if later one that's going to be tough as you need to consider every minor version of Python 3. Even 3.5 has syntax invalid 3.4...

**Comment by rgbkrk** [comment]
Foiled again!

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Let's pour out a cold one for Python 2. :beers: 

Thanks everyone and happy hacking! :bowtie:
