### ISSUE TITLE
Gallery of interesting notebooks removed from the wiki

### ISSUE THREAD

**Issue by mjclarke94** [jupyter/jupyter#287]
Any particular reason for this? If it has been relocated, it's probably worth adding a redirect as it is a page that is fairly regularly linked to in jupyter discussions.

**Comment by takluyver** [comment]
Thanks for the heads up: it looks like it was accidentally wiped yesterday. I've restored it now:
https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks

@jlomask no harm done here, let us know if you have any questions about how the wiki works.
