### ISSUE TITLE
Incorrect solution using numpy.dot() with float32 in Jupyter

### ISSUE THREAD

**Issue by DevinShanahan** [jupyter/jupyter#291]
ython 3.6.2 :: Anaconda, Inc. Jupyter 4.3.0, Notebook 5.0.0, numpy 1.13.1, MacOS 10.13
```
import numpy as np

vector_one = np.asarray([
    [1],
    [2],
    [1]
], dtype=np.float32)

vector_two = np.asarray([
    [3],
    [0],
    [1]
], dtype=np.float32)

dot_product = np.dot(vector_one[:,0], vector_two)
print(dot_product)
[0.]
```

Solution should be [4.].  Solution is correct in Terminal, only occurs in Jupyter Notebook when dtype=np.float32, using two vectors with the first being transposed as above or using .T

<img width="591" alt="screen shot 2017-10-04 at 12 21 13 pm" src="https://user-images.githubusercontent.com/17952172/31189725-aee5de74-a8fe-11e7-96f8-a5332f6d70d3.png">

**Comment by Carreau** [comment]
It's really unlikely that the issue is with Jupyter. 
Can you check `sys.executable` and the version of numpy from within the notebook ? 

I get the correct value of `[4.]` both in terminal and notebook.

**Comment by DevinShanahan** [comment]
from notebook:
```
sys.executable
'/anaconda3/bin/python'
np.__version__
'1.13.1'
```

If the issue is not with Jupyter, any ideas where I should be troubleshooting?

**Comment by Carreau** [comment]
> If the issue is not with Jupyter, any ideas where I should be troubleshooting?

No, unsure, I would try by directly invoking '/anaconda3/bin/python' to make sure there is no issue in with which executable refer to what, and make sure you do not have custom startup code in `~/.ipython/profile_default`. 

Maybe creating a new env, with a different names and try with this env.

**Comment by DevinShanahan** [comment]
It did work with a new env.  Thanks.

**Comment by jiangzhongshi** [comment]
I've encountered the same problem. 
```
import os
import sys
import numpy as np
v = np.array([ 0.26996088,  0.29773563,  0.10177446], dtype=np.float32)
np.dot(v,v)
```
Gives me -1.0842022e-19 in Jupyter, but correct if invoked from terminal.
