### ISSUE TITLE
Concurrent file serving is broken?

### ISSUE THREAD

**Issue by ebraminio** [jupyter/jupyter#292]
I've filled this [here](https://github.com/jupyter/jupyter_server/issues/11) but as it seems bug report of that repository is not that active and my previous bug didn't get any response I feel I should report it here also,

(rest is copied from https://github.com/jupyter/jupyter_server/issues/11, feel free close one of the files)

----

Hey guys, I am experiencing very weird issue with jupyter that I guess is a regression. Here is its steps to reproduce:

Create a notebook, put this code on first cell to create test images:

```python
from PIL import Image
from PIL import ImageDraw

for i in range(1, 21):
    img = Image.new('RGBA', (10, 10), 255)
    draw = ImageDraw.Draw(img)
    draw.text((0, 0), str(i), fill="black")
    img.save(str(i) + '.png')
```

Put this on the next cell as markdown:

```html
<img src="1.png" width="30">
<img src="2.png" width="30">
<img src="3.png" width="30">
<img src="4.png" width="30">
<img src="5.png" width="30">
<img src="6.png" width="30">
<img src="7.png" width="30">
<img src="8.png" width="30">
<img src="9.png" width="30">
<img src="10.png" width="30">
<img src="11.png" width="30">
<img src="12.png" width="30">
<img src="13.png" width="30">
<img src="14.png" width="30">
<img src="15.png" width="30">
<img src="17.png" width="30">
<img src="18.png" width="30">
<img src="19.png" width="30">
<img src="20.png" width="30">
```

Actual:
I see such result this, differently every time:

![screen shot 2017-10-08 at 4 59 12 pm](https://user-images.githubusercontent.com/833473/31317232-14f7693c-ac4a-11e7-825d-405d619ebbd8.png)

Expected:
To images loaded correctly.

My system:
jupyter --version: 4.3.0
macOS High Sierra

I can reproduce this very consistently on my setup, Is jupyter server somehow fails on serving concurrent requests or something else is wrong?

**Comment by takluyver** [comment]
:confused: What do you see in the terminal where the notebook is running when you do that?

**Comment by ebraminio** [comment]
Nothing in particular:

![screen shot 2017-10-09 at 4 02 06 pm](https://user-images.githubusercontent.com/833473/31338228-40c9e3d4-ad0b-11e7-95ac-d1735846e0d0.png)

Which packages do you suggest I should reinstall? For some reasons it seems I only this example broken on Safari but my another test is also broken on other browsers.

**Comment by takluyver** [comment]
You could try upgrading or reinstalling `notebook`, but I've no idea what would cause something like that.

I just tried and it seems to work as expected for me:
![screenshot from 2017-10-09 14-21-58](https://user-images.githubusercontent.com/327925/31340238-6c9e5b92-acfd-11e7-9dc5-0af4597ded7a.png)

**Comment by takluyver** [comment]
Is it possible that you drew numbers with non-matching file names at some point before? If you've displayed them before it could be caching them in the browser.

**Comment by ebraminio** [comment]
> You could try upgrading or reinstalling notebook, but I've no idea what would cause something like that.

Tried that, no problem.

> Is it possible that you drew numbers with non-matching file names at some point before? If you've displayed them before it could be caching them in the browser.

I have the issue I have the issue on variety of things so that's unlikely. But I've installed very different plugins and languages kernels for notebook and even once installed jupyter_server from source for developing different things. In order to reduce interference of other issues, where can I reset more of jupyter configs? ~/.jupyter folder didn't have much of the settings it seems.

**Comment by takluyver** [comment]
Run `jupyter --paths` to see where stuff is. Javascript extensions and other kernels are both installed into the 'data' paths it will show you.

I don't think other kernels should affect this. I guess nbextensions might, though I don't know how.

**Comment by ebraminio** [comment]
No idea why this test-case is very Safari specific, while I am trying my other notebooks that also are broken on Chrome and Firefox, can you try Safari for the specific test case I've put?

**Comment by takluyver** [comment]
Nope, no Safari on Linux ;-)

**Comment by ebraminio** [comment]
> Run jupyter --paths to see where stuff is. Javascript extensions and other kernels are both installed into the 'data' paths it will show you.

> I don't think other kernels should affect this. I guess nbextensions might, though I don't know how.

I've purged all of the folders was listed on jupyter --paths and the issue still exists.

Hmmm, with more number of images I can see the issue on Firefox and Chrome also.

```html
<img src="1.png" width="30">
<img src="2.png" width="30">
<img src="3.png" width="30">
<img src="4.png" width="30">
<img src="5.png" width="30">
<img src="6.png" width="30">
<img src="7.png" width="30">
<img src="8.png" width="30">
<img src="9.png" width="30">
<img src="10.png" width="30">
<img src="11.png" width="30">
<img src="12.png" width="30">
<img src="13.png" width="30">
<img src="14.png" width="30">
<img src="15.png" width="30">
<img src="16.png" width="30">
<img src="17.png" width="30">
<img src="18.png" width="30">
<img src="19.png" width="30">
<img src="20.png" width="30">
<img src="21.png" width="30">
<img src="22.png" width="30">
<img src="23.png" width="30">
<img src="24.png" width="30">
<img src="25.png" width="30">
```
![screen shot 2017-10-09 at 5 52 38 pm](https://user-images.githubusercontent.com/833473/31342808-af37257a-ad1a-11e7-9c27-189e55ae7991.png)

**Comment by takluyver** [comment]
Took a bit longer than that for me, but I do eventually see it:

![screenshot from 2017-10-09 15-30-51](https://user-images.githubusercontent.com/327925/31343284-16160cf2-ad07-11e7-8e9a-ab1ce5a2f5a6.png)

**Comment by takluyver** [comment]
Refreshing the page and re-rendering the markdown a few times seems to mess it up further. I see it in both Firefox and Chromium.

My best guess is that when it's responding to a lot of requests arriving at almost the same time, the responses end up associated with the wrong requests. I don't think that's something Jupyter could be affecting, but maybe there's something I've not thought of.

@bdarnell have you ever seen something like the issue above?

**Comment by ebraminio** [comment]
Hmmm, I feel my notebook serves randomly wrong things, maybe because of new Apple file system? :) I should investigate it more

**Comment by ebraminio** [comment]
> Refreshing the page and re-rendering the markdown a few times seems to mess it up further. I see it in both Firefox and Chromium.

Oh great so I am not alone, thanks :) I think it has something to do with caches and etags, I should investigate the option of course.

**Comment by takluyver** [comment]
It's possible there are other issues, but I can now replicate the mixed up numbers on Linux, so that much is definitely not an Apple filesystem issue.

**Comment by ebraminio** [comment]
> so that much is definitely not an Apple filesystem issue.

Just said that sarcastically honestly :)

![screen shot 2017-10-09 at 6 44 07 pm](https://user-images.githubusercontent.com/833473/31345211-e0612e64-ad21-11e7-83d1-98d68a4e01f8.png)

Caching is not related but seems start time is.

**Comment by takluyver** [comment]
I'm pretty mystified on this one. @minrk does it make any sense to you?

**Comment by bdarnell** [comment]
> Caching is not related but seems start time is.

I think it may still be caching-related, despite the "cached: no" entries here. These images are ~128B, and each response includes ~538B of headers. The bad results still contain those headers; they're just missing the data. The times don't quite line up for this theory, though. Packet captures would be the best evidence of what's really going on. 

What is the server-side code here? Tornado's StaticFileHandler or something else? Is there any proxying going on? The screenshot in https://github.com/jupyter/jupyter/issues/292#issuecomment-335145823 shows 302 redirects that don't appear in the one in https://github.com/jupyter/jupyter/issues/292#issuecomment-335190675. How are those redirects being generated?

**Comment by takluyver** [comment]
We have an [AuthenticatedFileHandler subclass](https://github.com/jupyter/notebook/blob/12592ef3bb2192b46052fd0ab6463757e8b5a49d/notebook/base/handlers.py#L519) of StaticFileHandler that mixes in all of our inheritance stuff. It also seems to do things with caching and etag generation, for reasons I'm not quite sure of at the moment.

We redirect file access at `/notebook/` URLs (typically from relative URLs inside a notebook) to `/files/` URLs. The code doing that is [here](https://github.com/jupyter/notebook/blob/12592ef3bb2192b46052fd0ab6463757e8b5a49d/notebook/notebook/handlers.py#L36).

Looking at how many layers we've got around Tornado, I now suspect it's probably something in our code, but I still have no idea what.

**Comment by ebraminio** [comment]
> Tornado's StaticFileHandler or something else?

Default jupyter file server which is [FilesHandler](https://github.com/jupyter/jupyter_server/blob/dd4b052403cc0ce70dbde9bfc6c71d6b09e814ec/notebook/files/handlers.py), I wanted to fix [this issue](https://github.com/jupyter/jupyter_server/issues/5) (have a look at its links) which got no attention at all, so am familiar with the code a little I guess but nothing is touched for reproduce of this and I've sacrificed all of my installed kernels and extensions I had in order to help fix of this :)

Anyway, does [FilesHandler](https://github.com/jupyter/jupyter_server/blob/dd4b052403cc0ce70dbde9bfc6c71d6b09e814ec/notebook/files/handlers.py) works race-free? For some reason I felt its logic is fishy when I studied it before, maybe because it doesn't use coroutines like tornado's [StaticFileHandler](https://github.com/tornadoweb/tornado/blob/59d80a6219d605a8a1da4c64deb8d4246d8fe174/tornado/web.py#L2372) or I don't know.

**Comment by bdarnell** [comment]
FilesHandler looks fine to me - no reason to make it a coroutine unless `contents_manager` were also changed to have an asynchronous interface.

You should be able to use `contents_manager` in a subclass of `StaticFileHandler` by overriding `get_content` and related methods (see [subclassing notes](http://www.tornadoweb.org/en/stable/web.html#tornado.web.StaticFileHandler)).

**Comment by ebraminio** [comment]
Hmmm, on my tests, specifically on Safari, sometimes if I refresh a notebook as above, redirecting is also can go wrong and sometimes an unrelated file is opened instead, the same effect thing is not available on other browsers however.

**Comment by minrk** [comment]
I think I saw this last week, but switching browsers from Safari to Chrome seemed to fix it, so I assumed it had been caused by the Safari 11 update that shipped a few days prior. Interestingly enough for me, it appeared to be *truly random* Handlers that happened to be active at the time. Refreshing the notebook page would occasionally display APIHandler responses, which are not StaticFileHandler subclasses.

On refreshing a few times, I had all of the following apparently replace the page response:

- /api/contents/:path (APIHandler)
- /api/sessions/ (APIHandler)
- /static/...notebook.min.css (served by FileFindHandler a lighter subclass of StaticFileHandler)

It appeared to be a roulette situation.

I haven't been able to reproduce reliably enough to track it down, though.

**Comment by minrk** [comment]
I managed to reproduce it reliably, and `git bisect` suggests that it is caused by #2656, switching to AuthenticatedFileHandler. So we are doing something strange there. I'll dig in and see if I can figure out what we have done.

**Comment by minrk** [comment]
Figured it out. The way AuthenticatedFilesHandler was being called involved mixing Handler instances in a not-entirely-safe way. I've switched how the files handler is registered so that only the CM's handler is registered and fully initialized, rather than trying to handoff from one handler to another.

**Comment by ebraminio** [comment]
This works just great, thank you much!

**Comment by takluyver** [comment]
Thanks for making a reproducible example to demonstrate the bug!
