### ISSUE TITLE
custom.css file location

### ISSUE THREAD

**Issue by p2ya** [jupyter/jupyter#295]
I am trying to add page break to notebook by setting custom.css file and adding a markdown with pagebreak as always.

1- I couldnt find a custom/custom.css file under .jupyter folder
2- I created folder and file and restarted but it didn's work
3- I searched for any other custom.css files and found some under static folder and made changes there but they didnt work as well

I really appreciate to know where I can find the original file (I am using Conda)
And how to edit and test to make it work.

**Comment by Doragd** [comment]
For Jupyter Notebook 5.5.0
custom.css has been moved to `\Anaconda3\Lib\site-packages\notebook\static\custom`

**Comment by scottlittle** [comment]
To find your `site-packages`: 
```
from distutils.sysconfig import get_python_lib
print(get_python_lib())
```

**Comment by AstridIt** [comment]
> 对于 Jupyter 笔记本 5.5.0 自定义.css已移至`\Anaconda3\Lib\site-packages\notebook\static\custom`

but i cant find  '\static\custom'

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. If you have an issue with https://github.com/jupyter/notebook, please report it over there.

Thanks everyone and happy hacking! :bowtie:
