### ISSUE TITLE
Collision of multiple cairo generated SVGs

### ISSUE THREAD

**Issue by ebraminio** [jupyter/jupyter#298]
Cairo generated SVGs with use of xlink:href will collide when used on used on the same page. I thought first it should be fixed from python-igraph but now that I see igraph just uses cairo in inside, I thought it maybe fixed from jupyter side also.

Possible fixes could be use base64 encoded SVGs or using iframes for separating them (or manual fiddling with output SVG ids are prepending some unique random letters?) in order to avoid the issue. (or suggesting python-igraph to have PNG output instead?)

The particular issue, reported first on https://github.com/igraph/python-igraph/issues/145 is as following:

----

Steps to reproduce:
1. Install latest release of igraph (python-igraph-0.7.1.post6) on python2 and open a jupyter notebook (pip install jupyter), open `jupyter notebook`, create a notebook.
2. Add these line on separate cells:
```python
import igraph as ig
ig.plot(ig.Graph.Full(3), vertex_label=['a', 'b', 'c'], bbox=(100, 100))
ig.plot(ig.Graph.Full(6), vertex_label=range(1, 7), bbox=(100, 100))
```
![screen shot 2017-11-09 at 2 26 36 pm](https://user-images.githubusercontent.com/833473/32602079-07049646-c55a-11e7-8de9-0c5af06a55a4.png)

Actual:
As can be seen on the screenshot, second graph on the page is messed up. As the both are SVGs they had some interference it seems.

Expected:
Each should drawn separately and correctly.

**Comment by takluyver** [comment]
I think the answer is to put the SVGs in iframes. We had a similar issue with SVG plots from IRkernel. I've made a comment on the igraph issue about how to do this.

**Comment by ebraminio** [comment]
Great. Thanks

**Comment by ebraminio** [comment]
This also could be done with base64 encoded `<img src="">`, run this on a page:

```javascript
document.body.innerHTML = `
<img src="data:image/svg+xml,${'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 400 100"><rect id="A" x="100" y="20" width="50" height="50" fill="#29e" /><use xlink:href="#A" x="150" y="10" /></svg>'.replace(/"/g, "&quot;")}">
<img src="data:image/svg+xml,${'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 400 100"><rect id="A" x="100" y="20" width="50" height="50" fill="#a9e" /><use xlink:href="#A" x="150" y="10" /></svg>'.replace(/"/g, "&quot;")}">
`;
```

iframes are hard to embed and publish I guess and removed by online ipynb html viewers I guess, maybe this is worth to do?

**Comment by ebraminio** [comment]
Also I believe this is good enough to be default (non-isolate) or at least replaced with current isolate (or as a separate option?)

**Comment by tacaswell** [comment]
There was a similar issue with Matplotlib a while ago and we added salt to the ids in the svg to avoid the collision.

**Comment by ebraminio** [comment]
Thanks, https://github.com/matplotlib/matplotlib/blob/477c1dcbe1a6aaed57d2e4b7210b47a6e8d4d73d/lib/matplotlib/backends/backend_svg.py#L317 this looks a little heavy to do it seems.

I believe base64 encoding the svg in img tags can be a better solution to avoid this once and for all.
