### ISSUE TITLE
get_ipython seems not defined when ran from external file on interactive widget

### ISSUE THREAD

**Issue by ebraminio** [jupyter/jupyter#299]
Steps to reproduce:
1. Install python-igraph from pip and put this on a cell
```python
import igraph as ig
from ipywidgets import interact

@interact(n=(0, 10))
def interactive(n):
    return ig.utils._is_running_in_ipython()
```
2. Scroll the widget

Expected:
Always True

Actual:
It becomes False after first scroll

Filed after https://github.com/igraph/python-igraph/issues/149

Here is source of `_is_running_in_ipython`, https://github.com/igraph/python-igraph/blob/17df5c301a952e4894db4e4a8963d85527fdc860/igraph/utils.py#L38-L47 maybe that should be fixed instead?

**Comment by takluyver** [comment]
I think we inject it into the builtins when running a cell, but not when running a widget callback. This code might be more robust:

```python
try:
    from IPython import get_ipython
    return get_ipython() is not None
except ImportError:
    return False
```

**Comment by ebraminio** [comment]
Thanks again @takluyver, if no further action is planned for jupyter, feel free to just close this.

**Comment by takluyver** [comment]
Thanks!
