### ISSUE TITLE
Question : autocompletion/formatting in simple python file

### ISSUE THREAD

**Issue by StephaneKazmierczak** [jupyter/jupyter#300]
Maybe I am missing something, but is there a way to have autocompletion and code formatting outside of a notebook, while editing a simple python file. I am in the situation where I am working in someone notebook which has a python file included in the notebook to bring some functions. Switching from the notebook to the python script I am losing most of the goodies of the IDE, even after selecting language > python from the menu. I am using vim to edit the python file for now but it would be much nicer if it would work also in jupyter.

**Comment by takluyver** [comment]
At present, no - we've avoided building IDE/advanced editor features, because there are so many projects that already do those things much better, and have invested masses of effort polishing them. I think Jupyterlab is slated to bring some of those features, though.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. 

Thanks everyone and happy hacking! :bowtie:
