### ISSUE TITLE
"Missing field in JSON data: notebook.path"

### ISSUE THREAD

**Issue by drevicko** [jupyter/jupyter#301]
I experienced the above jupyter server error after restarting my client computer+browser. I had saved the notebook just before restarting the computer (is may be possible that the save process was interrupted?).  I access the notebook server over an ssh tunnel, and the notebook server itself was not restarted. Here's a snippet from the server log:

```
...
[I 09:20:01.017 NotebookApp] Saving file at /BMI/Read AU BMI Stats.ipynb
[I 09:20:01.317 NotebookApp] Saving script /BMI/Read AU BMI Stats.py
[W 09:58:16.160 NotebookApp] Missing field in JSON data: notebook.path
[W 09:58:16.161 NotebookApp] 400 POST /api/sessions (::1) 1.72ms referer=http://localhost:8887/notebooks/BMI/Read%20AU%20BMI%20Stats.ipynb
...
```

Anyway, when I copied the notebook file to another computer and run jupyter, it worked fine. Likewise, after restarting jupyter, it works fine. Since the problem didn't persist (and I'm not sure I can replicate it) you may wish to just close this issue, but I thought I'd bring it to your attention and for future reference.

I'm using jupyter 4.0.6 installed via anaconda (conda 4.3.30). The notebook runs python 3.5.4 fwiw.

**Comment by takluyver** [comment]
I'm not quite sure how that came about. You might want to `conda update notebook` to get a newer version, though.

**Comment by drevicko** [comment]
Yeah, its rather odd. I guess something strange happened with js library versions or something? If it got confused and saved with an older format? 

If the server was lagging (which it does at times) when I saved the notebook, the tail of the transaction to save it may have got cut off by firefox quitting for the local shutdown? Some sort of race condition going on? 

Anyway, it's a pretty rare behaviour (only other place I found the error was an old issue in the [emacs notebook client](https://github.com/millejoh/emacs-ipython-notebook/issues/195)).

I'll update conda's notebook as you suggest.

**Comment by takluyver** [comment]
I think that error is coming from [creating a session](https://github.com/jupyter/notebook/blob/4.0.6/notebook/services/sessions/handlers.py#L43), not from saving the notebook. A session is the link between a notebook file and a kernel. It might be that the Javascript version is out of sync with the server, though I'm not really sure how that could happen.

**Comment by drevicko** [comment]
Ah, ok. I didn't think to try a different browser... would have presumably worked. 

I'm running notebooks on several servers, and they may have different versions (another I've been using recently has 4.3.0), so ff may have cached one from a different server (though they do run on different and consistent ports). It could explain it. 

Suggests that a version check of js scripts on session start isn't a bad idea, but I guess it's not such a common situation.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
