### ISSUE TITLE
Unicode Bug during Uploading File(s)

### ISSUE THREAD

**Issue by 8rV1n** [jupyter/jupyter#303]
This is my jupyter notebook version information:
Server Information:
You are using Jupyter notebook.
```
The version of the notebook server is: 5.2.2
The server is running on this version of Python:
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
```
Current Kernel Information:
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
```   

---------   
This is the bug description:  
When I upload a file to any of my working directory with files owning an unicode name, the bug shows itself.  
Filenames such as `测试`,`123测试`,`测试123` are all failed to upload.  
The traceback in the browser consol output this:  
```
Uncaught (in promise) Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1511, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/handlers.py", line 221, in put
    exists = yield gen.maybe_future(self.contents_manager.file_exists(path))
  File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 195, in file_exists
    return os.path.isfile(os_path)
  File "/usr/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 58-59: ordinal not in range(128)


    at wrap_ajax_error (utils.js:765)
    at Object.settings.error (utils.js:821)
    at l (jquery.min.js:4)
    at Object.fireWith [as rejectWith] (jquery.min.js:4)
    at k (jquery.min.js:6)
    at XMLHttpRequest.<anonymous> (jquery.min.js:6)
```

**Comment by takluyver** [comment]
What platform are you on, and what does running this Python code give you:

```python
import sys
sys.getfilesystemencoding()
```

**Comment by ArvinSiChuan** [comment]
Im using the Ubuntu 16.04 and the output is `'ascii'`.    
But I checked the system env `LANG` and it prints `en_US.UTF-8`.
By the way, the notebook Im using is in fact a jupyterhub version.

**Comment by ArvinSiChuan** [comment]
I found the reason why this happened.  
The notebook in Jupyterhub is not like the single Jupyter notebook, it will not pass some important system env vars (such as `LANG`)to the notebook unless configure the `keep_env` option.  
So the notebook in jupyterhub recognized the system file encoding to be `ascii`.  
After configuring the `keep_env` option, I tested the uploading again and it works.

**Comment by takluyver** [comment]
Thanks for debugging that.

We may be able to improve either Jupyterhub or the notebook itself to handle this kind of situation better. @minrk, any thoughts on which bit it might be best to change? On the notebook side, we could disbelieve systems which claim to have an ascii-only filesystem and use UTF-8 instead. Or in Jupyterhub, maybe it could do something smarter with the locale.

**Comment by minrk** [comment]
JupyterHub shouldn't be discarding locale info. `LANG` and `LC_ALL` are both in the default `env_keep` list for this reason. Perhaps this was overridden in config to remove them initially?

I'm certainly tempted to use utf-8 whenever the environment claims ascii, but I'd be concerned about any potential repercussions.

**Comment by ArvinSiChuan** [comment]
@minrk I wonder that the system level env(`LANG` or something) should never be discarded even if I override the option?

**Comment by minrk** [comment]
@ArvinSiChuan indeed, there should probably be some that are inherited. But it you want to *add* environment variables to keep, use `env_keep.append('...')` instead of `env_keep = ...`, which adds to the default list, instead of replacing it.

**Comment by ArvinSiChuan** [comment]
@minrk You are right we can use `append('...')` to avoid the override situation. I configured the conf.py file before reading the auto-generated template.py carefully and I thought there propably the hub should inherit all system env vars by conventions in my mind. I think we should add this to the documentations or Q&A, is this reasonable?

**Comment by minrk** [comment]
>I thought there propably the hub should inherit all system env vars by conventions in my mind

Indeed, this is true in several. The one exception is cases like JupyterHub, where a system is launching processes in different environments on behalf of other users, such as systemd, jupyterhub. In those cases, there could be lots of environment variables affecting the parent environment such as credentials and other things, few, if any, of which should be inherited by the spawned environments. Instead, only the bare default environment is used.

> I think we should add this to the documentations or Q&A, is this reasonable?

Yes, please do.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. If there's still something to document, sounds like it should be done over on https://github.com/jupyterhub/jupyterhub

Thanks everyone and happy hacking! :bowtie:
