### ISSUE TITLE
Add a floating "console" cell

### ISSUE THREAD

**Issue by bshahsavari** [jupyter/jupyter#304]
Having a console that always stays in the same position can make checking and debugging much easier. Spyder, MATLAB and many other IDE's have this feature and it would be great if this can be added to Jupyter notebook too. With current interface even a simple size checking requires creating a new cell and deleting it, or moving across the notebook to get to a cell that is created for testing the code.

**Comment by takluyver** [comment]
Have a look at the [Scratchpad extension](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/scratchpad/README.html).
