### ISSUE TITLE
can't upgrade from 4.4 in Mac OS X

### ISSUE THREAD

**Issue by mikkokotila** [jupyter/jupyter#307]
I have pip 9 and am following every instruction I found online about the matter, but I'm stuck with 4.4 when I do: 

`jupyter --version`

If I do: 

`sudo pip3 install -U jupyter`

It says "requirement already satisfied" 

Any advice how to overcome this? 
  
to add > when I do a clean environment and then pip install directly from the master, I still get 4.4. 

When I do:

`pip freeze`

I get: 

jupyter==1.1.0
jupyter-client==5.2.1
jupyter-console==5.2.0
jupyter-core==4.4.0
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.2.2

So is it just that I'm confused with the versions, and 4.4. is the most current for the core? I'm trying to overcome this age old problem https://github.com/jupyter/notebook/issues/2364 as in the version I'm having this is still happening.

**Comment by Carreau** [comment]
`jupyter --version` does not give you the version of the Jupyter package but of Jupyter-core. 

The `jupyter` package is [only available as version 1.0.0](https://pypi.python.org/pypi/jupyter) (not even sure how you can get `1.1.0` with pip freeze). It is a meta-package that has no code, it will likely never be updated. You have to specify which sub package to update. Notebook, nbconvert,  nbformat, jupyter-core....

You likely want to update `notebook`.

Do **not** use sudo with pip. It is likely to screw up your system.

**Comment by mikkokotila** [comment]
It looks like my notebook is alraedy up-to-date.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
