### ISSUE TITLE
Notebook dying too often when trying to load huge data.

### ISSUE THREAD

**Issue by Anirudh257** [jupyter/jupyter#316]
I am following the tutorial on [urban sound extraction](http://aqibsaeed.github.io/2016-09-03-urban-sound-classification-part-1/ ). I am trying to extract sound from the urban sound dataset. Everything works normally till I pass sound_names[ size: 10], raw_sounds[10*88200] to the plot_waves function as this:
 `plot_waves(sound_names,raw_sounds)`

After some heavy amount of online search, I found that decreasing the size of the input array would help. But, I tried passing raw_sounds[0][0: 40](only a sub array of size 40) to the plot_waves function and the kernel continues dying. After ruminaging on the Internet for many days, I am unable to find a possible solution for the same. 

The notebook can be found here:  [urban sound dataset](https://github.com/Anirudh257/Audio-files-extraction/blob/master/Audio%20extraction%20of%20urban%20sound%20dataset.ipynb).
The problematic cell is numbered 10.

Specifications:
Anaconda: conda 4.3.30
Python: 2.7
OS: Linux 64 bit

**Comment by takluyver** [comment]
When it dies, is there any error message in the terminal where you launched the notebook?

**Comment by Anirudh257** [comment]
Thanks for replying, @takluyver . This is the message on the terminal:

![image](https://user-images.githubusercontent.com/16001446/35374712-1bbc37d6-01ca-11e8-95e8-4419c4d0dba1.png)

And this is the message displayed on the kernel.

![image](https://user-images.githubusercontent.com/16001446/35374757-474a4578-01ca-11e8-8fd0-67ead805cc0d.png)

**Comment by takluyver** [comment]
No obvious clues there, unfortunately.

**Comment by mappedinn** [comment]
do you think that there a max RAM usage is set?

**Comment by Anirudh257** [comment]
I am not sure @mappedinn but it looks plausible. I am using the Colab which solves the issues. :)

**Comment by mappedinn** [comment]
@Anirudh257 I found out the issue. I was using pandas 0.20.0. With pandas 0.23.0 it worked perfectly.

**Comment by Anirudh257** [comment]
Thanks @mappedinn I will do that.
