### ISSUE TITLE
Test with Tornado 5.0b1

### ISSUE THREAD

**Issue by bdarnell** [jupyter/jupyter#317]
(I'm not sure where to file this in the jupyter family of projects; @minrk please route appropriately)

Tornado 5.0 is currently in beta, and I'm filing issues with prominent
users of Tornado to give them a chance to test it before release and
provide feedback on the changes and make adjustments as necessary. You
can install it with `pip install --pre tornado==5.0b1`. I expect to
release the final version of Tornado 5.0 in early March, about a month
away.

Full release notes are
[here](http://www.tornadoweb.org/en/latest/releases/v5.0.0.html). The
major change is that the `IOLoop` is now always backed by `asyncio` on
Python 3, which leads to various subtle changes at runtime but is
mostly compatible with previous versions. A more superficial but
source-incompatible change is that the `io_loop` argument to many
functions in Tornado has been removed and `IOLoop.current()` must be
used instead.

If you've already tested with Tornado 5.0b1 (or temporarily pinned
your dependency to 4.x so you can postpone dealing with this), feel
free to close this issue.

**Comment by minrk** [comment]
@bdarnell thanks! We run most of our tests with `--pre`, and have caught and fixed the few minor changes needed, which should already be in releases of current packages. The main thing we need to work with tornado 5 is to *also* use the pyzmq 17 beta, which greatly improves support for tornado + asyncio. What do you think is your timeline for tornado 5? I want to make sure I'm ready for that with pyzmq.

**Comment by bdarnell** [comment]
I'm planning to release Tornado 5 in early March.

**Comment by bdarnell** [comment]
I see this issue is still open. Is everything ready on your side? I'm planning to release Tornado 5.0 in the next week.

**Comment by takluyver** [comment]
Thanks for checking. AFAIK it should be working now. We've certainly fixed various issues, and Min has released pyzmq 17.

@minrk are you aware of any of our packages which will need new releases to get the compatibility work out? A quick look at the changelogs for notebook and ipykernel suggest that we have done releases since the compatibility changes.

**Comment by minrk** [comment]
I believe current releases of all of our repos are compatible with tornado 5. I've been living on master of tornado for a while without issues. I did [one last PR](https://github.com/jupyter/notebook/pull/3398) to make sure the notebook tests are running with tornado 5 and found a few things I missed in the tests themselves, but the fixes for the actual package have been released. Closing.
