### ISSUE TITLE
Endpoint documentation?

### ISSUE THREAD

**Issue by petergarbers** [jupyter/jupyter#318]
I've noticed that there is this endpoint `/api/nbconvert` (source: https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API). However I cannot find any specifications on how to specify which file and format to run `nbconvert` on.

I have tried many variations that all give the same response:

```
curl --request GET \
  --url 'http://localhost:8888/api/nbconvert?path=TestMongoDB.ipynb%3Fdownload%3D1&format=text%2Fhtml' \
  --header 'authorization: token xxxxxxxxxxxxxxxxxxxxxxxx' \
  --cookie 'username-localhost-8888=%222%7C1%3A0%7C10%3A1517534146%7C23%3Ausername-localhost-8888%7C44%3xxxxxxxxxxxxxxxxxxx%3D%7Cxxxxxxxxxxxxxxxxxxxxxxxxxx%22; _xsrf=2%7Cxxxxxxxxxxxxxxxxxxxxxxx%7C1517447429' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   446  100   446    0     0  44066      0 --:--:-- --:--:-- --:--:-- 44600
{
  "custom": {
    "output_mimetype": ""
  },
  "html": {
    "output_mimetype": "text/html"
  },
  "slides": {
    "output_mimetype": "text/html"
  },
  "latex": {
    "output_mimetype": "text/latex"
  },
  "pdf": {
    "output_mimetype": "text/latex"
  },
  "markdown": {
    "output_mimetype": "text/markdown"
  },
  "python": {
    "output_mimetype": "text/x-python"
  },
  "rst": {
    "output_mimetype": "text/restructuredtext"
  },
  "notebook": {
    "output_mimetype": "application/json"
  },
  "script": {
    "output_mimetype": ""
  }
}
```

Could anyone offer some guidance? I will update the docs to reflect how this works

**Comment by Carreau** [comment]
IIRC this API is still in progress. If you are at the command line, any reason not to use jupyter-nbconvert directly ?

cc @mpacer who might be better suited to point you in the right direction.

(Side note, you may want to change your credentials/token now that have been exposed ?)

**Comment by petergarbers** [comment]
Hi @Carreau 
Thanks for the response. 

Our goal is to expose notebooks through slack. 

The reason we would prefer to interface with it through an API is portability, running `jupyter nbconvert ...` requires us to be on the machine which is running the notebook, meaning our slack bot also needs to be running on that same machine. I'd prefer to not marry the two services, if possible.

Regarding the token, that was from a request I made yesterday and has long since been changed.

**Comment by Carreau** [comment]
> Our goal is to expose notebooks through slack.
> 
> The reason we would prefer to interface with it through an API is portability, running jupyter nbconvert ... requires us to be on the machine which is running the notebook, meaning our slack bot also needs to be running on that same machine. I'd prefer to not marry the two services, if possible.

Ok, great. Completely make sens, just making sure. One of the reason we started to create this API was for some similar use case. 

Btw, the wiki is community maintained, so might not be super-up-to-date. It seem like recent notebooks server now have a POST method (that takes a full ntoebook as argument), and a GET with `/nbconvert/<format>/<path>`. The second one might be what you are looking for.

**Comment by mpacer** [comment]
I’ll have more details about this in a bit, but don’t use the POST handler
as we’ve been talking about deprecating that in favor of a better designed
endpoint that can accept a json configuration object (
https://github.com/jupyter/notebook/pull/2413) but partly what’s holding
that PR up is figuring out how to handle the api documentation when there
are more endpoints than just those in the services module (which also has a
separate, undocumented nbconvert endpoint).

Sorry that this is so complicated, but I’ll definitely be thinking about
your use case when continuing my work on the endpoints.

**Comment by petergarbers** [comment]
@Carreau that endpoint actually works. Would you like for me to update the swagger documentation?

@mpacer thank you for weighing in. Let me know if there is anything I can do to assist!

**Comment by Carreau** [comment]
> @Carreau that endpoint actually works. Would you like for me to update the swagger documentation?

Any documentation update is always appreciated. The wiki is just open, otherwise feel free to send a PR.

Let us know also if the API is too complex for your use case and how we can improve it.

**Comment by mpacer** [comment]
Actually wait on the swagger changes for a little bit… the docs are currently not technically up-to-spec and I should remove the swagger stuff from my big nbconvert endpoint pr so that you can base it on that

**Comment by mpacer** [comment]
Apparently, we had already merged the swagger changes back in October (https://github.com/jupyter/notebook/commit/b0205c4b78829f1e51b385bd62d8cff64d42a423), so go right ahead!
