### ISSUE TITLE
python3 kernel not starting offline

### ISSUE THREAD

**Issue by jmriddell** [jupyter/jupyter#319]
When I try to open a notebook while not connected to the internet it just gets stuck and can't interact anymore with the jupyter instance, not even ctrl-c to interrupt. There is no problem if I open a md or py file, just when starting the kernel.

When offline:
```
C:\Users\*****>jupyter kernel
[KernelApp] Starting kernel 'python3'
```
until killing process

When online:
```
C:\Users\*****>jupyter kernel
[KernelApp] Starting kernel 'python3'
[KernelApp] Connection file: C:\Users\*****\AppData\Roaming\jupyter\runtime\kernel-572543c6-ec83-4232-a5ca-28c0f41cb953.json
[KernelApp] To connect a client: --existing kernel-572543c6-ec83-4232-a5ca-28c0f41cb953.json
```

On Windows 7 64 bit, Python 3.6 64 bit, ipython and jupyter installed via pip

Edit:
It's just a starting problem, if I open a notebook and then disconnect from internet the kernel works fine (can import modules and evaluate results)

**Comment by takluyver** [comment]
Do you have any security software? Sometimes that causes issues.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
