### ISSUE TITLE
Add a Try Jupyter! section to the docs

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter#32]
As the docs are being restructured for 4.0, it may be helpful for novices that land on the docs via google or other searches to have a section that previews Jupyter without installing (like a developer would).

Perhaps just prior to Installation in Table of Contents, add a brief section: 

Try Jupyter! (No installation necessary)
----------------------------------------------------

In a hurry to get started with Jupyter? Do you wish to try Jupyter before installing it to your system?

We want to share Jupyter with you, and we hope you will give it a try on our website https://try.jupyter.org

![tryjupyter](https://cloud.githubusercontent.com/assets/2680980/9705225/9e5cf5b6-5472-11e5-9e53-beb7fe5318b5.gif)

If you wish to try Jupyter with your own notebook, click the upload button on the upper right to upload your `ipynb` notebook file.

Thanks to @jhamrick for the licecap recommendation. We've been adding gifs to nbgrader docs, and I think it helps with reinforcing the written docs.

**Comment by ellisonbg** [comment]
I think this is a great idea to have a "Try Jupyter" listed right before the Installation section of the main docs.
