### ISSUE TITLE
How can I turn cmd to powershell?

### ISSUE THREAD

**Issue by hjkqqqadjh** [jupyter/jupyter#321]
jupyter notebook use cmd to run shell command in win10, but powershell is more powerful. How can I replace it by powershell?

**Comment by jakern** [comment]
You can set it up with using magic commands. [Details here.](https://stackoverflow.com/questions/19644926/configure-ipython-to-use-powershell-instead-of-cmd)

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
