### ISSUE TITLE
tab command for unicode characters

### ISSUE THREAD

**Issue by gvdr** [jupyter/jupyter#327]
Some languages (Julia is one, there may be others) allow the user to write unicode characters via a tab completion command (i.e., you would write something like `\alpha` and then press the Tab key).

This works in jupyter notebooks, but not in JupyterLab as the Tab is reserved.

Is there a workaround?

**Comment by Carreau** [comment]
That does seem to work here: 

![alpha](https://user-images.githubusercontent.com/335567/36917798-a282be44-1e0c-11e8-86c5-7b2c37ec0b41.gif)


Though the back-completions does not, look at classic notebook:

where \α tab should expand to \alpha
![alpha_c](https://user-images.githubusercontent.com/335567/36917887-e79beadc-1e0c-11e8-818e-4e5581f6033f.gif)

but does not in lab:

![alpha_c_lab](https://user-images.githubusercontent.com/335567/36917924-0859f458-1e0d-11e8-83e2-0522a3861427.gif)

**Comment by Carreau** [comment]
I spoke too soon, my version is out of date. It seem to work on released version in both case. 
Or did I misunderstood what you were looking for ?

**Comment by gvdr** [comment]
That is exactly what I'm looking for. Yet, it does not work on my browsers (Firefox developer edition and Chrome).

I'm using Jupyter-lab Beta Release Series Version 0.31.5 and Julia 0.6.2

**Comment by gvdr** [comment]
P.S. If from the same browser, same jupyterlab session, I launch a Classic Notebook the tab transformation works.

**Comment by ian-r-rose** [comment]
@gvdr The fix for this is in JupyterLab v0.31.10.

**Comment by gvdr** [comment]
Oh, silly me! Sorry!

**Comment by ian-r-rose** [comment]
No worries, glad you got it working.

**Comment by petar-andrejic** [comment]
This doesn't work in Markdown cells however. It would be great if it did

**Comment by fredguth** [comment]
Is there a list of the unicode chars that accept tab command?  I try \nabla and it does not work.

**Comment by we-taper** [comment]
@fredguth Looks like [Python 3 restricts variable names to unicode characters that represent characters in written languages.](https://python-3-for-scientists.readthedocs.io/en/latest/python3_features.html#unicode-variable-names).
