### ISSUE TITLE
Unable to change jupyter kernel

### ISSUE THREAD

**Issue by Mark531** [jupyter/jupyter#331]
Hello,

Jupyter starts with a wrong kernel (named "Python3") and I can't manage to change it. I want to use Anaconda's kernel with which many libs are installed by default.

So, I tried to add a new kernel:
python -m ipykernel install --user --name root --display-name "py3.5 (Anaconda)"

And now I see it appear:
>jupyter kernelspec list
Available kernels:
  python3    c:\users\i328807\appdata\local\continuum\anaconda3\lib\site-packages\ipykernel\resources
  root       C:\Users\I328807\AppData\Roaming\jupyter\kernels\root

But when I run jupyter notebook, only the old kernel ("Python3") can be chosen.

I've also found out a strange thing, in C:\Users\I328807\AppData\Roaming\jupyter\kernels\root, the kernel.json fine was properly specified, but in c:\users\i328807\appdata\local\continuum\anaconda3\lib\site-packages\ipykernel\resources, this file was missing. So, where does jupyter look for the path to python.exe then?

Thanks in advance,
Mark
PS: I use Windows 10 (64 bits), jupyter 4.1.0, Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]

**Comment by takluyver** [comment]
> ... but in c:\users\i328807\appdata\local\continuum\anaconda3\lib\site-packages\ipykernel\resources, this file was missing. So, where does jupyter look for the path to python.exe then?

That `ipykernel/resources` folder is a special fallback, and it will start the kernel with the same python.exe that Jupyter itself is running on. You can see what Python a kernel is running on by checking:

```python
import sys
sys.executable
```

I don't know why the kernelspec you added isn't showing up, though.

**Comment by Mark531** [comment]
sys.executable returns 'C:\\Users\\I328807\\AppData\\Local\\Continuum\\Anaconda3\\python.exe' so it's the right python.exe. It seems I have another issue then: https://github.com/conda/conda/issues/1753. But the kernel not appearing in jupyter is another one.

I also tried to remove the Python3 kernel manually:
jupyter kernelspec remove python3
But it had no effect, both kernels are listed when I call "jupyter kernelspec list".

**Comment by takluyver** [comment]
You can't remove the special case kernel except by uninstalling the
ipykernel package. It's meant to be a fallback that's always available.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
