### ISSUE TITLE
is available nbconvert rest api?

### ISSUE THREAD

**Issue by whitebluecloud** [jupyter/jupyter#335]
hi, I'm looking for nbconvert ipynb to python file with rest api.
so, I searched like '/api/nbconvert' from this link(https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API)
but, the api is not that I'm looking for..
is available nbconvert api with rest?? not CLI or LIB..

**Comment by takluyver** [comment]
Yes, if you have a notebook open in the web interface, look at the URL, and change `/notebooks/` to something like `/nbconvert/html/`.

**Comment by whitebluecloud** [comment]
@takluyver thanks a lot. I appreciate to your help :+1: :)
