### ISSUE TITLE
Possible to install extension without restarting notebook server?

### ISSUE THREAD

**Issue by porterde** [jupyter/jupyter#336]
I am running a Jupyter Hub instance on Kubernetes, where each logged in user gets their own Docker container instance running the Jupyter Notebook process. This is a nice sandbox environment for users to install Python packages and, if they get in to a mess, reset their environment by simply restarting their container from the image.

In this setup it does not appear possible for a user to install a new notebook extension or notebook server extension, as both require the notebook process to be restarted. Killing the notebook process stops the running container, and by the time the container restarts the new extension install is lost as it's running from the original image again. Obviously, extensions can be installed in Docker image during build, but I would like users to be able to install additional extensions themselves on demand.

Is there a way that I have missed of loading installed extensions without restarting the notebook process?

Hacky workarounds I am considering are a notebook server extension that effectively does and execv(...) to restart the process in place of the running one and hopefully this prevents the container exiting, or adding some custom script on container start to look in the user's persistent storage for a start script to run before running notebook process (and risk them getting in to a state where their notebook process never starts...).

**Comment by takluyver** [comment]
Javascript extensions should be able to load without restarting the server (you just need to enable them and then refresh the page), but server extensions do need a server restart.

**Comment by shivam1702** [comment]
I had to install `ipywidgets` and `widgetsnbextension`. 
I saw their documentations but found nothing about them being either JS or server extensions. 
@takluyver , is there any way to know which one they are?

After the install, I do get the following output though:
`Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK`

**Comment by flixr** [comment]
It seems this is still not possible with jupyterlab3 and revamped extensions...

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
