### ISSUE TITLE
jupyter has been blocked by antivirus 

### ISSUE THREAD

**Issue by zynabsmaan** [jupyter/jupyter#337]
I installed antivirus and I found that jupyter has been blocked I removed the antivirus but the jupyter still doesn't run and it gives me this message when I tried to open it from anaconda terminal 

Unable to create process using 'C:\Users\ADMIN\Anaconda3\envs\anaconda\python.exe C:\Users\ADMIN\Anaconda3\envs\anaconda\Scripts\jupyter-script.py notebook'

**Comment by simon1tan** [comment]
Could your antivirus had deleted something? Perhaps you should reinstall Anaconda

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
