### ISSUE TITLE
How to use different version of python3 in jupyter?

### ISSUE THREAD

**Issue by Haicang** [jupyter/jupyter#339]
Is it possible to use both python3.5 and python3.6 in jupyter without the manual change of config?

**Comment by daguito81** [comment]
You can create different environments with conda for example. And then install ipykernel on them and then you can switch between kernels in the notebook or when generating a new file. This let's you use different versions of anything

**Comment by Haicang** [comment]
> You can create different environments with conda for example. And then install ipykernel on them and then you can switch between kernels in the notebook or when generating a new file. This let's you use different versions of anything

Thank you so much! And I'll copy a link from [stackoverflow](https://stackoverflow.com/questions/39604271/conda-environments-not-showing-up-in-jupyter-notebook?rq=1), hoping it will help others.
