### ISSUE TITLE
fatal error in launcher jupyter

### ISSUE THREAD

**Issue by mrkardgar** [jupyter/jupyter#345]
hi 
i run jupyter notebook in cmd windows 7-x64 but i get this text
i use python 3.6.2
c:\windows\system32>jupyter notebook 

Fatal error in launcher: Unabble to create process using '""c:\program files\python36\python.exe"   "c:\Program Files\Python36\Scripsts\jupyter.exe"notebook'

**Comment by 1kastner** [comment]
did you try to remove and re-install it?

**Comment by ABHISHEK2F24** [comment]
Hi @mrkardgar 
I have the same issue. You just need to edit your environment variable 

-  go to windows start bar
-  search for **'environment variable'**
-  see path in system variable.
-  edit it like this : _**C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts\jupyter.exe**_
- That's it :-)

**Comment by mrkardgar** [comment]
thank's

‫‪Abhishek Kumar Maurya‬‏ <‪notifications@github.com‬‏> در تاریخ دوشنبه ۳
ژوئن ۲۰۱۹ ساعت ۱۲:۴۷ نوشت:‬
