### ISSUE TITLE
jupyter notebook Cannot upload file (>25 MB)

### ISSUE THREAD

**Issue by yuanjie-ai** [jupyter/jupyter#347]
jupyter notebook Cannot upload file (>25 MB)

**Comment by Jie-Yuan** [comment]
jupyter notebook Cannot upload file (>25 MB)
![image](https://user-images.githubusercontent.com/20265321/40902054-272ff20a-6805-11e8-99bd-ef4eae371723.png)
![image](https://user-images.githubusercontent.com/20265321/40902070-35a5ae4c-6805-11e8-94b9-14ed81cf0a40.png)

**Comment by manuhortet** [comment]
Isn't this the expected behavior? Couldn't you divide the file + the operations?

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. This was fixed in notebook 5.0 -see https://github.com/jupyter/notebook/pull/2162 and https://github.com/jupyter/notebook/issues/96

Thanks everyone and happy hacking! :bowtie:
