### ISSUE TITLE
R kernels from conda envs won't start from the root-env Jupyter notebook

### ISSUE THREAD

**Issue by kalenkovich** [jupyter/jupyter#353]
I have nb_conda_kernels installed in the root environment. When I open a notebook and select an R kernel from another environment, I get the following error: 

Rterm.exe - System Error: The program can't start because libopenblas.dll is missing from your computer. Try reinstalling the program to fix this problem.

![image](https://user-images.githubusercontent.com/9257050/42372417-d7a1fe02-811a-11e8-9e63-79b255e3fd74.png)

There is no problem however if I start Jupyter in the environment that has the R kernel. This is of course a reasonable workaround but it would be more convenient to be able to switch between the environments.

**Comment by gptshubham595** [comment]
solved?

**Comment by kalenkovich** [comment]
> put this two files inside zip in bin folder
> 
> and this will work
> 
> [bin.zip](https://github.com/jupyter/jupyter/files/6006126/bin.zip)
> 
> PS-Now this should be closed

Certainly copying library files from a zip file uploaded in a comment to a github issue is not a reasonable solution, is it? If anyone decides to go this way, please copy these libraries from the bin folder of the environment with an R kernel isntalled to the bin folder of your root environment - do not use the attached files.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. The kernelspec can have an environment field where you could make it match the paths of the environment where the R kernel is installed, so you could started it from you base environment. 

> Certainly copying library files from a zip file uploaded in a comment to a github issue is not a reasonable solution, is it?

agreed, indeed I'm going to go ahead and edit the previous comment to delete that file of unknown provenance.

Thanks everyone and happy hacking! :bowtie:

**Comment by ivanov** [comment]
for the record, the `dll` in question were `libopenblas.dll` and `libgfortran-5.dll`
