### ISSUE TITLE
Session id appearing in the url while making a call to kernal api

### ISSUE THREAD

**Issue by mak-aravind** [jupyter/jupyter#365]
When Jupiter tries to re-connect with kernal the URL been sent jupyter: 

WebSocket connection to 'wss://jupyter.sdp6-dev.csco.cloud/user/aravmuru/api/kernels/ff9c5ba6-aefb-4d07-8ba8-32c6a1c1edd1/channels?session_id=118d14ea4a234b7b9a8e575f9421de24' failed: Connection closed before receiving a handshake response

Don't we think this as a security vulnerabilty exposing the session id in the URL instead we should call api with POST verb rather a GET verb

**Comment by mak-aravind** [comment]
Can anyone please explain why we are sending the session_id for this call.

**Comment by ivanov** [comment]
Hey there @mak-aravind , I'm going through old issues and it seems to me that it makes sense to close this one, as it is quite stale. Sorry we never got to it - if this is still an issue, the report probably belongs to the https://github.com/jupyter-server/jupyter_server repository.

Thanks everyone and happy hacking! :bowtie:
