### ISSUE TITLE
When printing a line with f string the single quotes don't auto close and sometimes they close wrong

### ISSUE THREAD

**Issue by mathfour** [jupyter/jupyter#366]
I did a video to fully explain, as there are some weird edge cases. Here's a quick screenshot, as you have to [view the video over on YouTube](https://youtu.be/JP0QJVVl3k4).

![image](https://user-images.githubusercontent.com/7103316/44939271-8e837d80-ad49-11e8-9ea5-b4975b20b346.png)

Thanks, y'all!

**Comment by eseiver** [comment]
This bug is still happening for me in the 5.6.0 version of the Notebook server. I wouldn't mind it so much except that when I manually add the closing bracket with the conditions stated above, it attempts to auto-pair that one, so I have to then delete that extra trailing bracket.

**Comment by choldgraf** [comment]
Hmmm - I suspect (but am not positive) that this is actually an [ipython issue](https://github.com/ipython/ipython), so it might be more likely to be fixed w/ an issue in there? At least, I think that is the package that handles auto-completes etc.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one, as it is quite stale now. It does look like it was a codemirror issue after all, at least that was the resolution that the discussion in https://github.com/jupyterlab/jupyterlab/issues/5588 concluded, so a newer version of codemirror eventually fixed this.

Thanks everyone and happy hacking! :bowtie:
