### ISSUE TITLE
Numpy errors after editing jupyter_notebook_config.py (c.NotebookApp.notebook.dir)

### ISSUE THREAD

**Issue by rmrndr** [jupyter/jupyter#367]
After installing anaconda and the jupyter environment, I uncomment and edit `c.NotebookApp.notebook_dir` in the jupyter_notebook_confing.py file so when I launch jupyter notebook or jupyter lab I'm directly in my Python's working directory on my computer (`K:\\PWD\\`):

```Python
## The directory to use for notebooks and kernels.
c.NotebookApp.notebook_dir = 'K:\\PWD\\'
```

I've never had any issues doing this, never. However, 2 days ago, I created a new Python 3 Jupyter Notebook, import NumPy, Pandas and I got this error:

```Python
import numpy as np
import pandas as pd

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-59ab05e21164> in <module>()
      1 import numpy as np
----> 2 import pandas as pd

C:\Anaconda3\lib\site-packages\pandas\__init__.py in <module>()
     21 
     22 # numpy compat
---> 23 from pandas.compat.numpy import *
     24 
     25 try:

C:\Anaconda3\lib\site-packages\pandas\compat\numpy\__init__.py in <module>()
      8 
      9 # numpy versioning
---> 10 _np_version = np.__version__
     11 _nlv = LooseVersion(_np_version)
     12 _np_version_under1p10 = _nlv < LooseVersion('1.10')

AttributeError: module 'numpy' has no attribute '__version__'
```

### **It looks like there's an error with NumPy. No errors are returned when importing the library, however calling a NumPy functions returns an error:**

```Python
import numpy as np
np.zeros(5)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-36ec5cd547fe> in <module>()
      1 import numpy as np
----> 2 np.zeros(5)

AttributeError: module 'numpy' has no attribute 'zeros'
``` 

### **If I want to import another library, let's say matplotlib, another error is returned, again when calling NumPy:**

```Python
import matplotlib.pyplot as plt

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-a0d2faabd9e9> in <module>()
----> 1 import matplotlib.pyplot as plt

C:\Anaconda3\lib\site-packages\matplotlib\__init__.py in <module>()
    125 # cbook must import matplotlib only within function
    126 # definitions, so it is safe to import from it here.
--> 127 from . import cbook
    128 from matplotlib.cbook import (
    129     _backports, mplDeprecation, dedent, get_label, sanitize_sequence)

C:\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py in <module>()
   2638 
   2639 
-> 2640 class _StringFuncParser(object):
   2641     """
   2642     A class used to convert predefined strings into

C:\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py in _StringFuncParser()
   2650                                  lambda x: x,
   2651                                  True)
-> 2652     _funcs['quadratic'] = _FuncInfo(np.square,
   2653                                     np.sqrt,
   2654                                     True)

AttributeError: module 'numpy' has no attribute 'square'
```

### **If I import a base library (`math` for example), there is no issue:**
```Python
import math
math.sqrt(16)

4.0
```

### **If I try to import numpy and pandas in the console it works perfectly fine:**

```Python
import numpy as np

import pandas as pd

np.zeros(5)
Out[3]: array([0., 0., 0., 0., 0.])

pd.Series([1, 2, 3, 4, 5])
Out[4]: 
0    1
1    2
2    3
3    4
4    5
dtype: int64
```

### **If i comment back the `c.NotebookApp.notebook_dir` line in the jupyter_notebook_confing.py file, then the errors returned by numpy do not occur anymore in jupyter notebooks or jupyter lab:**

```Python
## The directory to use for notebooks and kernels.
#c.NotebookApp.notebook_dir = 'K:\\PWD\\'
```

```Python
import numpy as np

import pandas as pd

np.zeros(5)

array([0., 0., 0., 0., 0.])

pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64
```

It took me 2 days of uninstall/reinstall to figure out that the issues seems to be caused by specifying a custom directory for notebooks and kernels in the jupyter_notebook_config.py file. However, it's strange that the errors only started to happen 2 days ago since I specified a custom directory for my notebooks a long time ago and I never had such errors.

**Comment by constant5** [comment]
Have you tried updating your numpy? 

pip install --upgrade numpy

**Comment by rmrndr** [comment]
NumPy is up to date (`4.5.11-py36_0`). During my quest to find a solution I also downgraded NumPy and Pandas to try various version combinations with no luck.

**Comment by Aryarajula** [comment]
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-add23713a3e0> in <module>
----> 1 X_train = numpy.load('./Data/mnist/x_train.npy')
      2 X_test = numpy.load('./Data/mnist/x_test.npy')
      3 y_train = numpy.load('./Data/mnist/y_train.npy')
      4 y_test = numpy.load('./Data/mnist/y_test.npy')

F:\pro1\lib\site-packages\numpy\lib\npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    413         own_fid = False
    414     else:
--> 415         fid = open(os_fspath(file), "rb")
    416         own_fid = True
    417 

FileNotFoundError: [Errno 2] No such file or directory: './Data/mnist/x_train.npy'

**Comment by Jadamoureen** [comment]
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-5-69affd9d4321> in <module>
      1 import pandas as pd
----> 2 Test_df = pd.read_csv(r"/home/jada_moureen1/Desktop/panda/Test_Sheet1.csv")
      3 Test_df2 = pd.read_csv(r"data/Test_Sheet1.csv")
      4 print(pd.DataFrame.equals(Test_df, Test_df2))

**Comment by ekblessed** [comment]
this error show when i try to run my project
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-053d89089797> in <module>
----> 1 np.array(my_list)

NameError: name 'np' is not defined

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one as it is quite stale. The original error reported looks like a consequence of having either a file `numpy.py` or a directory `numpy` with a file `__init__.py` inside of it that caused "import numpy" to work, but not have any of the standard numpy things present (hence a missing `__version__` and `zeros`).

Thanks everyone and happy hacking! :bowtie:
