### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by funkybob** [jupyter/jupyter#368]
I tried to install jupyter using pipenv, and found the following dependencies conflict:

jupyter depends on widgetsnbextension~=3.3.0
jupyter depends on ipywidgets
ipywidgets 7.4.1 depends on widgetsnbextension~=3.4.0

If I pin ipywidgets to <7.4.0 I can get a successful install.

**Comment by minrk** [comment]
jupyter doesn't specify any version requirements on widgetsnbextension. Where do you see that? Maybe it's a different package?
