### ISSUE TITLE
install jupter by pip, find wrong version about ipython

### ISSUE THREAD

**Issue by AOtrans** [jupyter/jupyter#369]
I upgrade pip to 18. and when I run command 'pip install jupyter'. in default, it download ipython7.0. but only ipython5.x surpport python2.7. how can i fix this :)

**Comment by 1kastner** [comment]
You can install Python 3 next to Python 2. And you can have a Python 2 kernel in a Python 3 notebook.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Python 2 reached End of Life four years ago. 

Here's a poem I wrote to say goodbye to Python 2, when it was announced that Python 2.7 would be the last version of Python 2.

```
from __past__ import nostalgia

Goodbye old friend, dear Python2
A dozen years since I met you

It seems like only yesterday
print was a statement
range returned a list
and xrange was a thing

no stars or slashes in my def
life was simpler, unicode was...u"fun"
async await were waiting in the wings

Thanks for the memories, you were great
And in memoriam, after you're gone in 2020
I'll still fondly wear a shirt that says: 2.8
```

Thanks everyone and happy hacking! :bowtie:
