### ISSUE TITLE
Windows, Python 3.7 Jupyter Notebook: Cannot interrupt cell

### ISSUE THREAD

**Issue by mmatthe** [jupyter/jupyter#375]
On Windows with recent Jupyter installation (notebook 5.7.0, jupyter-core 4.4.0) and Python 3.7 a cell cannot be interrupted (the console says "Kernel interrupted") but actually it is not interrupted. The interruption works with Python 3.6. See also here: https://github.com/jupyter/jupyter_client/issues/387 

I'm reopening this issue here, as it seems over at the jupyter_client repo it migh thave slipped off.

**Comment by minrk** [comment]
This is fixed by jupyter-client 5.2.4
