### ISSUE TITLE
how to distinguish between the checkpoints of notebook and the checkpoints directory

### ISSUE THREAD

**Issue by antshuwen** [jupyter/jupyter#387]
Tensorflow will create the directory like "runs/1544414365/checkpoints". When I use the api "/api/contents/runs/1544414365/checkpoints" to get the sub directory, It only returns "[]" which is not the common format.

**Comment by antwsw** [comment]
@willingc

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
