### ISSUE TITLE
how to install jupyter and specify the ipython version

### ISSUE THREAD

**Issue by XufengXufengXufeng** [jupyter/jupyter#388]
My machine only has python 2.7 and I want to install jupyter with pip. 

When I use the command: python -m pip install jupyter, it fails because the ipython version should be 5.0 or less. The error continues appear even if I install ipython 5.0 first.

I have been researching the solutions, but no luck. Someone please help.

**Comment by XufengXufengXufeng** [comment]
It's a centos7 machine. I can't install python 3, as other apps on the machine depends on python 2.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
