### ISSUE TITLE
Hi my jupyter python3 version and terminal version is not matched

### ISSUE THREAD

**Issue by SlowMonk** [jupyter/jupyter#390]
my command channel's python version is python 3.6.7
but after I go to Jupyter notebook 
I print 

!python

it said 
Python 3.6.2 |Anaconda, Inc.| (default, Sep 22 2017, 02:03:08) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

How I make it match each other

**Comment by paulnice** [comment]
Hi Sangwon,

1. Why do you need it?
2. Can you please show the output of `which python` command?
3. What is you OS, OS version?
4. How do you run jupyter notebook?

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
