### ISSUE TITLE
Requesting help - To check whether JupyterHub is currently in use.

### ISSUE THREAD

**Issue by pr334** [jupyter/jupyter#395]
Hi, 
I'm currently working on automated script to check whether Jupyterhub (installed in AWS EMR) is in-use. The bash script will be installed on the master node of the cluster and trying to apply the below logic.

******
Logic:
******
IsActive = false
lstUsers = **<Fetch all current users>**
for each user in lstUsers:
       LstNotebook = **< fetch all notebooks opened by the user>**
       for each notebook in LstNotebook:
                   if **< Anycell in the notebook in execution state >:** 
                           IsActive = true
                           break
                   else if **<Completion time of any cell less than 5mins>:**
                          IsActive = true
                          break
**********************************
I'm trying to retreive all the <..> (highlighted in bold) using REST API calls. But I dunno how to use it.
I followed the steps in https://jupyterhub.readthedocs.io/en/latest/reference/rest.html,
 - Generated API token using openssl rand -hex 32
 - Added it to jupyterhub_config.py 

Then tried accessing, curl -XGET -s -k https://0.0.0.0:9443/hub/api/users -H "Authorization: token xxxxxxx" | jq . to get the user list. But I got 403 forbidden response.

Could anyone please guide how can I use these API Calls to achieve my above logic. Would be very helpful?

Thanks,
Praveen.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. 

Thanks everyone and happy hacking! :bowtie:
