### ISSUE TITLE
Enabling pylab causes jupyter to respond very slowly

### ISSUE THREAD

**Issue by yiwenlu66** [jupyter/jupyter#396]
Using `%pylab` magic in jupyter (without making any plots) makes subsequent command in jupyter to execute very slowly a while after the `%pylab` command is executed. Here is an example in jupyter console:

```
$ jupyter console
Jupyter console 6.0.0

Python 3.7.2 (default, Jan 13 2019, 12:50:01)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.



In [1]: %pylab
Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib

In [2]: # wait for about 1 minute and do nothing

In [3]: print('test')
/usr/local/lib/python3.7/site-packages/jupyter_console/ptshell.py:661: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
  warn('The kernel did not respond to an is_complete_request. '
test
```

The output above takes about 10 seconds to appear (for a `print` statement and for any other simple statement such as `pass`). The same phenomenon is observed in both jupyter notebook and jupyter qtconsole. Here is a screenshot from jupyter notebook (note the execution time of the third cell):

![image](https://user-images.githubusercontent.com/3724995/52553292-01774100-2e1e-11e9-9f47-e9d29018a9f0.png)

In particular, I notice that the kernel is idle for a few seconds after I tell jupyter to run the cell, and that the kernel stays busy for another few seconds after the output appears.

After some simple debugging, I seem to have located the function that causes this issue: `IPython.core.pylabtools.activate_matplotlib` (https://github.com/ipython/ipython/blob/512d47340c09d184e20811ca46aaa2f862bcbafe/IPython/core/pylabtools.py#L302). Here is a simple test:

```
$ jupyter console
Jupyter console 6.0.0

Python 3.7.2 (default, Jan 13 2019, 12:50:01)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.



In [1]: from IPython.core import pylabtools as pt; pt.activate_matplotlib('MacOSX')

In [2]: # wait for about 1 minute and do nothing

In [3]: print('test')
/usr/local/lib/python3.7/site-packages/jupyter_console/ptshell.py:661: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
  warn('The kernel did not respond to an is_complete_request. '
test
```

This does not seem to be an IPython issue, because when I replace `jupyter console` with `ipython` and execute exactly the same commands, everything works without any problem.

I am on Mac OS Mojave 10.14.3, and Python 3.7.2. Here is a list of my related packages:

```
$ pip3 freeze | grep 'jupyter\|matplotlib\|ipython'
ipython==7.2.0
ipython-doctester==0.3.0
ipython-genutils==0.2.0
ipython-tikzmagic==0.1.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
matplotlib==3.0.2
```

I am not sure whether this issue should belong to this repo, other jupyter repos, `ipython`, `matplotlib` or anything else, so I post it here. Please point out if I should post it elsewhere. Thanks!

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. I'm sorry such a detailed bug report didn't receive any attention. I hope you were able to eventually resolve the issue.

Thanks you and happy hacking! :bowtie:
