### ISSUE TITLE
Kernel hangs with latest jupyter 4.0.4

### ISSUE THREAD

**Issue by rseed42** [jupyter/jupyter#40]
Installs and starts successfully. However, when I enter some Scala expression in the first cell and start it, it remains at "[*]" forever. Both for scala 2.10 and 2.11.

**Comment by minrk** [comment]
Do you see anything in the terminal or javascript console?

**Comment by rseed42** [comment]
It says that the kernel has started, after that there are no exceptions, just no output and the cell stays at [*].

**Comment by willingc** [comment]
Closing this issue as addressed. :sunflower:
