### ISSUE TITLE
Reviving the all-Jupyter team meeting

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter#400]
Hello everyone, 

I wanted to point you to my discourse post, ["Reviving the all-Jupyter team meeting"](https://discourse.jupyter.org/t/reviving-the-all-jupyter-team-meetings/423). A few of us met on Zoom earlier today and discussed how to repurpose these all-team meetings moving forward. This post summarizes our discussion (albeit, from my perspective). 

I would love to get feedback!

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. There are now regular [community calls](https://www.youtube.com/playlist?list=PLUrHeD2K9Cmkoamm4NjLmvXC4Y6E1o8SP) happening, and you can learn about them on the jupyter discourse, and elsewhere.

Happy hacking! :bowtie:
