### ISSUE TITLE
how can i import training date excel file to juypter notebook?

### ISSUE THREAD

**Issue by tlmnader** [jupyter/jupyter#402]
I use anaconda framework,jupyter ide I download a training date file.xlsx ,but I cant load it to file to do operations is a problem in the location of training date file ? 
I tried this
df=pd.read_csv('training.csv')
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-7890e69ca8e6> in <module>()
----> 1 df=pd.read_csv('training.csv')

NameError: name 'pd' is not defined

I tried anthor code to use dateframe . "dataframe is not defined in pandas"

**Comment by ABHISHEK2F24** [comment]
Hello @tlmnader 
there are more than one error in here and so is the solution.
**NameError: name 'pd' is not defined** and **file name change xlsx to csv(no need)** can be solved using following lines
```
import pandas as pd
df = pd.read_excel('file.xlsx')

```

**Comment by naderasadii** [comment]
I want to upload      smartphones = pd.read_csv('c://smartphones.csv') but it go whit eror
how I can fix this
thank you
![Annotation 2020-01-25 023423](https://user-images.githubusercontent.com/60292886/73123519-dd851080-3f45-11ea-9d28-6d5ff76d7e8e.png)

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
