### ISSUE TITLE
RTD build on commit broken?

### ISSUE THREAD

**Issue by jhermann** [jupyter/jupyter#406]
GitHub changed automation from webhooks to "actions" a while ago. Meaning "build on commit" in this (and likely other Jupyter projects) is broken.

**Comment by choldgraf** [comment]
it seems like the latest commit successfully built on RTD...so maybe this isn't broken after all?

**Comment by jhermann** [comment]
You sure @willingc did not trigger this manually?

**Comment by choldgraf** [comment]
nope not at all :-)  I am not sure how to check for it, just wanted to flag that I noticed the docs were built

**Comment by willingc** [comment]
I did add the webhook a couple of days ago. If we can check if all works now for you @jhermann after a refresh we can close. @choldgraf can you open an issue to have someone/me add you to the RTD account. If fact, I would suggest adding you to all the repos and checking all of the webhooks.

**Comment by jhermann** [comment]
Smells like an orga team (member group) would be in order, like `doc-admins`.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
