### ISSUE TITLE
Jupyter notebook v5.7.6 won't launch, Windows10 x64, Anaconda, v5.7.4 ok

### ISSUE THREAD

**Issue by Kri-Ol** [jupyter/jupyter#408]
Windows 10, r1809, x64, Anaconda, python 3.7, latest updates installed, Terminus terminal, Chrome Version 73.0.3683.86 (Official Build) (64-bit), notebook  5.7.6

> jupyter notebook

redirect screen appears for a second or two, then empty screen in Chrome

downgrade to notebook  5.7.4

> jupyter notebook

works as expected

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
