### ISSUE TITLE
Add Chris H to access the RTD

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter#411]
I don't believe that I currently have access to these docs via readthedocs. I'd be happy to help improve the documentation if I had access. Could I get it?   (cc @willingc )

**Comment by willingc** [comment]
Thanks for filing the issue. I've added you @choldgraf. Please let me know if you want access to any others.

**Comment by choldgraf** [comment]
I'm happy to have rtd access to anything... Docs are near and dear to my heart :-)

**Comment by willingc** [comment]
@choldgraf Just ping me when you come across a repo that you need access. It needs to be set in individual RTD projects, and I don’t know an easy way to set multiple at once
