### ISSUE TITLE
Broken link in gallery of notebooks

### ISSUE THREAD

**Issue by ghost** [jupyter/jupyter#422]
In item Fractals, complex numbers, and your imagination, by Caleb Fangmeier.
This link is broken http://nbviewer.ipython.org/github/cfangmeier/ipython_notebooks/blob/master/Imagination.ipynb

This one works (links to historical blob)
https://nbviewer.jupyter.org/github/cfangmeier/Small/blob/9037dbd6d7e5843a60d7a92c6e4a713b3b685a74/Imagination.ipynb

**Comment by wgong** [comment]
edited wiki with the working link. Thanks

**Comment by ivanov** [comment]
thank for the report and the fix!
