### ISSUE TITLE
Apache Toree - PySpark  error 

### ISSUE THREAD

**Issue by sunnyEV** [jupyter/jupyter#433]
Hi, I tried all the settings need to run PySpark Toree. Not able to figure out were it went wrong, suggestions! 

Name: org.apache.toree.interpreter.broker.BrokerException
Message: Traceback (most recent call last):
  File "/tmp/kernel-PySpark-551540d3-c069-4027-a6d8-bc4199a205cd/pyspark_runner.py", line 166, in <module>
    kernel.refreshContext()
  File "/tmp/kernel-PySpark-551540d3-c069-4027-a6d8-bc4199a205cd/pyspark_runner.py", line 131, in refreshContext
    sc = SparkContext(jsc=jsc, gateway=gateway, conf=conf)
  File "/home/likithreddy/spark-2.4.3-bin-hadoop2.7/python/pyspark/context.py", line 127, in __init__
    "You are trying to pass an insecure Py4j gateway to Spark. This"
ValueError: You are trying to pass an insecure Py4j gateway to Spark. This presents a security risk.  If you are sure you understand and accept this risk, you can set the environment variable 'PYSPARK_ALLOW_INSECURE_GATEWAY=1', but note this option will be removed in Spark 3.0

StackTrace: org.apache.toree.interpreter.broker.BrokerState$$anonfun$markFailure$1.apply(BrokerState.scala:158)
org.apache.toree.interpreter.broker.BrokerState$$anonfun$markFailure$1.apply(BrokerState.scala:158)
scala.Option.foreach(Option.scala:257)
org.apache.toree.interpreter.broker.BrokerState.markFailure(BrokerState.scala:157)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
py4j.Gateway.invoke(Gateway.java:282)
py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
py4j.commands.CallCommand.execute(CallCommand.java:79)
py4j.GatewayConnection.run(GatewayConnection.java:238)
java.lang.Thread.run(Thread.java:748)

​

**Comment by jismyseban** [comment]
I am facing this issue as well. Do you have a work around?

**Comment by anogues** [comment]
Hello.

It's possifle to fix it i think. I did i tbut need to test deeply.

You need to find your pyspark installation, for your case: /home/likithreddy/spark-2.4.3-bin-hadoop2.7/python/pyspark/context.py

And comment the following lines (arround lines 115). Depending the version 2.3.3, 2.4.0, 2.4.x they can look a little bit different as they changed the code several times there, but the idea is to comment the raise ValueError part:

        #if gateway is not None and gateway.gateway_parameters.auth_token is None:
        #    raise ValueError(
        #        "You are trying to pass an insecure Py4j gateway to Spark. This"
        #        " is not allowed as it is a security risk.")

Regards,
Albert

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
