### ISSUE TITLE
Cannot login to Jupyterhub for new user -- ValueError: substring not found

### ISSUE THREAD

**Issue by pruce008** [jupyter/jupyter#436]
[I 2019-07-25 13:42:29.832 JupyterHub base:346] User logged in: user01_admin
sudo: a password is required
[E 2019-07-25 13:42:30.261 JupyterHub spawner:83] Failed to get JSON result from mediator: ''
[E 2019-07-25 13:42:30.265 JupyterHub user:427] Unhandled error starting user01_admin's
server: substring not found
[E 2019-07-25 13:42:30.334 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (::ffff:192.168.0.177)
    HTTPServerRequest(protocol='https', host='mincuda03:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:192.168.0.177', headers={'X-Forwarded-Host': 'mincuda03:8000', 'X-Forwarded-Proto': 'https', 'X-Forwarded-Port': '8000', 'X-Forwarded-For': '::ffff:192.168.0.177', 'Cookie': 'jupyterhub-hub-login="2|1:0|10:1564072369|20:jupyterhub-hub-login|44:NzRiOTZjNGQ5MGRlNDA1Nzk1NjIzZWUwOGI1ZTU5OTg=|9b13921dfb0d67b23e7b4154445beb167f8e9de17459894f673feff7b8cfa238"; _xsrf=2|418a81c3|fdc32f03cb05c5f89c48ebdd2698307b|1563959864; jupyterhub-session-id=1dfd64df1fae402bbbfadb98f589d766', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'https://mincuda03:8000/hub/login?next=', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded', 'Upgrade-Insecure-Requests': '1', 'Origin': 'https://mincuda03:8000', 'Cache-Control': 'max-age=0', 'Content-Length': '55', 'Connection': 'close', 'Host': 'mincuda03:8000'})
    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/login.py", line 94, in post
        yield self.spawn_single_user(user)
      File "/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 475, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/anaconda3/lib/python3.6/site-packages/sudospawner/spawner.py", line 92, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/anaconda3/lib/python3.6/site-packages/sudospawner/spawner.py", line 80, in do
        data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
    ValueError: substring not found

 

[E 2019-07-25 13:42:30.337 JupyterHub log:114] {
      "X-Forwarded-Host": "mincuda03:8000",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:192.168.0.177",
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1564072369|20:jupyterhub-hub-login|44:NzRiOTZjNGQ5MGRlNDA1Nzk1NjIzZWUwOGI1ZTU5OTg=|9b13921dfb0d67b23e7b4154445beb167f8e9de17459894f673feff7b8cfa238\"; _xsrf=2|418a81c3|fdc32f03cb05c5f89c48ebdd2698307b|1563959864; jupyterhub-session-id=1dfd64df1fae402bbbfadb98f589d766",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://mincuda03:8000/hub/login?next=",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Upgrade-Insecure-Requests": "1",
      "Origin": "https://mincuda03:8000",
      "Cache-Control": "max-age=0",

**Comment by pruce008** [comment]
Any help will be much appreciated. Thanks.

**Comment by hhajian** [comment]
For me, this was related to sudo rules. Follow the steps in https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges and make sure the "sudo setup test" runs fine.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-works-as-root-but-not-as-a-user/8851/1

**Comment by tgy** [comment]
in my case, this was simply because the user was not in the `jupyterhub` group

`usermod -aG jupyterhub myuser` did the trick

hope this helps someone

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Please open a new one in JupyterHub repository if you run into similar issues.

Thanks everyone and happy hacking! :bowtie:
