### ISSUE TITLE
Gallery of notebooks is missing

### ISSUE THREAD

**Issue by mmmm1998** [jupyter/jupyter#437]
Looks like
https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks
not exists anymore.

**Comment by faesepulveda** [comment]
this was a valuable resource, is there any way to fix it?

**Comment by fookatchu** [comment]
Someone deleted it for no clear reason. You can access the gallery through the revisions. Here is a link to the [latest full revision](https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks/fa878c1d1c0642d7a6448ed94d38a389461b087e).

**Comment by choldgraf** [comment]
Hey all - that was a good catch, I've reverted back to the last commit before the page was destroyed.
