### ISSUE TITLE
Why jupyter notebook take so much of the left side page layout to nothing ?

### ISSUE THREAD

**Issue by Uiuran** [jupyter/jupyter#441]
This is clearly visible in this print screen, since the cell is big the contrast is clear, a lot of dev writing space going to waste in this layout. I like very much of jupyter as IDE of development and presentation, but this layout is annoying. Maybe there is a way to build some extension to get rid of this blank space.

printscreen:
https://drive.google.com/file/d/1YlXViX0XFsBhk-0aMyoElJoEbWyzaaTu/view?usp=sharing

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue.
Happy hacking! :bowtie:
