### ISSUE TITLE
Docs: Is `JUPYTER_DATA_DIR` mentioned?

### ISSUE THREAD

**Issue by krinsman** [jupyter/jupyter#449]
Related issue: https://github.com/jupyterlab/jupyterlab/issues/5045

It seems that currently the `JUPYTER_DATA_DIR` environment variable is undocumented. Having some documentation about (1) the fact that it exists and (2) what it can be used for, e.g. customizing the installation location for kernel_specs [[ex.1]](https://github.com/JuliaLang/IJulia.jl/issues/865) [[ex.2]](https://github.com/n-riesco/ijavascript/issues/153) would it be useful.

`JUPYTER_DATA_DIR` being undocumented seems to have caused some confusion for others, see e.g. [this StackOverflow question](https://stackoverflow.com/questions/47660483/jupyter-path-in-environment-variables-not-working). Also it seems to be important inasmuch as there's a CLI flag for it in Jupyter Lab and in [Jupyter](https://jupyter.readthedocs.io/en/latest/projects/jupyter-command.html?highlight=data_dir).

It's not clear to me [from the code](https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/paths.py) what the difference between `JUPYTER_DATA_DIR` and `JUPYTER_PATH` is either (and also others are confused by this as indicated by the StackOverflow question). **EDIT:** I just realized that this has also been mentioned here https://github.com/jupyter/jupyter/pull/426/files and here https://github.com/jupyter/jupyter_core/issues/138.

**Comment by choldgraf** [comment]
closed in https://github.com/jupyter/jupyter/pull/450
