### ISSUE TITLE
How can I elegantly change notebook's password frequently

### ISSUE THREAD

**Issue by meyougonglv** [jupyter/jupyter#465]
Hi , I want to make the jupyter notebook can be accessed by one person for just some hours, and after that time it will be unavialable for that man. So I need chage password frequently. Is there a elegant and efficent way to change password? If can be directly changed on Web UI is perfect.
Is there such function? Thanks in advance

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. `jupyter notebook password` and `jupyter lab password` would be the way to change passwords, though it may require notebook restarts.

Thanks everyone and happy hacking! :bowtie:
