### ISSUE TITLE
why i cant change the serving files?

### ISSUE THREAD

**Issue by iliveforfun** [jupyter/jupyter#468]
when I start up the jupyter from the powershell using `jupyter notebook`,  I can see my serving files is `D:\jupyter notebook` which I configure in jupyter_notebook_config.py, however when I start up  using jupyter.exe,  I find serving files becomes `%USER%/jupyter_notebook`, I wanna know how to change it,  I have set the environment variable and so on....

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
