### ISSUE TITLE
How to change the kernel version for python???

### ISSUE THREAD

**Issue by isaac-you** [jupyter/jupyter#474]
The basic anaconda install python3.6.5 for the system , And I use the jupyterLab 0.32.1 to get remote python kernel under ubuntu system. 

But when I use the code : 
```
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```
to install pytorch for the system 
It automatically install python3.6.7 for pytorch 

So I can just only use python in the terminal to import torch 
```
(pytorch12) isaac@AIServer01:~$ python
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> 

```

but It cannot work for ipython  and  jupyter kernel 

```
(pytorch12) isaac@AIServer01:~$ ipython
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-eb42ca6e4af3> in <module>()
----> 1 import torch

ModuleNotFoundError: No module named 'torch'

```

Because the ipython and jupyter still connect to python3.6.5  
How can switch to python3.6.7 to use pytorch by jupyter ??
Thank you .

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. What you'd need to do is install a jupyter kernel using whatever version of python you wanted to use.

Thanks everyone and happy hacking! :bowtie:
