### ISSUE TITLE
Question about Jupyter Events for NBExtensions

### ISSUE THREAD

**Issue by clarencejychan** [jupyter/jupyter#479]
I have some code in an NB extension that is dependent on notebook.kernel.name to be populated. Due to how I"m loading the extension, the kernel is sometimes not ready by the time the extension is loaded. I tried using the kernel_ready.Kernel event but it seems when it’s fired, the notebook.kernel.name is still not populated.

What’s an event that I could use which would ensure that the notebook object and the kernel object are completely populated?

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
