### ISSUE TITLE
A simple cell running takes very very long time

### ISSUE THREAD

**Issue by pipdax** [jupyter/jupyter#487]
[![enter image description here][1]][1]

Here is the code,when I run a notebook cell, one cell will takes very long times. It appears once when run two times. But when I abort running this cell, and run again, it will success quickly.
Also, when I abort running this cell, the time of running this cell is 7h52m11s, like below.

[![enter image description here][2]][2]

I don't know why this happends.

  [1]: https://i.stack.imgur.com/Iysjq.png
  [2]: https://i.stack.imgur.com/PBVfh.png

**Comment by ivanov** [comment]
looks like you had some extra extensions that didn't come with default jupyter, so I can only imagine that they didn't handle the case of aborted cells properly for displaying this timing information.
