### ISSUE TITLE
Windows, Python 3.7 Jupyter Notebook: Cannot interrupt cell with client 5.3.4

### ISSUE THREAD

**Issue by jaewoo-so** [jupyter/jupyter#488]
python 3.7
windows 10 

jsonschema                        3.2.0
jupyter-client                    5.3.4
jupyter-console                   6.0.0
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.6.1
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.4
jupyter-nbextensions-configurator 0.4.1
jupyter-tensorboard               0.1.10
jupyterlab                        1.1.1
jupyterlab-server                 1.0.6

interrupt kernel not work .

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Please open an issue on the notebook repo if this is still occurring, along with how you are issuing the interrupt.

Thanks everyone and happy hacking! :bowtie:
