### ISSUE TITLE
Modification Permission denied

### ISSUE THREAD

**Issue by Thidashwe** [jupyter/jupyter#491]
I also encountered a similar error. Jupyter notebook installation in my Ubuntu 17.04 cloud machine had issues selecting the right kernel. This is what I did to solve this issue.

**Step 1:**
Install all the necessary dependencies:
_**For Python2:**_
$sudo apt-get install python-setuptools python-dev build-essential
$sudo easy_install pip

$python2 -m pip --version

$python2 -m pip install ipykernel
$sudo python2 -m ipykernel install --user
$pip install -U jupyter ipython

**_For Python3:_**
$sudo apt-get install python3-setuptools python3-dev build-essential
$sudo apt-get install python3-pip

$python3 -m pip --version

$sudo python3 -m pip install ipykernel
$sudo python3 -m ipykernel install --user
$sudo pip3 install -U jupyter ipython

**Step 2:**
Find the python executable locations for each version of Python and available kernels for Jupyter:

**_For Python2:_**
$python
>>>import sys
>>>print sys.executable
 The output for me was: /usr/bin/python

**_For Python3:_**
$python3
>>>import sys
>>>print (sys.executable)
The output for me was: /usr/bin/python3

To get the list of available kernels:

$jupyter kernelspec list

The output for me was:
Available kernels:
  python2    /home/info/.local/share/jupyter/kernels/python2
  python3    /home/info/.local/share/jupyter/kernels/python3

**Step 3:**
Update the kernel.json file with the correct location pointers to python executable

**_For Python2:_**
$sudo nano /usr/local/share/jupyter/kernels/python2/kernel.json

Eg:

{
 "display_name": "Python 2", 
 "language": "python", 
 "argv": [
  "/usr/bin/python",  
  "-m", 
  "ipykernel_launcher", 
  "-f", 
  "{connection_file}"
 ]
}

**_For Python3:_**
$sudo nano /usr/local/share/jupyter/kernels/python3/kernel.json

{
 "display_name": "Python 3", 
 "language": "python", 
 "argv": [
  "/usr/bin/python3",  
  "-m", 
  "ipykernel_launcher", 
  "-f", 
  "{connection_file}"
 ]
}

**Step 4:**
Restart Jupyter and toggle kernels to see if python versions are selected correctly in the back-end.

_Originally posted by @rahulremanan in https://github.com/jupyter/jupyter/issues/270#issuecomment-348671221_

I opened /usr/local/share/jupyter/kernels/python2/kernel.json and rewrite the python path, but I couldn't save the file after that.

The reason might because of me using a server instead of stand alone OS, if it is like this, do you have any idea please?

**Comment by Dark403969** [comment]
> I also encountered a similar error. Jupyter notebook installation in my Ubuntu 17.04 cloud machine had issues selecting the right kernel. This is what I did to solve this issue.
> 
> **Step 1:**
> Install all the necessary dependencies:
> _**For Python2:**_
> $sudo apt-get install python-setuptools python-dev build-essential
> $sudo easy_install pip
> 
> $python2 -m pip --version
> 
> $python2 -m pip install ipykernel
> $sudo python2 -m ipykernel install --user
> $pip install -U jupyter ipython
> 
> **_For Python3:_**
> $sudo apt-get install python3-setuptools python3-dev build-essential
> $sudo apt-get install python3-pip
> 
> $python3 -m pip --version
> 
> $sudo python3 -m pip install ipykernel
> $sudo python3 -m ipykernel install --user
> $sudo pip3 install -U jupyter ipython
> 
> **Step 2:**
> Find the python executable locations for each version of Python and available kernels for Jupyter:
> 
> **_For Python2:_**
> $python
> 
> > > > import sys
> > > > print sys.executable
> > > > The output for me was: /usr/bin/python
> 
> **_For Python3:_**
> $python3
> 
> > > > import sys
> > > > print (sys.executable)
> > > > The output for me was: /usr/bin/python3
> 
> To get the list of available kernels:
> 
> $jupyter kernelspec list
> 
> The output for me was:
> Available kernels:
> python2 /home/info/.local/share/jupyter/kernels/python2
> python3 /home/info/.local/share/jupyter/kernels/python3
> 
> **Step 3:**
> Update the kernel.json file with the correct location pointers to python executable
> 
> **_For Python2:_**
> $sudo nano /usr/local/share/jupyter/kernels/python2/kernel.json
> 
> Eg:
> 
> {
> "display_name": "Python 2",
> "language": "python",
> "argv": [
> "/usr/bin/python",
> "-m",
> "ipykernel_launcher",
> "-f",
> "{connection_file}"
> ]
> }
> 
> **_For Python3:_**
> $sudo nano /usr/local/share/jupyter/kernels/python3/kernel.json
> 
> {
> "display_name": "Python 3",
> "language": "python",
> "argv": [
> "/usr/bin/python3",
> "-m",
> "ipykernel_launcher",
> "-f",
> "{connection_file}"
> ]
> }
> 
> **Step 4:**
> Restart Jupyter and toggle kernels to see if python versions are selected correctly in the back-end.
> 
> _Originally posted by @rahulremanan in [#270 (comment)](https://github.com/jupyter/jupyter/issues/270#issuecomment-348671221)_
> 
> I opened /usr/local/share/jupyter/kernels/python2/kernel.json and rewrite the python path, but I couldn't save the file after that.
> 
> The reason might because of me using a server instead of stand alone OS, if it is like this, do you have any idea please?

**Comment by Dark403969** [comment]
@
