### ISSUE TITLE
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'

### ISSUE THREAD

**Issue by schorschie** [jupyter/jupyter#492]
Hi there,

I’m familiar with Jupyter from work and I tried using it at home with my Debian 10 system. I get the following error, and the kernel crashes:

`ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'`

I googled it and tried installing different versions of `prompt_toolkit` and `ipython` but it never succeed. 

Any ideas?

regards,
Gregory

**Comment by DA-fromindia** [comment]
https://github.com/jupyter/notebook/issues/4050

this will help!!

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
