### ISSUE TITLE
Julia: extra indentation after 'elseif' or 'else' keyword, until end of block

### ISSUE THREAD

**Issue by chunjiw** [jupyter/jupyter#493]
Type an if-else chunk of code naturally results in the following display:
```julia
if x < y
    println()
elseif x > y
        println()
    elseif
            println()
        else
                println()
            end
```
Every `elseif` and `else` adds an extra indentation.

It says here https://github.com/codemirror/CodeMirror/pull/5762 and other places that it is resolved, but apparently not. Forced to open a new issue here.

Julia version I am using:
```
Julia Version 1.0.5
Commit 3af96bcefc (2019-09-09 19:06 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by ivanov** [comment]
it's possible that codemirror5 fixed the issue but Jupyer hadn't pulled it in yet. Closing this old issue.
