### ISSUE TITLE
Start the Table of contents unexpanded

### ISSUE THREAD

**Issue by aswathysheena** [jupyter/jupyter#496]
I am making a report in jupyter notebook and converting to html. I have  enabled the option TOC and its coming properly , but expanded when I open the html. I want TOC to start unexpanded at first.

Is there anyway can I do that?

**Comment by reddishshoib** [comment]
Try
jupyter nbconvert --execute --to html notebook.ipynb
maybe this can help you

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Try asking on https://discourse.jupyter.org/

Thanks everyone and happy hacking! :bowtie:
