### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by BlockchainRev** [jupyter/jupyter#498]
Hello. I'm just starting to use jupyter notebook, and am running fastai.  Everything works until when I try to import stuff.
I run
`# Import necessary libraries
from fastai.vision import * 
import matplotlib.pyplot as plt`
To get:
`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-21c8d93a0244> in <module>
      1 # Import necessary libraries
      2 from fastai import *
----> 3 import matplotlib.pyplot as plt

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py in <module>
    136 # cbook must import matplotlib only within function
    137 # definitions, so it is safe to import from it here.
--> 138 from . import cbook, rcsetup
    139 from matplotlib.cbook import (
    140     MatplotlibDeprecationWarning, dedent, get_label, sanitize_sequence)

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\cbook\__init__.py in <module>
     29 from weakref import WeakMethod
     30 
---> 31 import numpy as np
     32 
     33 import matplotlib

~\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py in <module>
    138 
    139     # Allow distributors to run custom init code
--> 140     from . import _distributor_init
    141 
    142     from . import core

~\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py in <module>
     24                 # NOTE: would it change behavior to load ALL
     25                 # DLLs at this path vs. the name restriction?
---> 26                 WinDLL(os.path.abspath(filename))
     27                 DLL_filenames.append(filename)
     28     if len(DLL_filenames) > 1:

C:\ProgramData\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: [WinError 193] %1 is not a valid Win32 application
`
I would appreciate any help.

**Comment by Rohitpuranik-cloud** [comment]
After installing matplotlib When I was trying to use matplotlib.pyplot it was giving error   module not found.

I browsed some white papers and found out that we also need to install scipy library to use the matplotlib  so I used the below in my command prompt 

**python -mpip install scipy**

Restarted my kernel session.

It worked!!!

Let me know if that worked for you.
