### ISSUE TITLE
Possibly inaccurate shim warning message

### ISSUE THREAD

**Issue by tritemio** [jupyter/jupyter#50]
I'm not sure in which repo to report this. In Jupyter 4.0.6, if I do:

```
import IPython.nbconvert
```

I get the following message:

```
Anaconda\envs\py3\lib\site-packages\IPython\nbconvert.py:13: 
ShimWarning: The `IPython.nbconvert` package has been deprecated. 
You should import from ipython_nbconvert instead.
  "You should import from ipython_nbconvert instead.", ShimWarning)
```
*(manually added line break)*

Shouldn't be `nbconvert` instead of `ipython_nbconvert`?

Also, any reason the message is ending with `, ShimWarning)`?

**Comment by minrk** [comment]
Indeed, and it has been fixed in IPython master. The next release of IPython will have the right message.
