### ISSUE TITLE
python version >=3.8.0 cannot jupyter install pysparkkerrnel

### ISSUE THREAD

**Issue by zesluo** [jupyter/jupyter#501]
Hello! I'm doing a vscode extension tool. I just found that python version >=3.8.0 cannot jupyter install pysparkkerrnel. However, it can work if python <3.8.0. our tool use ‘jupyter install sparkmagic’ and ‘jupyter.exe kernelspec install pysparkkernel’. As the picture shown, the link is here: https://pypi.org/project/sparkmagic/0.15.0/#history, it doesn’t apply to python 3.8.0. Thanks a lot!

![image](https://user-images.githubusercontent.com/46309533/77924637-7f263680-72d6-11ea-8b2f-728dc8aa5f41.png)

![image](https://user-images.githubusercontent.com/46309533/77924559-5f8f0e00-72d6-11ea-8808-5506f316b30a.png)
![image](https://user-images.githubusercontent.com/46309533/77924577-66b61c00-72d6-11ea-86ff-6b34f730ce54.png)

https://discourse.jupyter.org

Thanks!

**Comment by ivanov** [comment]
sounds like this should have been reported to https://github.com/jupyter-incubator/sparkmagic - closing this issue as stale. 
Happy hacking! :bowtie:
