### ISSUE TITLE
No corre el comando jupyter notebook

### ISSUE THREAD

**Issue by alexrios22** [jupyter/jupyter#502]
Buen dia,

Al intentar ejecutar el comando `jupyter notebook` desde la ventana de comandos, no se ejecuta, se queda congelado, no da error ni nada, jupyter se encuentra en el path de las variables de entorno, intente cambiando de puerto con `jupyter notebook --port 8889` y nada, es como si se quedara congelado.

Deseo correr jupyter para poder utilizar la ventana interactiva de Visual Studio Code, tambien trate de correr `jupyter notebook` desde anaconda y tampoco me funciono igual se queda congelado.

Es importante destacar que al abrir el administrador de tareas, se ve que el proceso se esta "ejecutando", sin embargo no hace nada a pesar de dejarlo alli corriendo.

Agradeceria la ayuda que me puedan prestar, muchas gracias.

Ambiente en el que estamos ejecutando jupyter
-     Jupyter server running: Local
-     Extension version: 2020.3.71113 (Python extension for Visual Studio Code)
-     VS Code version: 1.43.2
-     Setting python.jediEnabled: true
-     Python and/or Anaconda version: Python 3.8.1
-     OS: Windows 10 64bits
-     Virtual environment: N/A

**Comment by ivanov** [comment]
I hope you were able to resolve your  issue, closing this as stale.
