### ISSUE TITLE
Move documentation index to rST without breaking translations?

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter#509]
Right now, we are using a manual-override of `index.html` to generate the landing page of the jupyter community docs (https://github.com/jupyter/jupyter/blob/master/docs/source/_templates/index.html).

I feel like if this file were written in rST (and achieving the same layout with the `list-table` directive, then it would be easier to read, maintain, and contribute to.

I'd like to try updating this page to `.rst`, but I see there are a lot `{%trans%}` elements in there, and it makes me wonder if doing this would break our translations somehow. @parente do you know if this is this case? Or if there's a way to move to rST but keep the translations?

**Comment by parente** [comment]
@choldgraf Those `{%trans%}` blocks pre-date the work done in https://github.com/jupyter/jupyter/issues/430 to set up the translation workflow. If you convert to using an `index.rst`, we can re-enter the translation strings into transifex, setting up any language definitions not already configured there.

I can help out with that process.

**Comment by choldgraf** [comment]
this is done now!
