### ISSUE TITLE
Add python2 kernel to jupyterhub 

### ISSUE THREAD

**Issue by zainul1114** [jupyter/jupyter#522]
Hi,
I am new to jupyterhub and i am trying to Add multiple python kernel(2.7.x,3.6.x,3.7.x) to jupyterhub 
my default python version is 3.6.8 which is installed from python source file, 

i am able to run jupyterhub with python3.
Python path: /share/apps/platform/ai/py36/3_6_8/bin/python3

But now i am trying to add Python 2.7.16 kernel
 
my python2 installation path: /share/apps/platform/ai/py27/2_7_16/bin/python

#jupyter-kernelspec list
Available kernels:
ir /root/.local/share/jupyter/kernels/ir
python3 /share/apps/platform/ai/py36/3_6_9/share/jupyter/kernels/python3

i tried to add python2:
[root@master ~]# python --version 
Python 2.7.16 
[root@master ~]# python3 --version 
Python 3.6.9 

#python2 -m ipykernel install 
Installed kernelspec python2 in /root/.local/share/jupyter/kernels/python2

[root@master ~]# jupyter-kernelspec list 
Available kernels: 
 ir /root/.local/share/jupyter/kernels/ir 
 python3 /share/apps/platform/ai/py36/3_6_9/share/jupyter/kernels/python3 
 python2 /usr/local/share/jupyter/kernels/python2

and when i try to check logs jupyterhub, i am getting below error

Jul 6 22:00:03 master jupyterhub: [I 2020-07-06 22:00:03.662 SingleUserNotebookApp restarter:110] KernelRestarter: restarting kernel (4/5), new random ports 
Jul 6 22:00:03 master jupyterhub: /share/apps/platform/ai/py27/2_7_16/bin/python2: No module named ipykernel_launcher 
Jul 6 22:00:06 master jupyterhub: [W 2020-07-06 22:00:06.690 SingleUserNotebookApp restarter:100] KernelRestarter: restart failed 
Jul 6 22:00:06 master jupyterhub: [W 2020-07-06 22:00:06.691 SingleUserNotebookApp kernelmanager:135] Kernel 2997ce87-ab15-475a-b4a0-d534bf910d8f died, removing from map. 

Please guide me how to resolve this.

**Comment by choldgraf** [comment]
hi there - I'd recommend asking in the Jupyter community forum: discourse.jupyter.org, this repository isn't used for taking user questions. I'll close this and look forward to your post in the forum, thanks!
