### ISSUE TITLE
Can't use Shift+Enter in firefox

### ISSUE THREAD

**Issue by pallabbasu** [jupyter/jupyter#528]
Suddenly Shift+Enter has stopped working in the edit mode in the jupyter-notebook. I can still execute a cell in the command mode.

Interestingly Kaggle is also affected. I think it may be some issue with the firefox. Private browsing and clearing cache etc. does not seem to work.

These are my configurations,

Firefox-79.0

Ubuntu-20.04

jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.13.0
ipykernel        : 5.2.0
jupyter client   : 6.1.2
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 6.0.0
nbformat         : 5.0.4
traitlets        : 4.3.3

**Comment by ivanov** [comment]
closing this - if there was an issue with basic execution as described here, it's pretty safe to say it has been dealt with over the last 3 years. 
Happy hacking! :bowtie:

**Comment by pallabbasu** [comment]
Thanks 🙏😊
