### ISSUE TITLE
fatal error in launcher

### ISSUE THREAD

**Issue by bauer-san** [jupyter/jupyter#53]
Windows 7
Python installation path: C:\Program Files (x86)\Python27\

When I:
C:\Program Files (x86)\Python27>*jupyter notebook*

I get:
*Fatal error in launcher: Unable to create process using '""C:\Program Files (x86)\Python27\python.exe"" "C:\Progra~2\Python27\Scripts\jupyter.exe" notebook'*

The jupyter*.exe files under C:\Program Files (x86)\Python27\Scripts have the "path with spaces" embedded.

I had a similar problem with pip but a ~recent update solved that.

How can I solve it for jupyter?

**Comment by willingc** [comment]
Closing as a resolved issue. If additional assistance is needed, please file an issue at [jupyter/help repo](https://github.com/jupyter/help).

**Comment by Ichaab** [comment]
How do you solved this problem please? I have the same issue

**Comment by DaveVoyles** [comment]
Same issue. 

How was it resolved?

**Comment by bauer-san** [comment]
Good questions.
It was never actually resolved but @willingc closed it.

**Comment by willingc** [comment]
@DaveVoyles @bauer-san Will you open a new issue specific to the current questions that you have about notebook installation on windows at https://github.com/jupyter/notebook/issues ? You will have better response doing that than reopening this old issue. Thanks 👍

**Comment by DaveVoyles** [comment]
Yes I will, thank you.

**Comment by AzureLu** [comment]
Maybe there are two environment path navigated to the jupyter-notebook.exe. 
I just fixed the same issue by removing the redundant path in environment path variable.

**Comment by AlkisPis** [comment]
> Maybe there are two environment path navigated to the jupyter-notebook.exe.
> I just fixed the same issue by removing the redundant path in environment path variable.

Can you please specify? How exactly did you fix it? What path variables are involved?
