### ISSUE TITLE
bad address

### ISSUE THREAD

**Issue by weilanhanf** [jupyter/jupyter#545]
I use Minconda, this package management tool to create a new python environment named sklearn. After I use this command “conda create -n sklearn python=3.6.5”, the environment is created. And I directly try "pip install jupyter" to install jupyter in this environment. But when I open jupyter notebook in browser,  something wrong happened. Details as follow:"**Bad address (C:\projects\libzmq\src\epoll.cpp:100)**". 

The system of my computer is Window10. 
The packages of this enviroment is showed below.
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
bleach              3.3.0
certifi             2020.12.5
cffi                1.14.4
colorama            0.4.4
decorator           4.4.2
defusedxml          0.6.0
entrypoints         0.3
importlib-metadata  3.4.0
ipykernel           5.4.3
ipython             7.16.1
ipython-genutils    0.2.0
ipywidgets          7.6.3
jedi                0.18.0
Jinja2              2.11.3
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.11
jupyter-console     6.2.0
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
MarkupSafe          1.1.1
mistune             0.8.4
nbclient            0.5.1
nbconvert           6.0.7
nbformat            5.1.2
nest-asyncio        1.5.1
notebook            6.2.0
packaging           20.9
pandocfilters       1.4.3
parso               0.8.1
pickleshare         0.7.5
pip                 20.3.3
prometheus-client   0.9.0
prompt-toolkit      3.0.14
pycparser           2.20
Pygments            2.7.4
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
pywin32             300
pywinpty            0.5.7
pyzmq               22.0.2
qtconsole           5.0.2
QtPy                1.9.0
Send2Trash          1.5.0
setuptools          52.0.0.post20210125
six                 1.15.0
terminado           0.9.2
testpath            0.4.4
tornado             6.1
traitlets           4.3.3
typing-extensions   3.7.4.3
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.36.2
widgetsnbextension  3.5.1
wincertstore        0.2
zipp                3.4.0

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. It is generally not a good idea to mix conda and pip commands. Pick one and use that to install all of the packages.

Thanks and happy hacking! :bowtie:
