### ISSUE TITLE
Broken Link for DLang (DMD) Kernel

### ISSUE THREAD

**Issue by majiang** [jupyter/jupyter#548]
There is a D-Lang entry on [Jupyter Kernels page](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) with link being 404.

Original maintainer @joequant , what's the current project status?  Is it possible to publish archived repository which can be forked by who are willing?

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. You might take a look at https://github.com/symmetryinvestments/jupyter-wire and https://github.com/m3m0ry/dlang-jupyter

Happy hacking! :bowtie:
