### ISSUE TITLE
pyspark(using yarn-client) ignoring PYSPARK_PYTHON when running on jupyter

### ISSUE THREAD

**Issue by llealgt** [jupyter/jupyter#554]
I have a use case where we have some pyspark code(using python kernel connecting to pyspark using yarn-client mode) and we need to specify a conda environment to use, but for some reason the PYSPARK_PYTHON setup seems to be ignored when running on jupyter(using a corporate jupyterlab instance), if the notebook is exported as .py file the configuration works fine.

I have already tried many things(none worked):

- setting the following in the beggining of the notebok os.environ['PYSPARK_PYTHON'] = "<the path>"
- adding it at spark session creation .config("spark.yarn.appMasterEnv.PYSPARK_PYTHON",test_path)
- adding it at spakr session creation .config("spark.pyspark.python",test_path) 

I saw some other people setting it using CLI env variables via:
export PYSPARK_PYTHON= the path
And then running jupyter notebook, but i cannot do it because i use a corporate jupyter lab instance so i tried adding it at 
ipython_config.py but it did not work, reference to SO question:
https://stackoverflow.com/questions/67542247/pyspark-python-setup-in-jupyter-notebooks-is-ignored

Does anybody knows how should I specify the PYSPARK_PYTHON from jupyter lab to use a specific conda environment?

**Comment by pra-sri** [comment]
It seems like you're facing difficulties in specifying the PYSPARK_PYTHON environment variable from JupyterLab to use a specific Conda environment when running PySpark code. Here are a few suggestions you can try to resolve the issue:
1.	Configure PYSPARK_PYTHON in the kernel startup script:
•	Locate the kernel startup script for your JupyterLab installation. The script is typically located in the kernels directory of your JupyterLab installation.
•	Open the kernel startup script for the Python kernel you're using.
•	Add the following line at the beginning of the script:
luaCopy code
import os os.environ['PYSPARK_PYTHON'] = "/path/to/conda/environment/python" 
•	Save the changes and restart JupyterLab.
2.	Modify the kernel's environment variables:
•	Go to the JupyterLab interface and click on the "Settings" tab.
•	Select "Advanced Settings Editor" from the drop-down menu.
•	In the settings editor, navigate to "Notebook" > "Kernel Environment Variables".
•	Add a new entry with the key PYSPARK_PYTHON and set its value to the path of the Python interpreter in your Conda environment.
•	Save the changes and restart the JupyterLab kernel.
3.	Use the findspark library:
•	Install the findspark library in your Conda environment by running conda install findspark.
•	In your JupyterLab notebook, import the findspark library and use the findspark.init() function to specify the PYSPARK_PYTHON path:
pythonCopy code
import findspark findspark.init("/path/to/conda/environment/python") 
•	This will ensure that PySpark uses the specified Python interpreter.
Make sure to replace "/path/to/conda/environment/python" with the actual path to the Python interpreter in your Conda environment.
If none of these suggestions work, it's possible that there might be specific configurations or restrictions imposed by your corporate JupyterLab environment that override or ignore the PYSPARK_PYTHON environment variable. In that case, it would be best to reach out to your system administrator or IT support for further assistance.

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue, as it is more of an issue for pyspark than a Jupyter issue. I'm not sure if there's a place where other spark and pyspark users monitor, but one possibility might be to make  a post or search https://discourse.jupyter.org/ Thanks @llealgt for reporting and @pra-sri for suggesting some paths forward.

Happy hacking! :bowtie:
