### ISSUE TITLE
Jupyter/IPython notebook requires kernel restart after every exception encountered in a cell

### ISSUE THREAD

**Issue by rainermann** [jupyter/jupyter#557]
Every time there is an error somewhere in a Python script, I need to kill and restart the kernel in Jupyter Notebook. Otherwise, none of the cells will execute. This happens with **any** script, i.e. it can be something as simple as `print('Hello, world!)` (missing the closing apostrophe). Killing and restarting the kernel is extremely annoying, as I'm losing all my variables etc. from previous calculations, so I need to rerun the entire script cell by cell. Why is this happening and can this behavior be changed somehow? Is this a "feature" of Jupyter/IPython or a bug?

Also, I often have to "force" a cell to execute by pressing Shift+Enter twice, because after the first time the cell would just stay busy indefinitely (showing `[*]`).

I'm working on a Windows 10 machine and installed `pip` using [get-pip.py](https://bootstrap.pypa.io/get-pip.py), then Jupyter via `pip install`, then all the Python packages I need for my work. I never had this problem on any other machine, either running Windows or various Linux distros.

**Comment by ivanov** [comment]
Your installation as described here was not working properly - this is not what should happen - you should have seen error messages and been able to continue to work by rerunning the broken cell after fixing any typos and having the rest of the state of the kernel untouched.
