### ISSUE TITLE
Add blog.jupyter.org status to status.jupyter.org

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#56]
Also should create a place with info on how do diagnose blog is down. 

And I don't know where to put such a meta issue.

**Comment by ellisonbg** [comment]
I don't have access to the blog host. I think @captainsafia might though.

**Comment by ellisonbg** [comment]
But yeah, our infrastructure documentation is definitely lacking. We need to have an up-to-date private Google Doc that describes all operational aspects of the project.

**Comment by Carreau** [comment]
I probably have access as it is with github ssh-keys. 
I just have 0 clues of hostname/username or what to do when logged-in

**Comment by Carreau** [comment]
> But yeah, our infrastructure documentation is definitely lacking. We need to have an up-to-date private Google Doc that describes all operational aspects of the project.

I think that most docs could be public, except any sensible which I think is minimal/

**Comment by ellisonbg** [comment]
I think the details of our operations should be private for security
reasons.

On Mon, Oct 26, 2015 at 1:22 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> But yeah, our infrastructure documentation is definitely lacking. We need
> to have an up-to-date private Google Doc that describes all operational
> aspects of the project.
>
> I think that most docs could be public, except any sensible which I think
> is minimal/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter/issues/56#issuecomment-151215402>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
I updated the status.io page that blog.jupyter.org is not responding yet the jupyter.org website is operating normally.

**Comment by captainsafia** [comment]
@Carreau — I have access to the serve the blog is on and I have an account on the blog (I believe it is an administrator account).

@ellisonbg — I ditto the starting to document things. @rgbkrk gave me access to our Rackspace servers yesterday and I practiced setting up some of our infrastructure (tmpnb and nbviewer) onto a small cluster I had. I was thinking that I could take this opportunity to document what I learn as I learn it. Would it make sense to have this information on a private Github repository on the org and give people access as necessary?

**Comment by willingc** [comment]
@minrk and @Carreau restored the blog and updated status.io that all is operational.

+1 to an infrastructure response plan.

**Comment by Carreau** [comment]
@captainsafia @willingc done. 
There is a private rep, you should receive an invite.

**Comment by captainsafia** [comment]
Thanks! I'll be able to add to this over the next couple of hours.

**Comment by captainsafia** [comment]
We deviated a bit from the original issue that @Carreau presented but I just added the Jupyter blog to [our status page](http://status.jupyter.org) so this can be closed.

**Comment by willingc** [comment]
@captainsafia Very helpful. Thanks.
