### ISSUE TITLE
open in windows without console window flashing

### ISSUE THREAD

**Issue by simonzack** [jupyter/jupyter#57]
Is there a way to open jupyter without the console window flashing in windows? I've tried pythonw but tt flashes twice for me every time:

    "C:\Program Files\Python34\pythonw.exe" -m qtconsole

**Comment by willingc** [comment]
@simonzack I don't have a Windows test system. I am going to reference this issue in the jupyter/qtconsole repository's issues since you will likely get a faster response there.

Related to: https://github.com/jupyter/qtconsole/issues/64

cc/@minrk

**Comment by tmr232** [comment]
The flashing windows are `ipconfig.exe` used to get the addresses of the Windows host.
I created a pull request to fix it on jupyter/jupyter_client#86.

**Comment by willingc** [comment]
@tmr232 Thanks again for a timely fix to @simonzack's issue. :cake: https://github.com/jupyter/jupyter_client/pull/86#issuecomment-151547292

**Comment by tmr232** [comment]
Very happy to help.

Anyway, I opened a new issue, addressing the fact that Jupyter currently uses `ipconfig.exe` and not OS APIs. jupyter/jupyter_client#87
