### ISSUE TITLE
Gallery of notebooks deleted again

### ISSUE THREAD

**Issue by Xpyder** [jupyter/jupyter#571]
Gallery of Notebooks was deleted a couple weeks ago (presumably by accident again)

https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks

Note: this has happened before, see ticket #437

**Comment by hangtwenty** [comment]
I was about to report the same, good catch. Then I realized the gallery is now on the wiki's home page, [`https://github.com/jupyter/jupyter/wiki`](https://github.com/jupyter/jupyter/wiki). There are two stale copies of them, but if there are external links to the old one, we probably shouldn't delete them - so I edited them to link to [the Jupyter wiki home page](https://github.com/jupyter/jupyter/wiki).

**Comment by hangtwenty** [comment]
Also added a footer:

[![image](https://user-images.githubusercontent.com/2420688/138043912-d2499f85-cf97-4de9-8ad9-bb92404f7758.png)](https://github.com/jupyter/jupyter/wiki)
