### ISSUE TITLE
Micronaut kernel link is invalid

### ISSUE THREAD

**Issue by diveyez** [jupyter/jupyter#588]
**Repository is not any longer at that URL.**
Suggest removal or replacement with an updated fork.

**Comment by krassowski** [comment]
Thank you! It was a typo I believe, the link was https://github.com/stainlessai/jupyter-jupyter but it should have been https://github.com/stainlessai/micronaut-jupyter. I fixed it on the https://github.com/jupyter/jupyter/wiki/Jupyter-kernels.

**Comment by choldgraf** [comment]
I think this one is now resolved, thanks @krassowski
