### ISSUE TITLE
Broken Link in documentation

### ISSUE THREAD

**Issue by duncan-wither** [jupyter/jupyter#589]
There's a broken link in the graphviz diagram on the [Using Jupyter Tools](https://jupyter.readthedocs.io/en/latest/use/using.html) page. 
Here's the code from [source file](https://github.com/jupyter/jupyter/blob/master/docs/source/use/using.rst):

```
kernel [
			label="Install a\nlanguage\nkernel",
			tooltip="How to install kernels",
			target="_top", color=green, // Local Link
			href="../projects/subprojects.html?highlight=jupyterhub#kernels"]
```
I think it should link to `https://jupyter.readthedocs.io/en/latest/install/kernels.html`.

**Comment by chunqiaohu** [comment]
您好，您的邮件我已经收到，会尽快给您回复，谢谢。
