### ISSUE TITLE
Icon for Jupyter / notebook / qtconsole

### ISSUE THREAD

**Issue by msarahan** [jupyter/jupyter#59]
Silly Windows question, apologies in advance.  Do you have a preferred icon for Jupyter / notebook / qtconsole shortcuts created by Anaconda?  I have looked for .ico files in several repositories, but see none.

**Comment by msarahan** [comment]
Note that Windows can't use SVGs or PNGs as icons.  I can convert your logo, but wanted to know if you already have something.

**Comment by damianavila** [comment]
ping @cameronoelsen, do we have something for the qtconsole (AFAIK, don't, but I could be wrong), also pinging @ellisonbg and @Carreau that maybe are interested on this as well...

**Comment by Carreau** [comment]
Yes, we have a list of icons for ipynbs: 

https://github.com/jupyter/notebook/tree/master/docs/resources (have small resolution variants)


![screen shot 2015-10-30 at 10 13 17](https://cloud.githubusercontent.com/assets/335567/10852623/df5e2192-7eee-11e5-8184-08eb05ab61ad.png)

None for the server though

the [qtconsole  icon](https://github.com/jupyter/qtconsole/blob/master/qtconsole/resources/icon/JupyterConsole.svg) could get some updating.

![screen shot 2015-10-30 at 10 14 28](https://cloud.githubusercontent.com/assets/335567/10852650/0abb29de-7eef-11e5-95b6-ce99c5a0cd4b.png)

**Comment by cameronoelsen** [comment]
So the shortcut icon for the qtconsole is the iP[y]: logo? Is there a specific logo for the qtconsole at all? I could make one if we need one for both qtconsole in general and the shortcut that shows! @damianavila @Carreau

**Comment by Carreau** [comment]
no the qtconsole logo is ipylogo on a terminal like background :-)

**Comment by dsblank** [comment]
But the qtconsole logo should be the Jupyter logo, perhaps on a terminal-like background.

**Comment by minrk** [comment]
Yeah, it should be Jupyter. It could be *just* the Jupyter logo.

**Comment by damianavila** [comment]
>But the qtconsole logo should be the Jupyter logo, perhaps on a terminal-like background.

Yep

>Yeah, it should be Jupyter. It could be just the Jupyter logo.

Yep... it could be...

**Comment by cameronoelsen** [comment]
Tomorrow when I'm in the office I'll make mockups of both variations and we can go from there!

**Comment by cameronoelsen** [comment]
So here is the qtconsole logo with the jupyter branding on it!
![qtconsole_jupyter](https://cloud.githubusercontent.com/assets/6437976/10979914/251ba41a-83b4-11e5-9435-893f5c753d0f.png)

SVG download link:
https://www.dropbox.com/s/s5sd2dzniibrag4/jupyter_qtconsole.svg?dl=0

For the jupyter file logo, I retouched it and scaled the "Nb" text to be the same size as each other. I can also take a second run on this icon. Just don't really know how the shortcut looks on a windows desktop.

![download](https://cloud.githubusercontent.com/assets/6437976/10980221/b5620cfc-83b5-11e5-8bf8-740d4afb5da6.png)

SVG download link:
https://www.dropbox.com/s/hfy7b43mvvzlet9/jupyter_filelogo.svg?dl=0

**Comment by Carreau** [comment]
can you convert the text to path ?  Or it render badly if you don't have the right font installed : 

![screen shot 2015-11-05 at 12 52 33](https://cloud.githubusercontent.com/assets/335567/10981366/47ca9cf2-83bc-11e5-98b3-c700127755d6.png)

**Comment by cameronoelsen** [comment]
@Carreau there we go! Should work now:
https://www.dropbox.com/s/hfy7b43mvvzlet9/jupyter_filelogo.svg?dl=0

**Comment by willingc** [comment]
Closing as an old issue. Please open new or outstanding design icon issues at [jupyter/design](https://github.com/jupyter/design). :art:

**Comment by swhare** [comment]
I too, got this issue, and solved it.  I may be late to the party, but in case anybody else who is looking for the answer happens across this page, I posted a solution in a repository https://github.com/swhare/JupyterNotebookSupport  Cheers!
