### ISSUE TITLE
Wiki links to 404

### ISSUE THREAD

**Issue by ezzcodeezzlife** [jupyter/jupyter#608]
Home > Statistics, Machine Learning, and Data Science > [Web scraping using Python with BeautifulSoup and Requests libraries](https://nbviewer.jupyter.org/github/Tanu-N-Prabhu/Python/blob/master/Web_scraping_Rate_My_Professor.ipynb), a notebook which explains scraping the data from the internet from scratch, by [Tanu Nanda Prabhu](https://github.com/Tanu-N-Prabhu/Python), author and editor at [Towards data science](https://medium.com/@tanunprabhu95).

first link links to 404 not found.

**Comment by isabela-pf** [comment]
Hi there! Can you provide a link to the page where the 404 is appearing? I'm not able to find the issue you're talking about.

**Comment by riyanswat** [comment]
It was in the wiki @isabela-pf  ... I fixed it now
