### ISSUE TITLE
Extend logging capabilities

### ISSUE THREAD

**Issue by aggFTW** [jupyter/jupyter#61]
Hi,

Right now, Jupyter uses the traitlets logging capabilites to log to stdout. When hosting Jupyter as a service in the cloud, there might be a need to send logs to other systems (e.g. a system exposed via a REST endpoint). Would a PR to create a configurable extension point for logging capabilities be something that you would support?

Thanks!

**Comment by ellisonbg** [comment]
My advice would be to log to stdout and then use your process management
system to direct the logs to an appropriate service/location. In general
trying to bundle details about your deployment architecture into your
services like this introduces coupling that will make things more painful.
I don't know where the code is, but I have done this in a few places over
time.

On Tue, Nov 3, 2015 at 7:38 PM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> Hi,
>
> Right now, Jupyter uses the traitlets logging capabilites to log to
> stdout. When hosting Jupyter as a service in the cloud, there might be a
> need to send logs to other systems (e.g. a system exposed via a REST
> endpoint). Would a PR to create a configurable extension point for logging
> capabilities be something that you would support?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter/issues/61>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by aggFTW** [comment]
Thanks @ellisonbg!

ping @msftristew

**Comment by minrk** [comment]
Most, if not all, process management tools (supervisor, docker, etc.) support this at a higher level, and assume that the processes it managers are logging to stdout/err, which it redirects. If you do it at this level, you get it for *all* services you run, not just Jupyter ones.

**Comment by aggFTW** [comment]
Thanks @minrk! Makes sense =)
