### ISSUE TITLE
Show execution time

### ISSUE THREAD

**Issue by adorilson** [jupyter/jupyter#62]
Show execution time script, like this

in[ ]: input code 
out[ ]: output
34ms

This "34ms" is the execution time showed after the code runned.

**Comment by dsblank** [comment]
For the IPython kernel see the `%%time` and `%%timeit` magics. %%time is also available for [MetaKernel-based kernels](https://github.com/Calysto/metakernel).

**Comment by Carreau** [comment]
Closing as this shoudl be either an extension (like the time /timeit modules built in) or even js extension.
