### ISSUE TITLE
Camera. Proposed designs

### ISSUE THREAD

**Issue by vidushidewan** [jupyter/jupyter#626]
How I suggest a method of camera. 
Concave Lens can capture image of object and the focus of the camera makes a real image inside the mid-focus. 
This image if captured at cathode ray. Can be a camera method.

**Comment by vidushidewan** [comment]
So, the projector are wired it seems if Monitors are used.

**Comment by isabela-pf** [comment]
Hi there, I am closing this because it looks like spam with the lack of complete sentences in the description. If there's any issue let me know and I'll reopen.

**Comment by Andani97** [comment]
**Hallo my friends because it looks complete sentences is the description**
