### ISSUE TITLE
Fatal Error on boot: "parser.py"

### ISSUE THREAD

**Issue by LienM** [jupyter/jupyter#63]
Yesterday I encountered the silliest error.

I uninspiredly named the parser for my dataset "parser.py". When I tried to boot Jupyter from my working directory the kernel kept dying. I got the generic error message "unable to find BeautifulSoup"  (XML, HTML, SGML) which as far as I was concerned might as well be used by Jupyter at some point in the parsing process.

Renaming the file obviously fixed the error, but it took me a while to figure out where it went wrong. I'm pretty sure I'm not the only uninspired programmer naming their parser "parser.py" though ;-).

**Comment by minrk** [comment]
What actually failed? We don't import BeautifulSoup anywhere in the kernel, as far as I'm aware. Do you have any startup files or extensions registered by default?

**Comment by LienM** [comment]
Do you have any startup files or extensions registered by default?

- Nope, tried in a clean virtual env

What actually failed?

-   I start the Jupyter Notebook from the directory that "parser.py" is in. For some reason it tries to load it then dies because in my file, BeautifulSoup is not correctly defined. 
File "parser.py", line 1, in <module>
    soup = BeautifulSoup(open("reuters21578/reut2-000.sgm"),"html.parser")
NameError: name 'BeautifulSoup' is not defined

But why would it bother to check the "parser.py" file anyway?

**Comment by minrk** [comment]
parser is part of the stdlib, it gets imported by some standard library packages that IPython uses. You can cause the same sort of problem with `random.py` or `email.py` or `socket.py`, etc.
