### ISSUE TITLE
permissionerror: [errno 13] permission denied: '/usr/local/share/jupyter/nbconvert/templates/conf.json'

### ISSUE THREAD

**Issue by banbsyip** [jupyter/jupyter#634]
I set up jupyter in conda env, python:3.7,but the there is a problem occur ,permissionerror: [errno 13] permission denied: '/usr/local/share/jupyter/nbconvert/templates/conf.json'. 
then I run the shell : python -m ipykernel install --user
the result is : Installed kernelspec python3 in /home/yipeng/.local/share/jupyter/kernels/python3.
so I can't add user to /usr/local/share/jupyter/
who can help me,thanks!

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks  and happy hacking! :bowtie:
