### ISSUE TITLE
can not launch jupyter on window x64

### ISSUE THREAD

**Issue by sargiss** [jupyter/jupyter#67]
Python 3.5 is on windows 64.
Use command 
`pip3 install jupyter`
to deploy jupyter packages.

Installation completed successfully.
But after that all attepts to launch it with command `jupyter notebook` fail with error message:there is no MSVCP140.dll

Tried to install VS2013 C++ redistributable package. That did not change anything.

**Comment by minrk** [comment]
- what version of Windows?
- how did you install Python?

My guess is that I did something wrong when building the recent pyzmq release on Windows.

**Comment by minrk** [comment]
More diagnostics:

- Does it fail in the same way if you do `python -c 'import zmq'`?
- Does it work if you do `pip3 install "pyzmq<15"`?

**Comment by franknarf1** [comment]
For what it's worth, I started using Jupyter today and also couldn't get its jupyter-notebook.exe to start.

> - Does it fail in the same way if you do `python -c 'import zmq'`?

gave me `SyntaxError: EOL while scanning string literal`.

>  - Does it work if you do `pip3 install "pyzmq<15"`?

worked fine (allowing Jupyter to launch).

Other info: 

- Python 3.5 
- Win 10 x64
- installed Jupyter with `pip install jupyter` 
- I'm so new to Python that I'm still on my first tutorial page (on "learn x in y minutes"), and so probably can't offer much by way of further info.

**Comment by sargiss** [comment]
Windows 7 ServicePack1
Python 3.5 (32bit) installer for windows was download from official page of python.

`python -c 'import zmq'` causes the same error related with abcent dll.

After installing `pyzmq` everithing was magically cured. jupyter launched with no errors.

**Comment by minrk** [comment]
This should be fixed by pyzmq-15.1
