### ISSUE TITLE
Broken links in kernels page

### ISSUE THREAD

**Issue by marcospb19** [jupyter/jupyter#675]
At the page https://docs.jupyter.org/en/latest/projects/kernels.html.

![image](https://user-images.githubusercontent.com/38900226/221728541-10d87c7f-07c1-4c5d-bab5-455aa62d7a63.png)

ipykernel link leads to 404.

Xeus link points to something else.

**Comment by codewithdev** [comment]
Would happy to pick this up. Let me know if someone can assing this to me.

**Comment by chunqiaohu** [comment]
您好，您的邮件我已经收到，会尽快给您回复，谢谢。

**Comment by jesse-sealand** [comment]
#693

**Comment by ivanov** [comment]
closed by #693
