### ISSUE TITLE
Register IANA media type

### ISSUE THREAD

**Issue by flying-sheep** [jupyter/jupyter#68]
in [this small thread](https://mail.scipy.org/pipermail/ipython-dev/2014-August/014713.html), `application/x-ipynb+json` was declared the “official” MIME type.

Time to replace it with `application/ipynb+json` by [registering with IANA](http://www.iana.org/form/media-types), and getting it into [shared-mime-info](http://cgit.freedesktop.org/xdg/shared-mime-info/tree/HACKING)

**Comment by willingc** [comment]
@takluyver Since the small thread was authored by you, I'm pinging you on what action is needed on this issue. :grey_question:

**Comment by takluyver** [comment]
I'm not sure that we need to do anything. I don't know of any advantage to registering a mime type - Python source code is not a registered type (so it's still `text/x-python`). Neither are common formats like Makefiles, Tex or HDF5, to pick a few at random. And if we change it by dropping the `x-`, then anything which checks the mime type will probably have to support both for at least a few years.

**Comment by willingc** [comment]
Closing - no action required currently.

**Comment by flying-sheep** [comment]
submitted a patch to shared-mime-info: https://bugs.freedesktop.org/show_bug.cgi?id=94878

**Comment by takluyver** [comment]
Thanks @flying-sheep

**Comment by flying-sheep** [comment]
it's fixed! should be in the next release :smile:

**Comment by willingc** [comment]
Rock on @flying-sheep. Nicely done. :tada:

**Comment by flying-sheep** [comment]
thanks! :blush:

**Comment by dmvieira** [comment]
It's very hard without this extension in IANA database: https://github.com/jshttp/mime-db/issues/176#issuecomment-547871252

There are frameworks that use IANA to support your content type when download like this one: https://github.com/http4s/http4s/pull/2932

**Comment by julien-c** [comment]
Dear Jupyter maintainers, would you be able to state in this issue or anywhere else, the following affirmation:

> Jupyter notebooks use file extension `.ipynb` and their intended mime-type is `application/x-ipynb+json`

This sounds like a reasonable statement – from what i know about Jupyter! – and would unlock support in `jshttp/mime-db`, as can be seen in https://github.com/jshttp/mime-db/pull/282

Thanks!
