### ISSUE TITLE
ipykernel  ModuleNotFoundError: No module named 'comm.base_comm'

### ISSUE THREAD

**Issue by zyh3826** [jupyter/jupyter#686]
```
ModuleNotFoundError: No module named 'comm.base_comm'
```
jupyter version: 1.0.0
ipykernel version: 6.23.1
when I low `ipykernel ` to 6.16.0, everything is ok

**Comment by ivanov** [comment]
Thank you for your report, @zyh3826 

If you are still having this issue, please open a ticket either with `ipykernel` or `ipywidgets` and provide reproducible steps that someone can go through to get the same error. What you posted here is not enough information to diagnose what happened.
