### ISSUE TITLE
A git tutorial targeted at scientists by fernando Perez - attached link not working !! [BUG]

### ISSUE THREAD

**Issue by priyanshukumar397** [jupyter/jupyter#688]
Hello Jupyter,

Heading : Scientific computing & data analysis with SciPy stack 
Sub-heading : General Topics in scientific computing 
Topic : A git tutorial targeted at scientists by fernando Perez
Link (fresh & new) : [ **https://berkeley-stat159-f17.github.io/stat159-f17/lectures/01-git/Git-Tutorial..html** ]  
                                [**https://indico.jlab.org/event/157/contributions/1049/attachments/915/1240/FernandoPerez-Jupyter.pdf** ]
Link( not working) : [**https://nbviewer.ipython.org/github/fperez/reprosw/blob/master/Version%20Control.ipynb**]

The above attached link(URL) to the topic is not working (i.e. broken) kindly fix it !!

You can also introduce basic git & their commands in detail rather than just a book or if you want I can contribute to it by writing all the commands in detail for much better understanding !! I hope you find it useful and will fix it soon :)

Thanks & Regards
Ishwar Kumar

**Comment by riyanswat** [comment]
It should work now. I fixed it in the wiki. Here's the updated link: https://nbviewer.org/github/fperez/reprosw/blob/master/Version%20Control.ipynb

**Comment by priyanshukumar397** [comment]
Hey @riyanswat , thanks for the fix !! Can I get an acknowledgement for reporting this error ?  Or can I be added to the contributer's list (if you have any )?

P.S. can I count this as an my first open-source contribution ?

Thanks
Ishwar Kumar
