### ISSUE TITLE
Strange display of Jupyter

### ISSUE THREAD

**Issue by nppn2188** [jupyter/jupyter#70]
I'm new to Jupyter notebook, but the jupyter display looks different than the regular one. 

![image](https://cloud.githubusercontent.com/assets/15900911/11389303/f90f3900-930c-11e5-95f2-a12f4c0671c8.png)

Anyone knows about the issue? and how to resolve it?

**Comment by minrk** [comment]
Looks like missing CSS. How did you install the notebook?

**Comment by nppn2188** [comment]
Thank you Minrk. I just used command prompt with the line 'conda install  jupyter'. 

How to obtain CSS? Sorry, I'm very new to this.

**Comment by nppn2188** [comment]
I tried this:

Import mimetypes
mimetypes.guess_type('file.css')

Output is application/x-css. I read some threads that say it should be replaced with text/css. I'm not sure how to replace it.

**Comment by minrk** [comment]
Can you show the output of the javascript console in your browser (probably View > Developer > Javascript Console)?

**Comment by nppn2188** [comment]
![image](https://cloud.githubusercontent.com/assets/15900911/11425737/12638b4a-9425-11e5-994b-8d62ee68043b.png)

**Comment by minrk** [comment]
And any messages in the terminal where the server is running?

**Comment by nppn2188** [comment]
C:\Users\User1\Desktop>cd example

C:\Users\User1\Desktop\example>jupyter notebook
[I 10:02:14.894 NotebookApp] Serving notebooks from local directory: C:\Users\Us
er1\Desktop\example
[I 10:02:14.895 NotebookApp] 0 active kernels
[I 10:02:14.897 NotebookApp] The IPython Notebook is running at: http://localhos
t:8888/
[I 10:02:14.899 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).

**Comment by minrk** [comment]
Can you run `jupyter notebook --debug` and then visit the notebook page in a Private Browsing tab and show the js console and terminal output for both?

**Comment by nppn2188** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\User1>jupyter notebook --debug
[D 01:14:29.372 NotebookApp] Config changed:
[D 01:14:29.373 NotebookApp] {'NotebookApp': {'log_level': 10}}
[D 01:14:29.375 NotebookApp] Searching ['C:\\Users\\User1', 'C:\\Users\\User1\\.
jupyter', 'C:\\Users\\User1\\Anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter
'] for config files
[D 01:14:29.377 NotebookApp] Attempting to load config file jupyter_config.py in
 path C:\ProgramData\jupyter
[D 01:14:29.378 NotebookApp] Attempting to load config file jupyter_config.json
in path C:\ProgramData\jupyter
[D 01:14:29.379 NotebookApp] Attempting to load config file jupyter_config.py in
 path C:\Users\User1\Anaconda3\etc\jupyter
[D 01:14:29.380 NotebookApp] Attempting to load config file jupyter_config.json
in path C:\Users\User1\Anaconda3\etc\jupyter
[D 01:14:29.381 NotebookApp] Attempting to load config file jupyter_config.py in
 path C:\Users\User1\.jupyter
[D 01:14:29.382 NotebookApp] Attempting to load config file jupyter_config.json
in path C:\Users\User1\.jupyter
[D 01:14:29.383 NotebookApp] Attempting to load config file jupyter_config.py in
 path C:\Users\User1
[D 01:14:29.384 NotebookApp] Attempting to load config file jupyter_config.json
in path C:\Users\User1
[D 01:14:29.386 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.py in path C:\ProgramData\jupyter
[D 01:14:29.387 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.json in path C:\ProgramData\jupyter
[D 01:14:29.389 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.py in path C:\Users\User1\Anaconda3\etc\jupyter
[D 01:14:29.390 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.json in path C:\Users\User1\Anaconda3\etc\jupyter
[D 01:14:29.392 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.py in path C:\Users\User1\.jupyter
[D 01:14:29.393 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.json in path C:\Users\User1\.jupyter
[D 01:14:29.395 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.py in path C:\Users\User1
[D 01:14:29.397 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.json in path C:\Users\User1
[D 01:14:29.767 NotebookApp] Terminals not available (error was No module named
'terminado')
[I 01:14:29.769 NotebookApp] Serving notebooks from local directory: C:\Users\Us
er1
[I 01:14:29.770 NotebookApp] 0 active kernels
[I 01:14:29.771 NotebookApp] The IPython Notebook is running at: http://localhos
t:8888/
[I 01:14:29.773 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[D 01:14:32.061 NotebookApp] Using contents: services/contents
[D 01:14:32.344 NotebookApp] 200 GET /tree (::1) 286.02ms
[D 01:14:34.179 NotebookApp] 304 GET /custom/custom.css (::1) 1403.08ms
[D 01:14:35.039 NotebookApp] 200 GET /static/services/contents.js?v=201511270114
29 (::1) 20.00ms
[D 01:14:35.057 NotebookApp] 200 GET /custom/custom.js?v=20151127011429 (::1) 11
.00ms
[D 01:14:35.418 NotebookApp] 200 GET /api/config/tree?_=1448604874527 (::1) 6.00
ms
[D 01:14:35.424 NotebookApp] 200 GET /api/config/common?_=1448604874528 (::1) 3.
00ms
[D 01:14:35.454 NotebookApp] Native kernel (python3) available from C:\Users\Use
r1\Anaconda3\lib\site-packages\ipykernel\resources
[D 01:14:35.456 NotebookApp] Native kernel (python3) available from C:\Users\Use
r1\Anaconda3\lib\site-packages\ipykernel\resources
[D 01:14:35.464 NotebookApp] 200 GET /api/kernelspecs (::1) 18.00ms
[D 01:14:35.478 NotebookApp] 200 GET /api/sessions?_=1448604874529 (::1) 6.00ms
[D 01:14:36.344 NotebookApp] 200 GET /api/contents?type=directory&_=144860487453
0 (::1) 750.04ms
[D 01:14:46.605 NotebookApp] 200 GET /api/sessions?_=1448604874531 (::1) 3.00ms
[D 01:14:46.844 NotebookApp] 200 GET /api/contents?type=directory&_=144860487453
2 (::1) 103.01ms
[D 01:15:04.633 NotebookApp] 200 GET /api/sessions?_=1448604874533 (::1) 4.00ms
[D 01:15:04.869 NotebookApp] 200 GET /api/contents?type=directory&_=144860487453
4 (::1) 118.01ms
[D 01:15:15.338 NotebookApp] 200 GET /api/sessions?_=1448604874535 (::1) 11.00ms

[D 01:15:15.577 NotebookApp] 200 GET /api/contents?type=directory&_=144860487453
6 (::1) 121.01ms
[D 01:15:19.326 NotebookApp] 200 GET /api/sessions?_=1448550144086 (::1) 3.00ms
[D 01:15:19.610 NotebookApp] 200 GET /api/contents?type=directory&_=144855014408
7 (::1) 174.01ms
[D 01:15:27.684 NotebookApp] Using contents: services/contents
[D 01:15:27.732 NotebookApp] 200 GET /tree (::1) 54.00ms
[D 01:15:28.235 NotebookApp] 200 GET /static/components/jquery-ui/themes/smoothn
ess/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (::1) 8.00ms
[D 01:15:28.252 NotebookApp] 200 GET /static/components/requirejs/require.js?v=2
de44fdcc1fe5e939aa4ce80626b241d (::1) 8.00ms
[D 01:15:28.262 NotebookApp] 200 GET /static/components/es6-promise/promise.min.
js?v=f004a16cb856e0ff11781d01ec5ca8fe (::1) 5.00ms
[D 01:15:28.274 NotebookApp] 200 GET /custom/custom.css (::1) 9.00ms
[D 01:15:28.313 NotebookApp] 200 GET /static/base/images/logo.png?v=7c4597ba713d
804995e8f8dad448a397 (::1) 10.00ms
[D 01:15:28.323 NotebookApp] 200 GET /static/style/style.min.css?v=726bda8146751
57da88304dabb766757 (::1) 31.00ms
[D 01:15:28.419 NotebookApp] 200 GET /static/tree/js/main.min.js?v=26c0ff61319c8
6280776dd7e281acc18 (::1) 142.01ms
[D 01:15:29.346 NotebookApp] 200 GET /static/services/contents.js?v=201511270114
29 (::1) 5.00ms
[D 01:15:29.355 NotebookApp] 200 GET /custom/custom.js?v=20151127011429 (::1) 6.
00ms
[D 01:15:29.706 NotebookApp] 200 GET /api/config/tree?_=1448604928904 (::1) 4.00
ms
[D 01:15:29.716 NotebookApp] Native kernel (python3) available from C:\Users\Use
r1\Anaconda3\lib\site-packages\ipykernel\resources
[D 01:15:29.719 NotebookApp] Native kernel (python3) available from C:\Users\Use
r1\Anaconda3\lib\site-packages\ipykernel\resources
[D 01:15:29.727 NotebookApp] 200 GET /api/kernelspecs (::1) 15.00ms
[D 01:15:29.733 NotebookApp] 200 GET /api/sessions?_=1448604928906 (::1) 4.00ms
[D 01:15:29.743 NotebookApp] 200 GET /api/config/common?_=1448604928905 (::1) 4.
00ms
[D 01:15:29.965 NotebookApp] 200 GET /api/contents?type=directory&_=144860492890
7 (::1) 124.01ms
[D 01:15:33.818 NotebookApp] 304 GET /custom/custom.css (::1) 5.00ms
[D 01:15:33.863 NotebookApp] 200 GET /static/tree/js/main.min.js.map (::1) 61.00
ms

**Comment by nppn2188** [comment]
![image](https://cloud.githubusercontent.com/assets/15900911/11435131/a97a9026-94a4-11e5-97a1-c30327270500.png)

**Comment by franktoffel** [comment]
I work with @nppn2188 and I tried to figured out what was going on. He was using anaconda but yesterday we tried with winpython and same problem appeared.

We also tried different web browsers with no luck. The web try.jupyter.org renders ok, dough.

**Comment by willingc** [comment]
@franktoffel @nppn2188 It looks like you are using Windows 7. Could you post the output of ``conda info -a``? 

It is possible that you are running into a dependency that was not updated by conda when you did the ``conda install jupyter``. See conda troubleshooting docs http://conda.pydata.org/docs/troubleshooting.html#conda-claims-installed . I have in past workshops seen issues with the hard links that conda uses if multiple conda versions installed and/or multiple python versions were installed over time.

**Comment by franktoffel** [comment]
Hi @willingc,

We tried as well WinPython and saw the same problem, but here you have the conda list output:

Current conda install:
 
             platform : win-64
        conda version : 3.18.8
  conda-build version : 1.18.1
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : C:\Users\User1\Anaconda3  (writable)
  default environment : C:\Users\User1\Anaconda3
     envs directories : C:\Users\User1\Anaconda3\envs
        package cache : C:\Users\User1\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
 
# conda environments:
#
root                  *  C:\Users\User1\Anaconda3
 
sys.version: 3.5.0 |Anaconda 2.4.0 (64-bit)| (default...
sys.prefix: C:\Users\User1\Anaconda3
sys.executable: C:\Users\User1\Anaconda3\python.exe
conda location: C:\Users\User1\Anaconda3\lib\site-packages\conda
conda-build: C:\Users\User1\Anaconda3\Scripts\conda-build.exe
conda-convert: C:\Users\User1\Anaconda3\Scripts\conda-convert.exe
conda-develop: C:\Users\User1\Anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\User1\Anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\User1\Anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\User1\Anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\User1\Anaconda3\Scripts\conda-metapackage.exe
conda-pipbuild: C:\Users\User1\Anaconda3\Scripts\conda-pipbuild.exe
conda-server: C:\Users\User1\Anaconda3\Scripts\conda-server.exe
conda-sign: C:\Users\User1\Anaconda3\Scripts\conda-sign.exe
conda-skeleton: C:\Users\User1\Anaconda3\Scripts\conda-skeleton.exe
user site dirs:
 
CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Users\User1\Anaconda3\Library\bin;C:\Program Files (x86)\NVIDIA Corpora
tion\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Fi
les\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft
Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\W
indows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Dell\Dell Data Protecti
on\Access\Advanced\Wave\Gemalto\Access Client\v5\;C:\Program Files (x86)\NTRU Cr
yptosystems\NTRU TCG Software Stack\bin\;C:\Program Files\NTRU Cryptosystems\NTR
U TCG Software Stack\bin\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Progra
m Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Intel\DMIX;C:\Progr
am Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\
Program Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files (x86)\
Common Files\Roxio Shared\OEM\DLLShared\;C:\Program Files (x86)\Common Files\Rox
io Shared\OEM\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\OEM\12
.0\DLLShared\;C:\Program Files (x86)\Roxio\OEM\AudioCore\;C:\Program Files\MATLA
B\R2014b\runtime\win64;C:\Program Files\MATLAB\R2014b\bin;C:\Program Files\MATLA
B\R2011a\runtime\win64;C:\Program Files\MATLAB\R2011a\bin;C:\Program Files (x86)
\PharosSystems\Core;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C
:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn\;C:\Program Files (x86)
\Common Files\AspenTech Shared\;C:\Program Files (x86)\IVI Foundation\IVI\bin;C:
\Program Files\IVI Foundation\IVI\bin;C:\Program Files (x86)\IVI Foundation\VISA
\WinNT\Bin\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x8
6)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\Microsoft SQL Server\110\Tools
\Binn\;C:\Program Files (x86)\MPICH2\bin\;C:\Program Files\VanDyke Software\Clie
nts\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\QuickTime
\QTSystem\;C:\Users\User1\Anaconda3;C:\Users\User1\Anaconda3\Scripts;C:\Users\Us
er1\Anaconda3\Library\bin;C:\Program Files (x86)\JACOBIAN\lib;C:\Program Files (
x86)\JACOBIAN\python;C:\Program Files (x86)\JACOBIAN\gnuplot\bin;C:\Program File
s\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;AspenTech\
Aspen Hydraulics
PYTHONHOME: <not set>
PYTHONPATH: <not set>
 
WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

**Comment by willingc** [comment]
@franktoffel @nppn2188 Thanks for checking. Conda looks up to date.

I think you are running into a Windows Registry setting issue (Similar issue and resolution in last post https://github.com/ipython/ipython/issues/6910).

Additional background on MIME in Windows 7 from Microsoft: https://technet.microsoft.com/en-us/library/cc725608%28v=ws.10%29.aspx

cc/@minrk

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
