### ISSUE TITLE
Broken breadcrumb on "The Jupyter Command" page

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/jupyter#702]
https://docs.jupyter.org/en/latest/use/jupyter-command.html — on this page, the breadcrumbs read "🏠 > Usage > The", not " 🏠  > Usage > The jupyter Command"

![image](https://github.com/jupyter/jupyter/assets/93281816/29709541-a240-43c2-864f-102e8aed6539)

**Comment by ivanov** [comment]
yeah, that's not great - and it looks like all of the other pages have that last breadcrumb severely shortened (just to the first word or two)

**Comment by ivanov** [comment]
this is getting addressed in https://github.com/pydata/pydata-sphinx-theme/pull/1861, closing it here, we'll get the benefit of it when we bring in the next version of pydata theme into these docs.
