### ISSUE TITLE
decision graph not rendering

### ISSUE THREAD

**Issue by brownsarahm** [jupyter/jupyter#708]
[the graph on the using page](https://github.com/jupyter/jupyter/blob/master/docs/source/use/using.rst?plain=1#L29) 

is not [rendering](https://docs.jupyter.org/en/latest/use/using.html)

![Screen Shot 2023-10-31 at 8 31 59 AM](https://github.com/jupyter/jupyter/assets/10656079/ee20884b-a159-4472-bbfb-b8293413e3ef)

**Comment by ivanov** [comment]
thank you for the report, found the fix and put it up in #712
