### ISSUE TITLE
possibly removing qtconsole from jupyter

### ISSUE THREAD

**Issue by ivanov** [jupyter/jupyter#718]
I wanted to start a conversation about the possibility of removing `qtconsole` from the base `jupyter` metapackage. Depending on timelines and feedback, it might makes sense to incorporate this into an eventual 1.1.0 release mentioned in #678

Per comments on [#358](https://github.com/jupyter/jupyter/issues/358) - QT is quite a heavy dependency. At 90 Mb, it is roughly 3 times larger than a complete python language installation from the comment on that issue, and I would venture to guess that the vast majority of our users do not use it.

I've opened a poll on the discourse, so you can fill it out there, or also provide a reaction here:

Please use a reaction to indicate how you feel about removing `qtconsole` from the jupyter meta-package?

:+1: I would welcome this change with enthusiasm
:-1: I would be very unhappy if it was removed 
:confused:  I would be inconvenienced and sad, but I could deal with it :frowning: 
:eyes: I don't use qtconsole, so feel free to remove it

Please leave your thoughts here, or on the [discourse thread.](https://discourse.jupyter.org/t/poll-and-feedback-on-possibly-removing-qtconsole-from-jupyter-metapackage/22882)

**Comment by minrk** [comment]
Seems sensible with current usage, qtconsole seems much more a component of things like Spyder than a standalone application these days. 

Excellent, thoughtful communication of the proposal, @ivanov!

**Comment by ivanov** [comment]
Please consider boosting one of these message so that we can get feedback from more of our users:

https://mastodon.sdf.org/@ivanov/111581177873962864
https://twitter.com/ivanov/status/1735429774158463045
https://www.linkedin.com/posts/paulivanov_poll-and-feedback-on-possibly-removing-qtconsole-activity-7141195557334581248-OPxG

**Comment by 3fon3fonov** [comment]
I personally use qtconsole and jupyter in the [Exo-Striker](https://github.com/3fon3fonov/exostriker) tool:
 
I would be sad if jupyter does not come with a qtconsole, but if qtconsole is developed in a separate repo and is in line with new versions of jupyter, I would not be against.

**Comment by minrk** [comment]
@3fon3fonov it's always been in a separate repo since we started calling things "Jupyter" with the [IPython->Jupyter split](https://blog.jupyter.org/the-big-split-9d7b88a031a7). This is only about the `jupyter` metapackage, which started out re-bundling everything that used to be in IPython. Exo-Striker [already depends directly on qtconsole](https://github.com/3fon3fonov/exostriker/blob/484d11f6b5084475a19b3de7e13ce1c0efc8fef5/pyproject.toml#L31), so it would not see any change from this.

**Comment by mosheleon** [comment]
Lighter is better 🚀 (I use QT but not via Jupyter)

Thank you for the visibility @ivanov 👋

**Comment by Czaki** [comment]
The qtconsole itself does not depend on QT. It only depends on `qtpy` and qt backend needs to be installed separately. So currently, install of Jupyter does not lead to install any of qt version.

**Comment by ivanov** [comment]
@Czaki depends on how it is being installed. what you say might be true for those using pip, but that's not the case for those using conda, or some operating system package managers.

**Comment by goyalyashpal** [comment]
would it be available to be used separately from pip?

i havent used it, but seeing from screenshots on the web, it seems it is like a TUI version of jupyter notebook. am i rihgt? and so, how does it differ from ipython?

[qtconsole screenshot][ss]

[ss]: https://duckduckgo.com/?q=qtconsole&t=vivaldim&iax=images&ia=images&iai=https%3A%2F%2Fwww.spyder-ide.org%2Fblog%2Frelease-qtconsole-440%2Fqtconsole-syntax-highlighting.png

i came here from this mastadoon/[hachyderm post][]

[hachyderm post]: https://hachyderm.io/@ivanov@mastodon.sdf.org/111581177954296849

**Comment by ivanov** [comment]
Thanks everyone who chimed in, the consensus was that it makes sense to remove `qtconsole` from the `jupyter` metapackage, so it does not get installed by default. Users wishing to continue using qtconsole by installing it separately.
