### ISSUE TITLE
Randbits error

### ISSUE THREAD

**Issue by tanmaygoyal875** [jupyter/jupyter#723]
hello I am trying to resolving the problem of randbits which is import error but can't able to resolve please help me 
Also when I import numpy or pandas It shows same error all the time 

ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import numpy as np

File ~/anaconda3/lib/python3.11/site-packages/numpy/__init__.py:157
    155 from . import fft
    156 from . import polynomial
--> 157 from . import random
    158 from . import ctypeslib
    159 from . import ma

File ~/anaconda3/lib/python3.11/site-packages/numpy/random/__init__.py:180
    126 __all__ = [
    127     'beta',
    128     'binomial',
   (...)
    176     'zipf',
    177 ]
    179 # add these for module-freeze analysis (like PyInstaller)
--> 180 from . import _pickle
    181 from . import _common
    182 from . import _bounded_integers

File ~/anaconda3/lib/python3.11/site-packages/numpy/random/_pickle.py:1
----> 1 from .mtrand import RandomState
      2 from ._philox import Philox
      3 from ._pcg64 import PCG64, PCG64DXSM

File numpy/random/mtrand.pyx:1, in init numpy.random.mtrand()

File bit_generator.pyx:40, in init numpy.random.bit_generator()

ImportError: cannot import name randbits

**Comment by shaughnessyo** [comment]
I encountered this problem by having a file "secrets.py" in my project, which conflicts with some files that numpy needs. Changing the file name fixed it for me.

**Comment by chunqiaohu** [comment]
您好，您的邮件我已经收到，会尽快给您回复，谢谢。

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue, as it is not a Jupyter issue. 
Happy hacking! :bowtie:

**Comment by SleeplessShu** [comment]
> is problem by having a file "secrets.py" in my project, which conflicts with some files that numpy needs. Changing the file name fixed it for me.

Muchas gracias, amigo! Your comment solve my problem!
