### ISSUE TITLE
Running the command "$ nox -s docs" gives the following error

### ISSUE THREAD

**Issue by 8Fly** [jupyter/jupyter#732]
![Snipaste_2024-07-13_14-26-25](https://github.com/user-attachments/assets/fe068ed6-1529-4df5-81cc-fb4d3df31f6b)

**Comment by ivanov** [comment]
it looks like you're doing this in Python 2.7?  This is an outdated and unsupported version, Python 2.7 reached its [end of life 4 and a half years ago](https://devguide.python.org/versions/).
