### ISSUE TITLE
Jupyter Kernel Crashes with matplotlib.pyplot Usage

### ISSUE THREAD

**Issue by xiezhipeng-git** [jupyter/jupyter#733]
Some specific details are available at the following link:
https://github.com/microsoft/vscode-jupyter/issues/15834

**Comment by chunqiaohu** [comment]
您好，您的邮件我已经收到，会尽快给您回复，谢谢。

**Comment by ivanov** [comment]
@xiezhipeng-git could you please produce the summary of those details here. I tried following what was reported but could not make sense of it. Please provide a minimal standalone example that reproduces the error you were seeing, as well as the error itself. Also, from a glance at the issue you linked, can you verify that the issue does not occur in a plain python shell (and it if works fine there, also try in an ipython shell)? It is possible that you are just running out of memory creating so many matplotlib plots

**Comment by xiezhipeng-git** [comment]
@ivanov 
```python
import matplotlib.pyplot as plt
from IPython.display import clear_output
for i in range(5100):
    clear_output(wait=True)
    plt.figure()
    plt.plot([1,2], [1,2])
    plt.show()
    
    
    print(i)
    
```
But now I can't meet it
I don't know if it's because I switched to a new CPU. The original CPU crashed due to irregular blue screen crashes and was replaced and repaired

**Comment by ivanov** [comment]
glad you got it fixed, @xiezhipeng-git - sounds like a hardware error and not a jupyter / matplotlib / ipythong bug. Will be closing this, but of course we can re-open if the symptoms come back for you or anyone else.
