### ISSUE TITLE
tab completion problem?

### ISSUE THREAD

**Issue by lalala2047** [jupyter/jupyter#75]
python version:3.4.3
jupyter version:4.0.6
system:mac os x ei 10.11

tab completion doesn't work totally when import any standard module. any can help?

**Comment by takluyver** [comment]
Is this in the notebook? Can you show us a screenshot of what you're doing?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
