### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by LuisDiazUgena** [jupyter/jupyter#76]
Hi!

I've been trying to use jupyter notebook, and when I type in a terminal:

sudo pip3 install jupyter it says: 

```
Requirement already satisfied (use --upgrade to upgrade): jupyter in ./.local/lib/python3.5/site-packages
Cleaning up...
```

Then I type:
```
sudo pip3 install jupyter --upgrade
Requirement already up-to-date: jupyter in ./.local/lib/python3.5/site-packages
Cleaning up...
```

And then I try to run jupyter:

```
jupyter notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 28, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe
```

What can I do tu be able to run this??

Thank you so much!

**Comment by takluyver** [comment]
The `jupyter-notebook` that it's finding is installed in Python 2; it's not trying to run the copy you've installed in Python 3.

Does `~/.local/bin/jupyter-notebook` exist? And is `~/.local/bin` on $PATH?

**Comment by LuisDiazUgena** [comment]
Hi! 

~/.local/bin/jupyter-notebook doesn't exist.

Thanks

**Comment by takluyver** [comment]
Then I'd suggest you `pip3 uninstall jupyter notebook` (i.e. remove both the 'jupyter' and 'notebook' packages) and install them again. It should be creating scripts with a `#!` line for Python 3.

**Comment by LuisDiazUgena** [comment]
I've removed it and now it's running. But I've another problem, I want to develop a notebook using python 3, but seems that the kernel it's not installed. What should I do?

Thank you so much

**Comment by takluyver** [comment]
On 30 November 2015 at 11:23, Luis Diaz <notifications@github.com> wrote:

> I've removed it and now it's running. But I've another problem, I want to
> develop a notebook using python 3, but seems that the kernel it's not
> installed. What should I do?


The kernel for the Python version the notebook is installed in should
automatically be available (i.e. if you installed the notebook with Python
3, Python 3 should be available as a kernel; if you did it with Python 2,
you'll see a Python 2 kernel).

To make the kernel for the other version of Python available, install the
ipykernel package in that version of Python,  and then explicitly install
the kernel using the instructions here:

http://ipython.readthedocs.org/en/latest/install/kernel_install.html

Thomas

**Comment by LuisDiazUgena** [comment]
Hi, I haven't been able to install the kernel that way, but I've used anaconda to install it, and now I'm able to use python 3, but I still got the problem that makes than I'm not able to make notebooks if I'm not using  sudo. This is the error:

```
Unexpected error while saving file: Untitled.ipynb [Errno 13] Permission denied: '/home/luisdiaz/.local/share/jupyter/notebook_secret'
```

It's not possible to run it without being superuser?

Thanks

**Comment by takluyver** [comment]
On 1 December 2015 at 08:34, Luis Diaz <notifications@github.com> wrote:

> Unexpected error while saving file: Untitled.ipynb [Errno 13] Permission denied: '/home/luisdiaz/.local/share/jupyter/notebook_secret'
>
> It's not possible to run it without being superuser?
>
That location is normally user writable, but it has somehow ended up being
owned by root in your case. We should probably do something more graceful,
but it's a bit of a pathological case. You should be able to fix it by
running this in a terminal:

sudo chown -R luisdiaz:luisdiaz ~/.local/share/jupyter

That changes the owner of that directory to your user.

Thomas

**Comment by LuisDiazUgena** [comment]
I've been able to run the program as non root user, but it keeps saying:

![image](https://cloud.githubusercontent.com/assets/6543254/11498919/b349a372-9822-11e5-8fbc-417d3c12d0df.png)

Thanks

**Comment by minrk** [comment]
@LuisDiazUgena thanks!
