### ISSUE TITLE
When including gists every row in the output is divided by a solid line

### ISSUE THREAD

**Issue by KobaKhit** [jupyter/jupyter#78]
I tried including a gist in my jupyter notebook and got the following output.

**A markdown cell**:

```markdown
<script src="https://gist.github.com/KobaKhit/45846b81ee8b28363b4a.js"></script>
```

**Output:**
![screen shot 2015-12-03 at 9 44 41 pm](https://cloud.githubusercontent.com/assets/4805827/11580609/2a07edd0-9a07-11e5-9b0e-7ba280da70f1.png)

As you can see every row is divided by a solid line. It would be nice to be able to include gists without those solid lines. Thanks.

**Comment by takluyver** [comment]
Looking at the code of that script, it's writing elements directly into the document, so it's probably clashing with some of our styles. I don't think there's much we can do about that; it probably needs to be in an iframe.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
