### ISSUE TITLE
Cannot make the Jupyter notebook work (Python kernel) on Windows 7 

### ISSUE THREAD

**Issue by Iki-San** [jupyter/jupyter#86]
Hello,

First of all, thank you so much for all your hard work. Jupyter is just great!
However, I'm pulling out whatever hair I have left trying to make it work (the notebook part) on Windows. I've followed the instructions from http://jupyter.org/ to the letter, read the forums, did my best to make it work, but no luck.

My details are like:
- Windows 7 Professional, 64 bit machine
- tried Anaconda 64 bit or 32 bit, Python 2.7 or Python 3.5 (all possible combos)
- all the other things (Ipython or the Jupyter QTConcole) work like a charm
- every time I try a "jupyter notebook --debug" in the cmd window, I get errors.  The notebook seems to work, but there is a broken link below the Python logo which reads " No Connection to Kernel". The errors (from the cmd window, in chronological order) are:

1) - Terminals not available (error was No module named terminado) - that's easily solvable, I do a "conda install pip" and then a "pip install terminado" 

2) -  Terminals not available (error was No module named fcntl) - that's less easily solvable, but manageable - I do what's suggested at http://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows

3) - Terminals not available (error was No module named termios) - that's where I hit the wall.

Thank you so much!

**Comment by Carreau** [comment]
Terminals are not supported (yet?) on Windows, you should not get error messages on windows, just information messages. 

That being said, the rest of notebook should work correctly without terminals, 
so can you post the error log you get ?



"No Connection to Kernel" seem like an different issue, like your network/antivirus/firewall blocking websocket connexion. 
Usually try offline will all protection disabled to see if it's that.

**Comment by Iki-San** [comment]
Good sir,

First off, thank you so much. Also, you're right. When I tried running it offline, with my Ad-Aware Antivirus turned off, everything worked. So it could just be the antivirus. Any words of advice highly appreciated.  

Please see below for what I get when running "jupyter notebook --debug" with the antivirus turned on (and when the connection to the kernel is not working):

C:\Users\ChestiuniSerioase>jupyter notebook --debug
[D 20:57:25.022 NotebookApp] Config changed:
[D 20:57:25.038 NotebookApp] {'NotebookApp': {'log_level': 10}}
[D 20:57:25.038 NotebookApp] Searching [u'C:\\Users\\ChestiuniSerioase', 'C:\\Us
ers\\ChestiuniSerioase\\.jupyter', 'C:\\Anaconda2\\etc\\jupyter', 'C:\\ProgramDa
ta\\jupyter'] for config files
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_config.py in
 path C:\ProgramData\jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_config.json
in path C:\ProgramData\jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_config.py in
 path C:\Anaconda2\etc\jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_config.json
in path C:\Anaconda2\etc\jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_config.py in
 path C:\Users\ChestiuniSerioase\.jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_config.json
in path C:\Users\ChestiuniSerioase\.jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_config.py in
 path C:\Users\ChestiuniSerioase
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_config.json
in path C:\Users\ChestiuniSerioase
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.py in path C:\ProgramData\jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.json in path C:\ProgramData\jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.py in path C:\Anaconda2\etc\jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.json in path C:\Anaconda2\etc\jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.py in path C:\Users\ChestiuniSerioase\.jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.json in path C:\Users\ChestiuniSerioase\.jupyter
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.py in path C:\Users\ChestiuniSerioase
[D 20:57:25.038 NotebookApp] Attempting to load config file jupyter_notebook_con
fig.json in path C:\Users\ChestiuniSerioase
[D 20:57:25.085 NotebookApp] Terminals not available (error was No module named
termios)
[I 20:57:25.099 NotebookApp] Serving notebooks from local directory: C:\Users\Ch
estiuniSerioase
[I 20:57:25.099 NotebookApp] 0 active kernels
[I 20:57:25.099 NotebookApp] The IPython Notebook is running at: http://localhos
t:8888/
[I 20:57:25.099 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[D 20:57:25.710 NotebookApp] Using contents: services/contents
[D 20:57:25.740 NotebookApp] 200 GET /tree (::1) 31.00ms
[D 20:57:25.927 NotebookApp] 304 GET /custom/custom.css (::1) 125.00ms
[D 20:57:26.006 NotebookApp] 200 GET /static/services/contents.js?v=201512212057
25 (::1) 0.00ms
[D 20:57:26.006 NotebookApp] 200 GET /custom/custom.js?v=20151221205725 (::1) 0.
00ms
[D 20:57:26.006 NotebookApp] 200 GET /api/config/tree?_=1450749445961 (::1) 0.00
ms
[D 20:57:26.006 NotebookApp] 200 GET /api/config/common?_=1450749445962 (::1) 0.
00ms
[D 20:57:26.022 NotebookApp] 200 GET /api/sessions?_=1450749445963 (::1) 0.00ms
[D 20:57:26.022 NotebookApp] Native kernel (python2) available from C:\Anaconda2
\lib\site-packages\ipykernel\resources
[D 20:57:26.022 NotebookApp] Native kernel (python2) available from C:\Anaconda2
\lib\site-packages\ipykernel\resources
[D 20:57:26.022 NotebookApp] 304 GET /api/kernelspecs (::1) 0.00ms
[D 20:57:26.052 NotebookApp] 200 GET /api/contents?type=directory&_=145074944596
4 (::1) 16.00ms
[D 20:57:30.049 NotebookApp] Using contents: services/contents
[D 20:57:30.071 NotebookApp] 200 GET /notebooks/Untitled.ipynb (::1) 22.00ms
[D 20:57:30.084 NotebookApp] 304 GET /custom/custom.css (::1) 1.00ms
[D 20:57:30.108 NotebookApp] 304 GET /static/components/MathJax/MathJax.js?confi
g=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (::1) 1.00ms
[D 20:57:30.173 NotebookApp] 304 GET /static/components/MathJax/config/TeX-AMS_H
TML-full.js?rev=2.5.3 (::1) 0.00ms
[D 20:57:30.269 NotebookApp] 304 GET /custom/custom.js?v=20151221205725 (::1) 0.
00ms
[D 20:57:30.302 NotebookApp] 304 GET /static/components/MathJax/config/Safe.js?r
ev=2.5.3 (::1) 1.00ms
[D 20:57:30.311 NotebookApp] 200 GET /api/config/notebook?_=1450749450212 (::1)
1.00ms
[D 20:57:30.312 NotebookApp] 200 GET /api/config/common?_=1450749450213 (::1) 0.
00ms
[D 20:57:30.335 NotebookApp] Native kernel (python2) available from C:\Anaconda2
\lib\site-packages\ipykernel\resources
[D 20:57:30.336 NotebookApp] Native kernel (python2) available from C:\Anaconda2
\lib\site-packages\ipykernel\resources
[D 20:57:30.338 NotebookApp] 304 GET /api/kernelspecs (::1) 2.00ms
[D 20:57:30.375 NotebookApp] 200 GET /api/contents/Untitled.ipynb?type=notebook&
_=1450749450214 (::1) 28.00ms
[D 20:57:30.378 NotebookApp] 200 GET /nbextensions/widgets/notebook/js/extension
.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.434 NotebookApp] 304 GET /static/components/MathJax/jax/output/HTML-
CSS/fonts/STIX-Web/fontdata.js?rev=2.5.3 (::1) 1.00ms
[D 20:57:30.569 NotebookApp] Native kernel (python2) available from C:\Anaconda2
\lib\site-packages\ipykernel\resources
[D 20:57:30.569 NotebookApp] Starting kernel: ['C:\\Anaconda2\\python.exe', '-m'
, 'ipykernel', '-f', u'C:\\Users\\ChestiuniSerioase\\AppData\\Roaming\\jupyter\\
runtime\\kernel-67007897-a846-43ca-97d5-a0efe7501d05.json']
[D 20:57:30.573 NotebookApp] Connecting to: tcp://127.0.0.1:49941
[I 20:57:30.575 NotebookApp] Kernel started: 67007897-a846-43ca-97d5-a0efe7501d0
5
[D 20:57:30.575 NotebookApp] Kernel args: {'kernel_name': u'python2', 'cwd': u'C
:\\Users\\ChestiuniSerioase'}
[D 20:57:30.575 NotebookApp] 201 POST /api/sessions (::1) 42.00ms
[D 20:57:30.576 NotebookApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?_=
1450749450215 (::1) 1.00ms
[D 20:57:30.582 NotebookApp] 304 GET /static/components/MathJax/extensions/Safe.
js?rev=2.5.3 (::1) 1.00ms
[D 20:57:30.585 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/init.js?v=
20151221205725 (::1) 1.00ms
[D 20:57:30.586 NotebookApp] 200 GET /nbextensions/widgets/notebook/js/widgetare
a.js?v=20151221205725 (::1) 0.00ms
[D 20:57:30.667 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/manager.js
?v=20151221205725 (::1) 1.00ms
[D 20:57:30.668 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_boo
l.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.671 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_flo
at.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.673 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_ima
ge.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.676 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_int
.js?v=20151221205725 (::1) 2.00ms
[D 20:57:30.677 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget.js?
v=20151221205725 (::1) 2.00ms
[D 20:57:30.678 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_lin
k.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.680 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_box
.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.681 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_out
put.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.683 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_col
or.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.684 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_but
ton.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.684 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_str
ing.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.686 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_con
troller.js?v=20151221205725 (::1) 0.00ms
[D 20:57:30.687 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_sel
ection.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.688 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_sel
ectioncontainer.js?v=20151221205725 (::1) 1.00ms
[D 20:57:30.743 NotebookApp] Initializing websocket connection /api/kernels/6700
7897-a846-43ca-97d5-a0efe7501d05/channels
[D 20:57:30.746 NotebookApp] Requesting kernel info from 67007897-a846-43ca-97d5
-a0efe7501d05
[D 20:57:30.746 NotebookApp] Connecting to: tcp://127.0.0.1:49938
[D 20:57:30.786 NotebookApp] 200 GET /static/components/backbone/backbone-min.js
?v=20151221205725 (::1) 2.00ms
[D 20:57:30.803 NotebookApp] 304 GET /nbextensions/widgets/widgets/css/widgets.m
in.css (::1) 1.00ms
[D 20:57:31.259 NotebookApp] Received kernel info: {u'language_info': {u'mimetyp
e': u'text/x-python', u'nbconvert_exporter': u'python', u'name': u'python', u'py
gments_lexer': u'ipython2', u'version': u'2.7.11', u'file_extension': u'.py', u'
codemirror_mode': {u'version': 2, u'name': u'ipython'}}, u'implementation': u'ip
ython', u'implementation_version': u'4.0.1', u'protocol_version': u'5.0', u'bann
er': u'Python 2.7.11 |Anaconda 2.4.1 (32-bit)| (default, Dec  7 2015, 14:13:17)
[MSC v.1500 32 bit (Intel)]\nType "copyright", "credits" or "license" for more i
nformation.\n\nIPython 4.0.1 -- An enhanced Interactive Python.\n?         -> In
troduction and overview of IPython\'s features.\n%quickref -> Quick reference.\n
help      -> Python\'s own help system.\nobject?   -> Details about \'object\',
use \'object??\' for extra details.\n%guiref   -> A brief reference about the gr
aphical user interface.\n', u'help_links': [{u'url': u'http://docs.python.org/2.
7', u'text': u'Python'}, {u'url': u'http://ipython.org/documentation.html', u'te
xt': u'IPython'}, {u'url': u'http://docs.scipy.org/doc/numpy/reference/', u'text
': u'NumPy'}, {u'url': u'http://docs.scipy.org/doc/scipy/reference/', u'text': u
'SciPy'}, {u'url': u'http://matplotlib.org/contents.html', u'text': u'Matplotlib
'}, {u'url': u'http://docs.sympy.org/latest/index.html', u'text': u'SymPy'}, {u'
url': u'http://pandas.pydata.org/pandas-docs/stable/', u'text': u'pandas'}]}
[D 20:57:31.263 NotebookApp] Opening websocket /api/kernels/67007897-a846-43ca-9
7d5-a0efe7501d05/channels
[D 20:57:31.265 NotebookApp] Connecting to: tcp://127.0.0.1:49938
[D 20:57:31.269 NotebookApp] Connecting to: tcp://127.0.0.1:49939
[D 20:57:31.270 NotebookApp] Connecting to: tcp://127.0.0.1:49940
[D 20:57:31.279 NotebookApp] 200 GET /api/kernels/67007897-a846-43ca-97d5-a0efe7
501d05?_=1450749450216 (::1) 2.00ms
[D 20:57:32.299 NotebookApp] Initializing websocket connection /api/kernels/6700
7897-a846-43ca-97d5-a0efe7501d05/channels
[D 20:57:32.305 NotebookApp] Opening websocket /api/kernels/67007897-a846-43ca-9
7d5-a0efe7501d05/channels
[D 20:57:32.305 NotebookApp] Connecting to: tcp://127.0.0.1:49938
[D 20:57:32.306 NotebookApp] Connecting to: tcp://127.0.0.1:49939
[D 20:57:32.308 NotebookApp] Connecting to: tcp://127.0.0.1:49940
[D 20:57:32.309 NotebookApp] 200 GET /api/kernels/67007897-a846-43ca-97d5-a0efe7
501d05?_=1450749450217 (::1) 0.00ms
[D 20:57:33.326 NotebookApp] Initializing websocket connection /api/kernels/6700
7897-a846-43ca-97d5-a0efe7501d05/channels
[D 20:57:33.332 NotebookApp] Opening websocket /api/kernels/67007897-a846-43ca-9
7d5-a0efe7501d05/channels
[D 20:57:33.334 NotebookApp] Connecting to: tcp://127.0.0.1:49938
[D 20:57:33.336 NotebookApp] Connecting to: tcp://127.0.0.1:49939
[D 20:57:33.338 NotebookApp] Connecting to: tcp://127.0.0.1:49940

**Comment by Carreau** [comment]
> First off, thank you so much. Also, you're right. When I tried running it offline, with my Ad-Aware Antivirus turned off, everything worked. So it could just be the antivirus. Any words of advice highly appreciated.

You will just have to configure your antivirus not to block the websocket connexion. Unfortunately, my experience on that is limitted, as i havent touched an antivirus in many years. 

The `--debug` log shows nothing anormal, as the antivirus is likely intercepting things as a too low level for Jupyter to ever notice.
You can try to ask on the google group mailing list, potentially other users with the same antivirus will be able to tell you how to configure it. 

I'm closing the issue, but feel free to continue writing.

**Comment by merinoffff** [comment]
I, having encountered it, confirm this issue being of the antiviral nature, Kaspersky specifically. 

> [W 19:37:27.154 NotebookApp] zmq message arrived on closed channel
[W 19:37:53.975 NotebookApp] zmq message arrived on closed channel
[W 19:37:53.977 NotebookApp] zmq message arrived on closed channel

**Comment by davegrice-gas** [comment]
Confirming the above.  Kaspersky Endpoint Security had port 8888 among the list of "Monitored Ports".  Simply unchecking it from the list immediately resolved this symptom for me.

**Comment by Fjedor** [comment]
The workaround, though i would not prefer it, is to jupyter notebook twice. Then close the first launch altogether. That way you would be working on a different port which is fine with Kaspersky it seems. 
I am forced to go that way, bcz i do not have the needed admin rights to change Kasper monitoring settings. Hope that helps.

**Comment by semartin3** [comment]
thanks @Fjedor !

**Comment by takluyver** [comment]
If you want to run the notebook on a different port, you can do it like this:

```
jupyter notebook --port 8889
```

Or you can [configure it](http://jupyter-notebook.readthedocs.io/en/latest/config_overview.html) to start on a different port without needing to enter it every time:

```python
c.NotebookApp.port = 8889
```

That should be easier than starting it twice and killing the first one. :-)

**Comment by Fjedor** [comment]
That's what I was looking for. Thanks

**Comment by dreme** [comment]
I had the same problem with my Anaconda Jupyter Notebook being blocked by my anti-virus software, which in my case was BitDefender Internet Security 2018

In my case I manage to get around it by disabling the “Block port scans in the network” feature, i.e.:

1.	Click the "B" icon on the left sidebar of the Bitdefender interface.
2.	Click the VIEW FEATURES link.
3.	Click the GEAR icon in the lower-right corner of the FIREWALL pane.
4.	Select the SETTINGS tab.
5.	Turn off the “Block port scans in the network” feature

**Comment by vkrmad** [comment]
@Carreau ,
sir i have the same problem but with different errors  on the command line,
here is what appears on my anaconda prompt after i write 
jupyter notebook --debug 


(base) C:\Users\Vivek Prem Pandey>jupyter notebook --debug
[D 05:02:58.526 NotebookApp] Searching [u'C:\\Users\\Vivek Prem Pandey', 'C:\\Users\\Vivek Prem Pandey\\.jupyter', 'C:\\ProgramData\\Anaconda2\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 05:02:58.526 NotebookApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 05:02:58.532 NotebookApp] Looking for jupyter_config in C:\ProgramData\Anaconda2\etc\jupyter
[D 05:02:58.532 NotebookApp] Looking for jupyter_config in C:\Users\Vivek Prem Pandey\.jupyter
[D 05:02:58.532 NotebookApp] Looking for jupyter_config in C:\Users\Vivek Prem Pandey
[D 05:02:58.532 NotebookApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 05:02:58.532 NotebookApp] Looking for jupyter_notebook_config in C:\ProgramData\Anaconda2\etc\jupyter
[D 05:02:58.532 NotebookApp] Loaded config file: C:\ProgramData\Anaconda2\etc\jupyter\jupyter_notebook_config.json
[D 05:02:58.532 NotebookApp] Looking for jupyter_notebook_config in C:\Users\Vivek Prem Pandey\.jupyter
[E 05:02:58.532 NotebookApp] Exception while loading config file C:\Users\Vivek Prem Pandey\.jupyter\jupyter_notebook_config.py
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\traitlets\config\application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "C:\ProgramData\Anaconda2\lib\site-packages\traitlets\config\loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "C:\ProgramData\Anaconda2\lib\site-packages\traitlets\config\loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "C:\ProgramData\Anaconda2\lib\site-packages\ipython_genutils\py3compat.py", line 280, in execfile
        exec(compiler(scripttext, filename, 'exec'), glob, loc)
      File "C:\Users\Vivek Prem Pandey\.jupyter\jupyter_notebook_config.py", line 101
        c.NotebookApp.browser = 'chrome''
                                        ^
    SyntaxError: EOL while scanning string literal
[D 05:02:58.542 NotebookApp] Looking for jupyter_notebook_config in C:\Users\Vivek Prem Pandey
[D 05:03:10.757 NotebookApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 05:03:10.759 NotebookApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\Anaconda2\etc\jupyter\jupyter_notebook_config.d\jupyterlab.json
        C:\ProgramData\Anaconda2\etc\jupyter\jupyter_notebook_config.json
[D 05:03:10.769 NotebookApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\Vivek Prem Pandey\.jupyter\jupyter_notebook_config.json
[I 05:03:11.924 NotebookApp] JupyterLab extension loaded from C:\ProgramData\Anaconda2\lib\site-packages\jupyterlab
[I 05:03:11.924 NotebookApp] JupyterLab application directory is C:\ProgramData\Anaconda2\share\jupyter\lab
[I 05:03:12.201 NotebookApp] Serving notebooks from local directory: C:\Users\Vivek Prem Pandey
[I 05:03:12.203 NotebookApp] The Jupyter Notebook is running at:
[I 05:03:12.203 NotebookApp] http://localhost:8888/?token=174bdaf597a1aedfb28cfa5be733f721752696bb00a674a0
[I 05:03:12.203 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 05:03:12.242 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/Vivek%20Prem%20Pandey/AppData/Roaming/jupyter/runtime/nbserver-14300-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=174bdaf597a1aedfb28cfa5be733f721752696bb00a674a0
[D 05:03:15.079 NotebookApp] Accepting token-authenticated connection from ::1
[D 05:03:15.088 NotebookApp] Using contents: services/contents
[D 05:03:15.608 NotebookApp] Path base/images/favicon.ico served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\base\images\favicon.ico
[D 05:03:15.638 NotebookApp] Path components/jquery-ui/themes/smoothness/jquery-ui.min.css served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\components\jquery-ui\themes\smoothness\jquery-ui.min.css
[D 05:03:15.654 NotebookApp] Path components/jquery-typeahead/dist/jquery.typeahead.min.css served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\components\jquery-typeahead\dist\jquery.typeahead.min.css
[D 05:03:15.688 NotebookApp] Path style/style.min.css served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\style\style.min.css
[D 05:03:15.706 NotebookApp] Path components/es6-promise/promise.min.js served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\components\es6-promise\promise.min.js
[D 05:03:15.880 NotebookApp] Path components/preact/index.js served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\components\preact\index.js
[D 05:03:15.931 NotebookApp] Path components/proptypes/index.js served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\components\proptypes\index.js
[D 05:03:15.970 NotebookApp] Path components/preact-compat/index.js served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\components\preact-compat\index.js
[D 05:03:16.046 NotebookApp] Path components/requirejs/require.js served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\components\requirejs\require.js
[D 05:03:16.118 NotebookApp] Path base/images/logo.png served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\base\images\logo.png
[D 05:03:16.121 NotebookApp] Path tree/js/main.min.js served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\tree\js\main.min.js
[D 05:03:16.558 NotebookApp] 200 GET /tree?token=174bdaf597a1aedfb28cfa5be733f721752696bb00a674a0 (::1) 1479.00ms
[D 05:03:16.572 NotebookApp] 200 GET /api/sessions?_=1552865229501 (::1) 7.00ms
[D 05:03:16.585 NotebookApp] 200 GET /api/terminals?_=1552865229502 (::1) 6.00ms
[D 05:03:16.823 NotebookApp] 200 GET /api/contents?type=directory&_=1552865229503 (::1) 51.00ms
[D 05:03:16.828 NotebookApp] Path custom.css served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\custom\custom.css
[D 05:03:16.838 NotebookApp] 304 GET /custom/custom.css (::1) 11.00ms
[D 05:03:17.655 NotebookApp] Path services\contents.js served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\services\contents.js
[D 05:03:17.688 NotebookApp] 200 GET /static/services/contents.js?v=20190318050258 (::1) 34.00ms
[D 05:03:17.813 NotebookApp] Paths used for configuration of tree:
        C:\ProgramData\jupyter\nbconfig\tree.json
[D 05:03:17.822 NotebookApp] Paths used for configuration of tree:
        C:\ProgramData\Anaconda2\etc\jupyter\nbconfig\tree.json
[D 05:03:17.828 NotebookApp] Paths used for configuration of tree:
        C:\Users\Vivek Prem Pandey\.jupyter\nbconfig\tree.json
[D 05:03:17.859 NotebookApp] 200 GET /api/config/tree?_=1552865597199 (::1) 51.00ms
[D 05:03:17.884 NotebookApp] Found kernel python2 in C:\ProgramData\Anaconda2\share\jupyter\kernels
[D 05:03:18.197 NotebookApp] 304 GET /api/kernelspecs (::1) 320.00ms
[D 05:03:18.209 NotebookApp] 200 GET /api/terminals?_=1552865597203 (::1) 2.00ms
[D 05:03:18.224 NotebookApp] 200 GET /api/sessions?_=1552865597202 (::1) 2.00ms
[D 05:03:18.236 NotebookApp] Path custom.js served from C:\ProgramData\Anaconda2\lib\site-packages\notebook\static\custom\custom.js
[D 05:03:18.272 NotebookApp] 200 GET /custom/custom.js?v=20190318050258 (::1) 39.00ms
[D 05:03:18.280 NotebookApp] 200 GET /api/terminals?_=1552865597201 (::1) 3.00ms
[D 05:03:18.289 NotebookApp] Paths used for configuration of common:
        C:\ProgramData\jupyter\nbconfig\common.json
[D 05:03:18.293 NotebookApp] Paths used for configuration of common:
        C:\ProgramData\Anaconda2\etc\jupyter\nbconfig\common.json
[D 05:03:18.298 NotebookApp] Paths used for configuration of common:
        C:\Users\Vivek Prem Pandey\.jupyter\nbconfig\common.json
[D 05:03:18.303 NotebookApp] 200 GET /api/config/common?_=1552865597200 (::1) 17.00ms
[D 05:03:18.364 NotebookApp] 200 GET /api/contents?type=directory&_=1552865597204 (::1) 56.00ms

really need your help ,thank you .
