### ISSUE TITLE
Check and update documentation and potentially stale info about Docker images

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyter#87]
While this is about Docker and arguably could have been filed in [our docker repo](https://github.com/jupyter/docker-demo-images), I think it's worth putting it here as our main "docs central" should always be a good place for folks to find their bearings.

[This blog post](http://blog.dscpl.com.au/2015/12/running-ipython-as-docker-container.html) by @GrahamDumpleton has some good notes and details from a user's perspective on his experiences setting up our Docker images and finding info about them.

We should go over this post and ensure that any possible dead-ends he identifies can be improved (such as, for deprecated images, pointing out where users should look instead, so they don't feel like they hit a dead end).

Pinging @willingc as you might be able to put this on your radar, and thanks to @ctb for bringing it to my attention.

**Comment by willingc** [comment]
@fperez It's on my radar to work to improve the experience for users. Thanks @ctb and @grahamdumpleton for your insights. Please leave any additional helpful thoughts that you may have on this issue.

I'm going to file issues in [jupyter/docker-demo-images](https://github.com/jupyter/docker-demo-images) and [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks) so there is awareness among the developers that work on these docker-related repos.

**Comment by fperez** [comment]
Thanks, Carol!

**Comment by parente** [comment]
I posted to the group about the plethora of docker images about a month back. There's a laundry list here of all the images and their current state as best I could tell:

https://groups.google.com/forum/#!searchin/jupyter/docker/jupyter/tfVaVCQaNXM/0XuwaEBlCwAJ

I did take a pass through and mark those that I believe to be deprecated as such. I have not taken action on the other comment I made in the original post about cataloging which images exist and what their purpose is beyond the README in docker-stacks for those specific images.

**Comment by willingc** [comment]
- [ ] Consider creating an "official" Jupyter notebook repository [DockerHub docs on official images](https://docs.docker.com/docker-hub/official_repos/)

**Comment by parente** [comment]
One issue we did not address after looking through the Docker images the last time was how to position the Docker image for jupyter/notebook (from github.com/jupyter/notebook) vs the "batteries included" images from docker-stacks (jupyter/scipy-notebook, jupyter/r-notebook, jupyter/all-spark-notebook, etc.). As it currently stands, the Dockerfile in jupyter/notebook sets up an image that is based on HEAD of the master branch and includes assets needed for development of the notebook whereas the docker-stacks images are all based on the last stable release available in conda. Unfortunately, the Docker Hub automated builds assume the README of the repo is the one to post to the Hub as well on every build, so there's little indication other than in the title at https://hub.docker.com/r/jupyter/notebook/ that this image is bleeding-edge Jupyter Notebook and probably not suitable for more users.

**Comment by willingc** [comment]
I'm closing this issue since substantial good work has been done by @parente and @jakirkham on docker-stacks. If there are still unresolved actions in this issue, please reopen.
