### ISSUE TITLE
IPython is not a python package after installing jupyter directly on Windows

### ISSUE THREAD

**Issue by boctorz** [jupyter/jupyter#89]
I have Python2.7 on my Windows. If I just install jupyter using 

    pip install jupyter
without ipython installed before, then the IPython directory has no `__init__.py` file so that it is not a valid package, and `jupyter notebook` fails.
If I install ipython first with

    pip install ipython
then install jupyter, everything is fine with no problem.

**Comment by takluyver** [comment]
What version of pip do you have? That's a really weird problem.

**Comment by boctorz** [comment]
It seems some problems happened in my system, not the jupyter. I'm sorry for the misinformation. My pip version is 7.1.2. And I redo the whole process just now: 

    pip uninstall jupyter
    pip uninstall ipython 
    pip install jupyter

and the problem is gone, the last command first installs ipython with pip. 
I think the problem I encountered was due to some install-uninstall-reinstall process with ipython before.
