### ISSUE TITLE
Investigate readthedocs yaml file.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#90]
Note: this is likely a potential improvement for all the jupyter repos. 

Readthedocs now have configuration possible via a yml file, as well as conda:
  - http://docs.readthedocs.org/en/latest/conda.html
  - http://docs.readthedocs.org/en/latest/yaml-config.html

it is noticeably painful to set the parameter of rtd correctly via the web interface. 
I think  it would be great to try this yaml thing and potentially give feedback while the feature is still in beta phase.

**Comment by minrk** [comment]
Good idea.

**Comment by willingc** [comment]
Will take a look at this later today. Thanks @carreau. 

FYI, I had a discussion with Eric yesterday about RTD's subprojects setting to see if it currently supports search across projects. Right now, it does not. It just allows hosting under one CNAME. He's hoping RTD will get funding for search across multiple repos and it's something on his radar.

**Comment by willingc** [comment]
Closing since we have been using ``readthedoc.yml`` on most doc builds at this point.
