### ISSUE TITLE
Differing IPython and Jupyter behaviour in virtualenvs

### ISSUE THREAD

**Issue by jgosmann** [jupyter/jupyter#95]
It seems that the `~/.ipython/profile_default/startup/...` files are executed in a different environment depending on whether I invoke `ipython` or `jupyter console` in a virtualenv.

I have a Python package installed in my system site packages and in a virtualenv (in two different versions). If I invoke `ipython`, it seems that `sys.path` is adjusted for the virtualenv first before the startup file is executed and the correct package is loaded. However, with `jupyter console` (also in the virtualenv) it seems that the startup file is executed (loading the wrong package in system site packages) and then the path is adjusted. Upon executing the first command it appears the startup file is executed again, but because the package was already loaded it won't be replaced with the correct version.

Installing jupyter in the virtualenv fixes this problem, but I am wondering: What is the intended behaviour? (It would be convenient if it was not necessary to install jupyter in every virtualenv.) Is the different behaviour of the `ipython` and `jupyter` command intended?

**Comment by takluyver** [comment]
`ipython console` should be a synonym for `jupyter console`, but if IPython is installed inside the virtualenv and jupyter isn't, that might explain it.

In general, the startup files will be run in whichever Python is running IPython; if that's the virtualenv Python, they'll run inside the virtualenv. *However*, if IPython notices that it was started with a virtualenv active, it will add the virtualenv to sys.path, even if IPython itself is installed outside it. I think we did something to prevent that for kernels, but I can't find it now.

You can make different Pythons available to Jupyter by installing kernel specs:
http://ipython.readthedocs.org/en/latest/install/kernel_install.html

**Comment by jgosmann** [comment]
> but if IPython is installed inside the virtualenv and jupyter isn't, that might explain it.

Neither was installed in the virtualenv.

**Comment by takluyver** [comment]
Is `sys.executable` the same in both cases?

**Comment by jgosmann** [comment]
I just noticed that I have to correct myself: `ipython console` and `jupyter console` show the same behaviour. But `ipython` (without console) and `ipython console`/`jupyter console` do not. I will edit my original comment accordingly.

`sys.executable` is the same in all cases: `'/home/jgosmann/.pyenv/versions/2.7.10/bin/python2.7'`

**Comment by takluyver** [comment]
Ah, OK, that makes a bit more sense. `jupyter console` starts the kernel in a separate process from the frontend and talks to it. `ipython console` is just the older name for the same thing. `ipython` runs a single process, with the interface and code execution in the same process. It's quite possible that there are some differences between the two, though I'm not yet sure exactly what causes this.

**Comment by takluyver** [comment]
Still a bit puzzled - on my system, it looks like the virtualenv-detecting stuff is happening before startup scripts run in both cases.

What package are you importing? If it's something that's used in the IPython kernel machinery, IPython itself might be importing it before your script is run.

**Comment by jgosmann** [comment]
No, the imported package ([nengo](https://github.com/nengo/nengo)) is unrelated to IPython.

**Comment by takluyver** [comment]
Thinking about this prompted me to open ipython/ipykernel#96 - that's intended for discussion, but if accepted, it would make a deliberate difference in behaviour for this: any `jupyter` commands would ignore the active virtualenv. You would still be able to set up a kernel for the virtualenv, or install jupyter+ipython inside the virtualenv, but it wouldn't automatically pick up the `$VIRTUAL_ENV` environment variable.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:

**Comment by phejimlin** [comment]
Sorry, It's there any way to set jupyter notebook auto add the virtualenv to sys.path even if jupyter itself is installed outside virtualenv? 
Now, I just can sys.path.append(virtualenv path) to work around.

**Comment by takluyver** [comment]
You can do it using a startup file - see ipython/ipykernel#96 for more discussion.
