### ISSUE TITLE
`jupyter notebook` yields "0:42: execution error: File some object wasn’t found. (-43)"

### ISSUE THREAD

**Issue by nchammas** [jupyter/jupyter#96]
Just installed Jupyter per [the instructions](http://jupyter.readthedocs.org/en/latest/install.html) and ran following:

```
jupyter notebook
```

However, this does not open the Notebook web application in my web browser as [the docs promise](http://jupyter.readthedocs.org/en/latest/running.html).

Instead, I get this:

```
$ jupyter notebook
[I 17:42:54.245 NotebookApp] Serving notebooks from local directory: /Users/nicholaschammas
[I 17:42:54.245 NotebookApp] 0 active kernels 
[I 17:42:54.245 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 17:42:54.245 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
0:42: execution error: File some object wasn’t found. (-43)
```

If I manually navigate my browser to `localhost:8888` things seem to be working, so that's fine. But perhaps there is something off about the startup or about [the docs](http://jupyter.readthedocs.org/en/latest/running.html) that needs to be looked into.

I wasn't sure where to report this, so I thought I'd start with the docs site.

I'm running Jupyter 4.0.6. (For some reason, `pip3 install -U jupyter` doesn't give me the latest release, which appears to be 4.1.0.)

**Comment by takluyver** [comment]
`jupyter notebook` starts the server and then opens a web browser pointing to it using the [webbrowser module](https://docs.python.org/3/library/webbrowser.html). This line looks like whatever browser it's trying to start crashing:

```
0:42: execution error: File some object wasn’t found. (-43)
```

Is your `$BROWSER` environment variable set?

**Comment by nchammas** [comment]
Nope, `$BROWSER` is not set.

Actually, there does seem to be something wrong with my setup. If I change my default browser from Chrome to Safari, it works seamlessly.

For the record, I'm on OS X and `open http://...` yields the following with Chrome as the default browser:

```
LSOpenURLsWithRole() failed with error -600 for the URL http://localhost:8888.
```

`open` has no issues when Safari is the default browser. So I think this is the root issue.

**Comment by ilfreddy** [comment]
I experienced the same problem. It worked again just by closing Chrome and letting jupyter-lab launch chrome.
