### ISSUE TITLE
new notebook option UI is confusing.

### ISSUE THREAD

**Issue by SimpleExpress** [jupyter/jupyter#97]
when I start the server by command ```jupyter notebook```, the ___Notebooks___ options is disabled, even when I uninstall and then re-install all related packages, it still can't work.
my env is python3, mac osx 10.11.2, please kindly suggest, thanks.
<img width="1062" alt="capture" src="https://cloud.githubusercontent.com/assets/1047330/12407042/e7906cec-be8d-11e5-942b-111be929540c.png">

**Comment by willingc** [comment]
@SimpleExpress Here's a gif that demonstrates the usage of the New menu. The Notebooks label is not selectable. Below the Notebooks label, the new notebook type may be selected to create a new notebook. The items that are displayed under the notebook label are the language kernels that are currently installed and useable by Jupyter notebook. For example, selecting Python 3 will create a new notebook using Python 3. I hope this helps to clarify.

![newnotebook](https://cloud.githubusercontent.com/assets/2680980/12410931/8db8da24-be2e-11e5-846b-416dc6959505.gif)

cc/@carreau @captainsafia Perhaps there should be a clarification if one hovers over the Notebooks label.

**Comment by SimpleExpress** [comment]
@willingc so Notebooks is actually a label with python options below, now I see the usage. Really appreciate your clarification.

**Comment by willingc** [comment]
@SimpleExpress :+1:

**Comment by Carreau** [comment]
I'll reopen and just ping @ellisonbg as it is not the only time I saw this confusing. I think wee should do UI testing/rething the UI there.

**Comment by willingc** [comment]
Thanks @Carreau.

**Comment by takluyver** [comment]
I think it should be a bit more visually distinct from the clickable menu entries. At the moment, it's aligned, almost the same colour and almost the same size (12px vs 13px).

Here it is shifted 5px left, the font size dropped to 10px, and italicised, for instance:

![screenshot from 2016-01-19 16 31 28](https://cloud.githubusercontent.com/assets/327925/12424881/1b545cf0-beca-11e5-95a2-8d61671998a3.png)

**Comment by ellisonbg** [comment]
Yeah, I think this could be improved. Let's ping @cameronoelsen on it.

On Tue, Jan 19, 2016 at 8:33 AM, Thomas Kluyver <notifications@github.com>
wrote:

> I think it should be a bit more visually distinct from the clickable menu
> entries. At the moment, it's aligned, almost the same colour and almost the
> same size (12px vs 13px).
>
> Here it is shifted 5px left, the font size dropped to 10px, and
> italicised, for instance:
>
> [image: screenshot from 2016-01-19 16 31 28]
> <https://cloud.githubusercontent.com/assets/327925/12424881/1b545cf0-beca-11e5-95a2-8d61671998a3.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter/issues/97#issuecomment-172908677>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cameronoelsen** [comment]
@takluyver & @ellisonbg, I definitely think that the "Notebooks" header should be dropped down in font size from 12px to something around 10px or 9px, should definitely stay the shade of gray but I don't think it needs to be italicized.

Here is a mockup of the menu using this ^, thoughts?:
![notebook_selector](https://cloud.githubusercontent.com/assets/6437976/12460935/23d73a5e-bf6b-11e5-9fb2-849d9fa3a8bd.png)

**Comment by Carreau** [comment]
How would an inverted header look like ? (background gray, text white)

**Comment by cameronoelsen** [comment]
When we do something like that it feels like it is selected or something.
![invert_menu](https://cloud.githubusercontent.com/assets/6437976/12461360/56ae7b16-bf6d-11e5-8449-0d03c7cd5ce6.png)

I tried doing a header with an underline that is shorter than the width of the popup window (my second favorite):
![line_menu](https://cloud.githubusercontent.com/assets/6437976/12461436/c278812a-bf6d-11e5-955f-634aa012b1fd.png)

And one last pass with the line going full width with the text centered between the two dividers:
![full_line](https://cloud.githubusercontent.com/assets/6437976/12461447/cff52d76-bf6d-11e5-9995-31020b760d5a.png)

**Comment by takluyver** [comment]
Of those, I think I like the short underline one best, followed by the first one with no decoration.

Is there any mileage in pushing it out of alignment with the clickable menu entries? In my experimentation, I felt like that was a pretty good signal that it was distinct.

**Comment by dsblank** [comment]
As a data point, I find gray on white hard to read. Making it even smaller than the rest makes it appear as a gray smudge. I assume it says "Notebooks" :) Seriously though, my eyes don't work as well as they used too, and you should keep in mind low-vision users. I would recommend that you don't have any text anywhere in the UI that small.

**Comment by willingc** [comment]
I agree with @dsblank on the font size in gray. The size is more of an issue for me than the gray. I like the version with the short underline or the first one. Should "Notebooks" be changed to "Notebook" to be consistent with the singular "text file"/"folder"/"terminal"?
